### ISSUE TITLE
Update new jobs execution endpiont

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow-ui#1006]
With the performance improvement addressed via https://github.com/spring-cloud/spring-cloud-dataflow/issues/2583, we need to have the UI updated with the new REST endpoint to retrieve the thin version of the job executions (without step executions but with just the step execution count).

**Comment by sabbyanandan** [comment]
@oodamien: The backend commit is ready via https://github.com/spring-cloud/spring-cloud-dataflow/commit/e3b8896e139433566086d4d9a666c93268cb67ce. Let's go ahead with your inflight PR to adapt to the changes on the UI side.
