### ISSUE TITLE
Add the option to rollback to a previous stream-version

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1012]
As a user, after when updating the stream with different options, I'd like to also have the option to pick and choose to rollback to the previous version from the stream history.

Currently, I see the history showing up as:
![image](https://user-images.githubusercontent.com/1562654/50299686-0ed40880-0437-11e9-83fe-3f4f0a5d8f4e.png)

It'd be nice to have the option from the list or the history page, to rollback to a pinned version. This would be an alternative to what we do via `stream rollback ... ` in the shell.

**Comment by oodamien** [comment]
@sabbyanandan What are the conditions to allow the rollback on a history?
- The stream should be deployed (status)
- The selected history should be not deployed (status)

**Comment by sabbyanandan** [comment]
@oodamien: Both of those conditions appear to be a valid assumption. I'd be curious to see the UX on how this can be done from the history page. It might be useful to review Spinnaker/Helm's rollback offering from their respective dashboards.
