### ISSUE TITLE
Verify client-side paging in App List page

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1022]
As a developer, I'd like to revisit the pagination in the Apps List page to make sure it is taking advantage of the `findAll(Pageable)` support available from the backend. 

This may already work this way, so let's just confirm and close, if it does.

Relates to spring-cloud/spring-cloud-dataflow#1401

**Comment by oodamien** [comment]
@sabbyanandan On the client-side, all the apps are retrieve to group by name (many versions).
The pageable is not used.

**Comment by sabbyanandan** [comment]
Thank you for the confirmation.
