### ISSUE TITLE
Composed Task definition doesn't render as a connected graph

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1026]
As a user, while attempting to create the following CT in v1.7.3, I notice that each of the nodes is individually created as Task definitions, but I'm unable to visually see the connected graph even at the parent definition level.

Definition:
> <extractDB: timestamp || extractFiles: timestamp> && merge: timestamp && cleanse: timestamp && <writetohdfs: timestamp || transform: timestamp && writetos3: timestamp>

Result:
![image](https://user-images.githubusercontent.com/1562654/51131140-aed94380-17e3-11e9-8fa0-567eb19bb3fb.png)
![image](https://user-images.githubusercontent.com/1562654/51131189-d6301080-17e3-11e9-8fa9-5d47009c4b2b.png)

In the previous releases, I'm used to seeing the connected DAG as follows.
![image](https://user-images.githubusercontent.com/1562654/51131311-3921a780-17e4-11e9-9422-86ef66415100.png)

**Comment by BoykoAlex** [comment]
I think it is the problem on the server side.
The CT def creation goes off to the server as a POST request:
```
http://localhost:4200/tasks/definitions?definition=%3CextractDB:%20timestamp%20%7C%7C%20extractFiles:%20timestamp%3E%20%26%26%20merge:%20timestamp%20%26%26%20cleanse:%20timestamp%20%26%26%20%3Cwritetohdfs:%20timestamp%20%7C%7C%20transform:%20timestamp%20%26%26%20writetos3:%20timestamp%3E&name=task-1
```

The response is:
```
{"name":"task-1","dslText":"task-1","composed":true,"lastTaskExecution":null,"status":"UNKNOWN","_links":{"self":{"href":"http://localhost:4200/tasks/definitions/task-1"}}}
```

Somehow server creates a number of CTs for that definition...

**Comment by aclement** [comment]
Does that make it my problem?

**Comment by sabbyanandan** [comment]
Maybe. Perhaps it is possible that there's a bug in how we persist the DSL in the database - we will find out.

**Comment by cppwfs** [comment]
Hitting the http://localhost:9393/tasks/definitions/{taskdefName} shows that the improper DSL is returned.

Moving this issue to SCDF issue:  https://github.com/spring-cloud/spring-cloud-dataflow/issues/2763
