### ISSUE TITLE
Add a link to launch grafana dashboard for each stream

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1027]
As a developer, I'd like to explore options to investigate whether if we can embed Grafana dashboard widgets in the Dashboard. 

Notes:
- This requires to be validated on top of spring-cloud/spring-cloud-dataflow#2753.
- For this to work, we may have to come up with the dynamic Grafana URL based on the selected stream for context. That'd mean, we would have to formulate the URL with stream-specific unique identifiers and query properties, so when Grafana loads, it will automatically also query and render the widgets automatically for the selected stream.
- We would also want to come up with the ideas to query the `/metrics` endpoint directly to continue to render the message rates in the UI natively (depends on spring-cloud/spring-cloud-dataflow#2737 and spring-cloud/spring-cloud-dataflow#2736).

Depends On https://github.com/spring-cloud/spring-cloud-dataflow/issues/2786

**Comment by oodamien** [comment]
Add the link `Grafana`
![image](https://user-images.githubusercontent.com/487067/51599408-c4dfb600-1eff-11e9-87a7-c37da83cd469.png)

**Comment by sabbyanandan** [comment]
@oodamien: I love the grafana-icon and the rendering! 😄
