### ISSUE TITLE
Protect deploy, launch, modify, destroy and schedule actions by the new security roles

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1028]
As a developer, I'd like to encapsulate the deploy/launch, destroy and schedule actions with the newly defined security role configurations in the backend.

Depends on spring-cloud/spring-cloud-dataflow#2582

Child of spring-cloud/spring-cloud-dataflow#2574

**Comment by oodamien** [comment]
ROLE_SCHEDULE: schedule module
ROLE_DEPLOY: task launch / stream deploy / stream update
ROLE_DESTROY: task destroy / stream destroy / app destroy

**Comment by sabbyanandan** [comment]
Also:

*ROLE_DESTROY*: app unregister
*ROLE_MODIFY*: app default
