### ISSUE TITLE
Actuator Endpoints

### ISSUE THREAD

**Issue by channing-jackson** [spring-cloud/spring-cloud-dataflow-ui#104]
Are the Spring Actuator endpoints exposed for the SCDF Dashboard UI?  If so, how can we configure the server application to enable them when we push the application? 

If not, are there Actuator endpoints for the server application itself, independent of the Dashboard UI?

**Comment by markfisher** [comment]
they are exposed under `/management`

**Comment by channing-jackson** [comment]
Thanks.
