### ISSUE TITLE
Streams search results are incomplete

### ISSUE THREAD

**Issue by oodamien** [spring-cloud/spring-cloud-dataflow-ui#1040]
The stream search is not returning the expected result.
Create a stream `foo` (file | log)

**Tests search:**
fo: no result
foo: 1 result
oo: no result

**The search should be return:**
fo: 1 result
foo: 1 result
oo: 1 result

**Note: Other tests**
fo%: 1 result
foo: 1 result
%oo: 1 result

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow#2793
