### ISSUE TITLE
Revise delete-all operation to rely on the new endpoint

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1049]
As a developer, I'd like to revise the delete-all operation from the Dashboard to use the endpoint defined via spring-cloud/spring-cloud-dataflow#2507, so both the Shell/GUI offers a consistent UX.

Notes:
- Use the new endpoint as opposed to deleting one app at a time, thus eliminating "n" backend calls. It should improve performance, and likewise, we won't run into DB connection limit issues.
- Rely on the REST response to highlight the outcome of the backend operation.
- Remove any client-side overhead.

**Comment by ilayaperumalg** [comment]
Closing this as `invalid` as we don't the right REST endpoint (to unregister a set of apps) at the server side yet.
