### ISSUE TITLE
Reword stream-create to stream-update for when updating an existing stream

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1050]
As a developer, I'd like to reword all the stream-create references to stream-update for when updating an existing stream.

Following items need correction:
- Rephrase `Deploy Stream` to `Update Stream` in the dropdown
- Rephrase `Deploy Stream` button to `Update Stream` in the stream-update page
- Reword the stream-update title to reflect the update operation
- Update any success/error messages if applicable
- Revise unit-test assertions if applicable

**Comment by oodamien** [comment]
Rephrase Deploy Stream to Update Stream in the dropdown:
https://github.com/spring-cloud/spring-cloud-dataflow-ui/pull/1051
