### ISSUE TITLE
App unregistration option should not be available on Stream info page

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow-ui#1069]
I see the `Remove` button after clicking the app information page under Stream info. This should not be visible as the app cannot be unregistered when in use.

**Comment by oodamien** [comment]
As far, we are not able to list the apps used by the streams/tasks.
It's not possible to add a condition on the unregister app action.

**Comment by sabbyanandan** [comment]
Also relates to https://github.com/spring-cloud/spring-cloud-dataflow/issues/4353.

**Comment by sabbyanandan** [comment]
Let's clean things up on the server side first, and revisit this later.
