### ISSUE TITLE
Streams with commas in definition not displaying on dashboard

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1071]
_From @djgeary on February 11, 2019 11:26_

This started happening after upgrading from 1.5.0 to 1.7.3.
The streams still work and deploy / undeploy from the shell. 

However if the definition contains a comma that is not already in quotes it will not display in the dashboard and hence cannot be managed or monitored there.

An example is
```
rabbit --queues=logs --outputType=text/plain | filter --expression=!#jsonPath(payload,'$.type').equals('test') | mongodb --mongodb.database=logs --collection=responses
```
If we make sure the part with the comma is within quotes eg
```
stream create --name newlogs --definition "rabbit --queues=logs --outputType=text/plain | filter --expression=!#jsonPath(payload,'$.type').equals('test') | mongodb --mongodb.database=logs --collection=responses"
```
it works OK.

This seems to be a dashboard bug - in the web console we get 
`
TokenizationError: Unexpected character
ERROR TypeError: "t.lines[0].nodes is undefined"
`
This means its possible to set up and deploy working streams from shell and not realise there is an issue until you go to the dashboard to monitor the metrics.

See discussion on gitter https://gitter.im/spring-cloud/spring-cloud-dataflow?at=5c59640b975714406b99c920

_Copied from original issue: spring-cloud/spring-cloud-dataflow#2875_

**Comment by sabbyanandan** [comment]
@djgeary: Thanks for reporting it. I will move it to the UI project since we will have to fix it at that level.

**Comment by aclement** [comment]
let me try and recreate.

**Comment by sabbyanandan** [comment]
I tried the following stream in 1.5.1, 1.7.4, and 2.0.0. It worked on all the versions via Shell. (I used the Einstein Apps against Kafka for testing)

```
dataflow:>app import --uri http://repo.spring.io/libs-milestone-local/org/springframework/cloud/stream/app/spring-cloud-stream-app-descriptor/Einstein.M1/spring-cloud-stream-app-descriptor-Einstein.M1.stream-apps-kafka-maven


dataflow:>stream create foo --definition "http --server.port=9001 | filter --expression=#jsonPath(payload,'$.text')=='test' | log" --deploy


dataflow:>http post --target http://localhost:9001 --data {"text":"test111"} --contentType application/json
> POST (application/json) http://localhost:9001 {"text":"test111"}
> 202 ACCEPTED

dataflow:>http post --target http://localhost:9001 --data {"text":"test"} --contentType application/json
> POST (application/json) http://localhost:9001 {"text":"test"}
> 202 ACCEPTED
```

The above also worked from the Dashboard on 1.5.1 and 2.0.0, but I see the tokenizer error on 1.7.3. However, after switching to the recent 1.7.4 release, I don't see the Dashboard error, though. 

This [commit](https://github.com/spring-cloud/spring-cloud-dataflow-ui/commit/5fcb743a61a11238cf96880cb9f0cbf6196586e1) didn't go in until v1.7.3 Dashboard release, and that is used in the recent v1.7.4 SCDF-server release. 

@djgeary: Could you upgrade and retry?

**Comment by sabbyanandan** [comment]
@djgeary: More details in the blog [here](https://spring.io/blog/2019/02/08/spring-cloud-data-flow-1-7-4-and-skipper-1-1-4-released).

**Comment by ilayaperumalg** [comment]
@djgeary Thanks for confirming.
