### ISSUE TITLE
Stream/Task Definitions with Plus Sign Not Created Correctly

### ISSUE THREAD

**Issue by mkandefer** [spring-cloud/spring-cloud-dataflow-ui#1074]
When creating a stream or task with a property that has a plus sign as a character in its value the plus sign is replaced with a space upon publishing the stream/task. I'm currently running SCDF 1.7.4 Local, and have observed this in 1.6.3 and 1.7.3. Manually editing the task/stream definition in the database fixes the issue.

**Comment by sabbyanandan** [comment]
Hi, @mkandefer. My apologies for the delay. It is not clear what properties cause this anomaly. Could you share your stream/task definitions? That would help to relate to the problem.

**Comment by sabbyanandan** [comment]
Relates to https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1152.

**Comment by ghillert** [comment]
We should revisit the issue once this open Angular PR from 2017 ever gets merged: https://github.com/angular/angular/pull/19710
