### ISSUE TITLE
Data flow ui does not hide password when configuring task from the ui.

### ISSUE THREAD

**Issue by jaimodha** [spring-cloud/spring-cloud-dataflow-ui#1080]
- When creating a task from the ui and passing the properties like --spring.data.mongodb.password=testpassword, does not hide the password once the task is created.
- But when you pass the same parameters in the stream definition when creating the stream it works fine e.g.  --spring.data.mongodb.password=testpassword='************'

**Comment by sabbyanandan** [comment]
Hi, @jaimodha. It'd be good to know the versions in use. Go to the "About" tab and get the JSON copied to the clipboard, which you can then share it here.

**Comment by jaimodha** [comment]
Hi here is the info on the version

`{
  "versionInfo": {
    "implementation": {
      "name": "spring-cloud-dataflow-server-local",
      "version": "1.7.0.RELEASE"
    },
    "core": {
      "name": "Spring Cloud Data Flow Core",
      "version": "1.7.0.RELEASE"
    },
    "dashboard": {
      "name": "Spring Cloud Dataflow UI",
      "version": "1.7.0.RELEASE"
    },
    "shell": {
      "name": "Spring Cloud Data Flow Shell",
      "version": "1.7.0.RELEASE",
      "url": "https://repo.spring.io/libs-release/org/springframework/cloud/spring-cloud-dataflow-shell/1.7.0.RELEASE/spring-cloud-dataflow-shell-1.7.0.RELEASE.jar"
    }
  },
  "featureInfo": {
    "analyticsEnabled": true,
    "streamsEnabled": true,
    "tasksEnabled": true,
    "skipperEnabled": false,
    "schedulerEnabled": false
  },
  "securityInfo": {
    "isAuthenticationEnabled": false,
    "isAuthorizationEnabled": false,
    "isFormLogin": false,
    "isAuthenticated": false,
    "username": null,
    "roles": []
  },
  "runtimeEnvironment": {
    "appDeployer": {
      "platformSpecificInfo": {},
      "deployerImplementationVersion": "1.3.9.RELEASE",
      "deployerName": "LocalAppDeployer",
      "deployerSpiVersion": "1.3.4.RELEASE",
      "javaVersion": "1.8.0_192",
      "platformApiVersion": "Linux 3.10.0-862.3.3.el7.x86_64",
      "platformClientVersion": "3.10.0-862.3.3.el7.x86_64",
      "platformHostVersion": "3.10.0-862.3.3.el7.x86_64",
      "platformType": "Local",
      "springBootVersion": "1.5.16.RELEASE",
      "springVersion": "4.3.19.RELEASE"
    },
    "taskLauncher": {
      "platformSpecificInfo": {},
      "deployerImplementationVersion": "1.3.9.RELEASE",
      "deployerName": "LocalTaskLauncher",
      "deployerSpiVersion": "1.3.4.RELEASE",
      "javaVersion": "1.8.0_192",
      "platformApiVersion": "Linux 3.10.0-862.3.3.el7.x86_64",
      "platformClientVersion": "3.10.0-862.3.3.el7.x86_64",
      "platformHostVersion": "3.10.0-862.3.3.el7.x86_64",
      "platformType": "Local",
      "springBootVersion": "1.5.16.RELEASE",
      "springVersion": "4.3.19.RELEASE"
    }
  }
}`

**Comment by sabbyanandan** [comment]
Thanks! We addressed in the v1.7.3 release [via: spring-cloud/spring-cloud-dataflow#2469], but I'd recommend upgrading to the latest [v1.7.4](http://docs.spring.io/spring-cloud-dataflow/docs/1.7.4.RELEASE/reference/htmlsingle/#getting-started). 

Once when you do, please report back with findings, I will close it then.

**Comment by jaimodha** [comment]
Thanks you so much for the prompt reply @sabbyanandan will check and report back quickly.

**Comment by jaimodha** [comment]
Sorry @sabbyanandan for the delay on the response. Waiting on the DevOps team to update the version.

**Comment by jaimodha** [comment]
Just validated @sabbyanandan the issue was fixed in v1.7.4 so closing this issue. Thanks you so much for the prompt reply.
