### ISSUE TITLE
`Confirm Destroy Task Definitions` Modal does not close

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#1097]
When deleting multiple task apps, the modal `Confirm Destroy Task Definitions` does not close.

![image](https://user-images.githubusercontent.com/685363/53561200-4bd11100-3af2-11e9-9caa-d521c98cafa8.png)

The tasks do seem to get deleted, though.

**Comment by oodamien** [comment]
Create the following task definition: `timestamp && timestamp-batch` (name `foo`)
Creation of 3 tasks definitions:
- foo: timestamp && timestamp-batch
- foo-timestamp: timestamp
- foo-timestamp-batch: timestamp-batch

Grouped delete will performed 3 HTTP call.
The first call, delete foo, returns an error (`ObjectOptimisticLockingFailureException`).

**Comment by cppwfs** [comment]
I had a chance to dig into this a bit.   
[Background] 
In a scenario where a user defines a composed task `foo` of `1: timestamp && 2: timestamp` dataflow creates not only the primary composed task definition `foo` but 2 child definitions, `foo-1` and `foo-2`.   When a user to deletes the composed task, SCDF deletes `foo-1`, `foo-2` and then `foo`.
[Issue]
When the SCDF-UI does a delete it issues deletes for all task definitions that were selected, this appears too be asynchronous.   So in my test case what was observed was that `foo-2`, `foo` and then `foo-1` were issued as deletes.   So when `foo` attempted to clean up its children, `foo-2` and `foo-1` were already destroyed and thus it threw an exception.  
[SCDF Behavior]
When working with composed tasks we do not prevent a user from deleting the child task, however, if a user does this it leaves the composed task in an inconsistent state.  We probably want to create a story to prevent this.  
[Solution]
We should not delete tasks asynchronously, but rather synchronously delete from top to bottom and get a successful acknowledgment back before doing he next delete.    Also, keep in mind that if you delete a Composed Task it will delete the children, so you will get a 404 if you attempt to delete a child task (that has been deleted by its parent). 
[Edge Case to solution] 
This does not prevent a cross boundary delete where the child tasks are only showing on the page and the parent is on a different page.   In that case we can try to prevent this on the SCDF app, but that would be out of scope for the 2.0.0.RELEASE IMHO.

**Comment by sabbyanandan** [comment]
There's an order to how things will have to be deleted; unless something changed in the UI recently. Did it?
