### ISSUE TITLE
Stream deploy: disabled submit

### ISSUE THREAD

**Issue by oodamien** [spring-cloud/spring-cloud-dataflow-ui#1108]
According to the guideline, the 'Deploy' action must not have a disabled state.
An error message must be displayed if there is an error while submitting the form.

![image](https://user-images.githubusercontent.com/487067/53816786-7f81c000-3f64-11e9-8781-e230ffbb8f20.png)

**Comment by ilayaperumalg** [comment]
LGTM, merging.
