### ISSUE TITLE
Stream creation fails when using property value with string concatenation

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow-ui#1152]
When creating the following stream:

http | transform --expression='Hello '+payload.toUpperCase()+'!' | log

the server fails the stream definition with the following error:

```
ataflow-server    | 2019-03-22 06:54:03.040  WARN 1 --- [nio-9393-exec-8] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request: 115E:(pos 58): unexpected data in stream definition '('
dataflow-server    | http | transform --expression='Hello ' payload.toUpperCase() '!' | log
dataflow-server    |                                                           ^
dataflow-server    |
```

As you can see from the above the DSL string doesn't have the String concatenation symbol `+` with it.
The same works from the SCDF shell.

**Comment by ghillert** [comment]
We should revisit the issue once this open Angular PR from 2017 ever gets merged: https://github.com/angular/angular/pull/19710
