### ISSUE TITLE
Stream deploy wrongly uses boolean from freetext

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow-ui#1167]
`hdfs` sink uses boolean options and all works ok until I go to `freetext` and come back to `builder` when form is rebuild from raw property strings.
If I i.e. have
```
app.hdfs.file-uuid=true
```
![hdfs-properties-1](https://user-images.githubusercontent.com/50398/55542054-28375280-56be-11e9-9844-b336eb1f0f47.png)

I think this is caused by populate methods in `StreamDeployBuilderComponent` which are taking both keys/values as strings and then passes boolean as string. `PropertiesDialogComponent` then don't understand this. I manually tested to set property value as real boolean if text value is `true` and then `PropertiesDialogComponent` correctly shows boolean values.

This should probably get fixed somewhere else than in `StreamDeployBuilderComponent`.

**Comment by jvalkeal** [comment]
Looks like this issue might originate from flo. Same problem in `stream create` if you paste `time | hdfs --file-uuid=true` to text field. It doesn't set `file-uuid` to true if you open `hdfs` properties dialog.

**Comment by jvalkeal** [comment]
I think issue is this fly class where `res` is a `true` as `string` when it is parsed from text so it blindly goes to default. Theoretically it could check `true` and `false` as strings and even `1` and `0` as ints and strings.
```
  export class CheckBoxControlModel extends GenericControlModel<boolean> {

    constructor(_property: Property, validation?: Validation) {
      super(_property, InputType.CHECKBOX, validation);
    }

    protected getValue() {
      const res = super.getValue();
      if (typeof res !== 'boolean') {
        return this.property.defaultValue;
      }
      return res;
    }

  }
```

**Comment by BoykoAlex** [comment]
@jvalkeal Sounds like it is **spring-flo** bug

**Comment by jvalkeal** [comment]
Fixed as snapshots are not used in master.
