### ISSUE TITLE
Add busy spinner when destroying task definitions

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#1186]
On Cloud Foundry, the (bulk-) destroying of task applications can take a long time as the applications will be removed from the Cloud Foundry system as well. Currently, we don't show any spinner and the screen may look frozen:

![image](https://user-images.githubusercontent.com/685363/57006374-f78eef80-6b7b-11e9-8548-c13acc088cbf.png)

**Comment by sabbyanandan** [comment]
We have redesigned the progress-bar. It now shows up visually on the top of the header, and is animated, too.
