### ISSUE TITLE
Upgrade to Angular 8 and the related dependencies

### ISSUE THREAD

**Issue by oodamien** [spring-cloud/spring-cloud-dataflow-ui#1196]
https://blog.ninja-squad.com/2019/05/29/what-is-new-angular-8.0/

**Comment by sabbyanandan** [comment]
Let's also specifically look at `webpack-bundle-analyzer` dependency.

**Comment by sabbyanandan** [comment]
Flo will have to updated to Angular 8, too.

**Comment by BoykoAlex** [comment]
@oodamien I have created Angular 8 compatible branch of Flo: https://github.com/spring-projects/spring-flo/tree/angular8. If you reference https://github.com/spring-projects/spring-flo#angular8 instead of Flo version 0.8.9 the AOT errors should be gone
