### ISSUE TITLE
UI - Supporting other languages 

### ISSUE THREAD

**Issue by afsanehabouei** [spring-cloud/spring-cloud-dataflow-ui#1203]
As a developer, I'm wondering if I could add resource bundles in my language. But surprisingly I found pure text strings in html files without any redirection to any translation service like ngx-translate.

**Comment by sabbyanandan** [comment]
Hi, @afsanehabouei. We have an open story (see: https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/701), so yeah, it is not supported yet.

If you have got the background as to what to do to add support for it, feel free to start a PR against #701, and we can collaborate.

I will close this as a duplicate.
