### ISSUE TITLE
Stream deploy from dashboard uses sanitized value(s)

### ISSUE THREAD

**Issue by goehringc** [spring-cloud/spring-cloud-dataflow-ui#1204]
When a stream is configured through the shell with values that should be sanitized, and deployed from the UI, the UI is POSTing what it retrieved from the sanitizer and not allowing values to be read from the db.

In order to reproduce:
1. `stream create --name test --definition "http --mapped-request-headers='*' | parser-endpoint: httpclient --http-method=POST --headers-expression={'Content-Type':'application/json'} --url='https://parser.my.url/' | log"`
2. Deploy the stream from the UI
3. The respective httpclient app gets configured with the literal sanitized url (e.g. httpclient.url:"`******`")

**Comment by sabbyanandan** [comment]
@oodamien: I paired with @goehringc yday, and I can quickly reproduce this as well. Let me know if you have any questions.

There seems to be a difference in how we deploy stream from Shell vs. UI. The Shell literally deploys what's available in the database. In the database, the sensitive parameters (in this case: `--url`) is stored correctly. However, in the UI, we are POSTing what's available in the client-side, which happens to include all the masked values (e.g. `httpclient.url:"******"`), and that is wrong. 

We should look into to see why we are not calling the same backend API that the Shell is invoking. Let's handle it consistently.
