### ISSUE TITLE
spring-cloud-dataflow-ui  mvn clean install issue

### ISSUE THREAD

**Issue by levystasman** [spring-cloud/spring-cloud-dataflow-ui#1210]
I would appreciate if someone can provide pointers on what's causing this failure. Tried in multiple Windows 10 (Professional) clean machines to build the UI. Running into same issue while building Spring-cloud-dataflow-ui

D:\GIT\spring-cloud-dataflow-ui>mvn clean install

[INFO] Scanning for projects...
[WARNING] The project org.springframework.cloud:spring-cloud-dataflow-ui:jar:2.1.1.BUILD-SNAPSHOT uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Cloud Data Flow User Interface 2.1.1.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ spring-cloud-dataflow-ui ---
[INFO] Deleting D:\GIT\spring-cloud-dataflow-ui\ui (includes = [package-lock.json], excludes = [])
[INFO] Deleting D:\GIT\spring-cloud-dataflow-ui\ui\node (includes = [], excludes = [])
[INFO]
[INFO] --- frontend-maven-plugin:1.6:install-node-and-npm (install node and npm) @ spring-cloud-dataflow-ui ---
[INFO] Installing node version v10.16.0
[INFO] Unpacking C:\Users\Cloud\.m2\repository\com\github\eirslett\node\10.16.0\node-10.16.0-win-x64.zip into D:\GIT\spring-cloud-dataflow-ui\ui\node\tmp
[INFO] Copying node binary from D:\GIT\spring-cloud-dataflow-ui\ui\node\tmp\node-v10.16.0-win-x64\node.exe to D:\GIT\spring-cloud-dataflow-ui\ui\node\node.exe
[INFO] Installed node locally.
[INFO]
[INFO] --- frontend-maven-plugin:1.6:npm (npm install) @ spring-cloud-dataflow-ui ---
[INFO] Running 'npm install --scripts-prepend-node-path=auto' in D:\GIT\spring-cloud-dataflow-ui\ui
[WARNING] npm WARN deprecated @types/jasmine-expect@3.8.1: This is a stub types definition for jasmine-expect (https://github.com/JamieMason/Jasmine-Matchers). jasmine-expect provides its own type definitions, so you don\'t need @types/jasmine-expect installed!
[WARNING] npm WARN deprecated core-js@2.6.1: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
[WARNING] npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[WARNING] npm WARN deprecated 8fold-marked@0.3.9: Marked is active again: https://github.com/markedjs/marked
[WARNING] npm WARN deprecated ts-simple-ast@0.86.0: NOTICE: ts-simple-ast has been renamed to ts-morph and version reset to 1.0.0. Switch at your leisure...
[WARNING] npm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
[WARNING] npm WARN deprecated samsam@1.1.2: This package has been deprecated in favour of @sinonjs/samsam
[WARNING] npm WARN deprecated opn@6.0.0: The package has been renamed to `open`
[WARNING] npm WARN deprecated samsam@1.1.3: This package has been deprecated in favour of @sinonjs/samsam
[WARNING] npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
[ERROR] npm ERR! prepareGitDep 1>
[ERROR] npm ERR! prepareGitDep > node-sass@4.9.0 install C:\Users\Cloud\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-7a4fd12a\node_modules\node-sass
[ERROR] npm ERR! prepareGitDep > node scripts/install.js
[ERROR] npm ERR! prepareGitDep
[ERROR] npm ERR! prepareGitDep Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.0/win32-x64-64_binding.node
[ERROR] npm ERR! prepareGitDep Download complete
[ERROR] npm ERR! prepareGitDep Binary saved to C:\Users\Cloud\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-7a4fd12a\node_modules\node-sass\vendor\win32-x64-64\binding.node
[ERROR] npm ERR! prepareGitDep Caching binary to C:\Users\Cloud\AppData\Roaming\npm-cache\node-sass\4.9.0\win32-x64-64_binding.node
[ERROR] npm ERR! prepareGitDep
[ERROR] npm ERR! prepareGitDep > node-sass@4.9.0 postinstall C:\Users\Cloud\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-7a4fd12a\node_modules\node-sass
[ERROR] npm ERR! prepareGitDep > node scripts/build.js
[ERROR] npm ERR! prepareGitDep
[ERROR] npm ERR! prepareGitDep Binary found at C:\Users\Cloud\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-7a4fd12a\node_modules\node-sass\vendor\win32-x64-64\binding.node
[ERROR] npm ERR! prepareGitDep Testing binary
[ERROR] npm ERR! prepareGitDep Binary is fine
[ERROR] npm ERR! prepareGitDep
[ERROR] npm ERR! prepareGitDep > spring-flo@0.8.9 prepare C:\Users\Cloud\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-7a4fd12a
[ERROR] npm ERR! prepareGitDep > npm run build
[ERROR] npm ERR! prepareGitDep
[ERROR] npm ERR! prepareGitDep
[ERROR] npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
[ERROR] npm ERR! prepareGitDep npm WARN deprecated core-js@2.6.5: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
[ERROR] npm ERR! prepareGitDep npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[ERROR] npm ERR! prepareGitDep npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
[ERROR] npm ERR! prepareGitDep npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
[ERROR] npm ERR! prepareGitDep npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[ERROR] npm ERR! prepareGitDep npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
[ERROR] npm ERR! prepareGitDep npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
[ERROR] npm ERR! prepareGitDep npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
[ERROR] npm ERR! prepareGitDep npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
[ERROR] npm ERR! prepareGitDep npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
[ERROR] npm ERR! prepareGitDep npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
[ERROR] npm ERR! prepareGitDep npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[ERROR] npm ERR! prepareGitDep npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
[ERROR] npm ERR! prepareGitDep 'npm' is not recognized as an internal or external command,
[ERROR] npm ERR! prepareGitDep operable program or batch file.
[ERROR] npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
[ERROR] npm ERR! prepareGitDep npm ERR! errno 1
[ERROR] npm ERR! prepareGitDep npm ERR! spring-flo@0.8.9 prepare: `npm run build`
[ERROR] npm ERR! prepareGitDep npm ERR! Exit status 1
[ERROR] npm ERR! prepareGitDep npm ERR!
[ERROR] npm ERR! prepareGitDep npm ERR! Failed at the spring-flo@0.8.9 prepare script.
[ERROR] npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR] npm ERR! prepareGitDep
[ERROR] npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR! prepareGitDep npm ERR!     C:\Users\Cloud\AppData\Roaming\npm-cache\_logs\2019-06-27T04_23_20_496Z-debug.log
[ERROR] npm ERR! prepareGitDep
[ERROR] npm ERR! premature close
[ERROR]
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     C:\Users\Cloud\AppData\Roaming\npm-cache\_logs\2019-06-27T04_23_20_619Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:26 min
[INFO] Finished at: 2019-06-26T21:23:32-07:00
[INFO] Final Memory: 33M/491M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:npm (npm install) on project spring-cloud-dataflow-ui: Failed to run task: 'npm install --scripts-prepend-node-path=auto' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by levystasman** [comment]
Same with D:\GIT\spring-cloud-dataflow-ui\ui>npm install

**Comment by sabbyanandan** [comment]
Hi, @levystasman. Apologies for the delayed response. It appears the node set up probably in your machine is not in a good state; once after updating node version locally on your machine, you could try running the equivalent of the following commands in Windows.

```
rm package-lock.json
rm -Rf node_modules/
npm install
```

If you continue to see issues on the latest build, please leave a comment here. I will close it for now.

**Comment by levystasman** [comment]
Thank you, Sabby. I will check it out.
