### ISSUE TITLE
Task Execution Page: Don't show link for deleted Task Definitions

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#1213]
Currently we show a link and clicking the link causes an error message to be shown.

![image](https://user-images.githubusercontent.com/685363/60350741-c703e000-9989-11e9-9482-800ee07bde18.png)

This might be an expensive operation to be implemented but we should not show the links for Task Definitions that have been deleted. Additionally we should add a visually clue/marker indicating that the Task Definition does not exist.

Depends on https://github.com/spring-cloud/spring-cloud-dataflow/issues/3299

**Comment by sabbyanandan** [comment]
This has been addressed.
