### ISSUE TITLE
UI/UX improvements in Flo + Dashboard integration

### ISSUE THREAD

**Issue by oodamien** [spring-cloud/spring-cloud-dataflow-ui#1214]
The primary goal of this is to inherit improvements from Flo itself. We are investigating options to give up on JointJS and instead implement our own graphing/connector widgets in Angular. 

By default, flo canvas should display 2 columns on the left panel.
Exemple:
![image](https://user-images.githubusercontent.com/487067/60351086-4e227980-99c5-11e9-91a6-852a46db3b83.png)

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/spring-cloud/spring-cloud-dataflow-ui/commit/dc3617a81a7684d8c0267d6b4780b83e9e558f5f.
