### ISSUE TITLE
Add a new action-menu item to stop Tasks from Task Executions

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1223]
As a developer, I'd like to add a new `Stop task` option in the Task action-menu item (see below), so the users can use it to stop an already running Task in the targeted platform.

![image](https://user-images.githubusercontent.com/1562654/60545084-0fdfcf80-9ccf-11e9-8851-1129329a97dd.png)

**Acceptance:**
- Integrate with the endpoint delivered via https://github.com/spring-cloud/spring-cloud-dataflow/issues/858
- Tests added

**Comment by oodamien** [comment]
@sabbyanandan Should we also allow user to stop multiple task? (bulk action)

**Comment by cppwfs** [comment]
@oodamien You and me are thinking too much alike.   This concerns me for you :-D    Yes, the Restful API will support a list of task-execution-ids.    
Also it will require a single parameter to identify the platform which the task-executions should be terminated.  i.e. `curl -X POST http://localhost:9393/tasks/executions/stop/107?platform=foobar`

**Comment by oodamien** [comment]
@sabbyanandan This action has to be add on the Task executions list page and task execution page.

**Comment by sabbyanandan** [comment]
@oodamien: Makes sense. For all of the workflows, though, we still need the UX around platform-list dropdown similar to what we have in Stream/Task deploy and launch pages respectively.

**Comment by sabbyanandan** [comment]
As an update, since the platform is already tagged with the task-execution, we do not need it to be provided as an option before deleting the executions. It can be implicitly derived, and no extra step from the UI.
