### ISSUE TITLE
Show logs of stream applications

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow-ui#1230]
Using the new REST endpoints for retrieving logs of stream applications, we can show the logs of the applications from the data flow UI `streams` page.

The REST endpoints are:

/streams/logs/{streamName}
/streams/logs/{streamName}/{AppDeploymentId}

**Comment by oodamien** [comment]
**First implementation**:
- **Stream** - Summary page: select a log (stream, specific app), show the log, refresh action
- **Task** - Summary page: show the log, refresh action

Note: no auto refresh
