### ISSUE TITLE
Show logs of task applications

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow-ui#1231]
Using the REST endpoints from data flow server: `/tasks/logs/{taskDeploymentId}` we can show the task execution log at the task execution page at the Data Flow UI

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/spring-cloud/spring-cloud-dataflow-ui/commit/56943908015376d8f167776d065001dbff8dbec1.
