### ISSUE TITLE
Inform user of long running download

### ISSUE THREAD

**Issue by mminella** [spring-cloud/spring-cloud-dataflow-ui#1232]
When a user schedules a task, it may be downloaded for the first time which may take time.  We log on the server this information, but we do not tell the user while they are looking at the UI.  This can lead to them feeling that something has gone wrong when things are actually working fine on the backend.

**Comment by sabbyanandan** [comment]
We won't have any response coming back from the server until when the request is complete, so showing any incremental progress update with a custom message is a bit complicated. 

However, after a few discussions, we ended up re-implementing the "progress bar" UX, and the latest experience can be found in the screenshot attached in https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1261.
