### ISSUE TITLE
Supplying Task arguments with new-lines breaks the property parsing

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1242]
As a user, when scheduling a Task with arguments that include line-breaks, I notice that the property parsing produces incorrect schedule behavior.

Supplying the multiple key-value pairs separated by commas like this works:

> localFilePath=/var/scdf/atrades-shared-files/ tempDir=/home/vcap/

However, passing them as separate lines fail:

> localFilePath=/var/scdf/atrades-shared-files/ 
> tempDir=/home/vcap/

**Comment by oodamien** [comment]
On task schedule create page:
Test 1: 
```
a=a b=b
```
will send `a=a b=b`

Test 2:
```
a=a
b=b
```
will send `a=a,b=b`

Test 3:
```
a=a,b=b
```
will send `a=a,b=b`

**Comment by sabbyanandan** [comment]
Why is `Test 2` sending them with a `,` - is that by design? That is not documented nor it is provided as a hint in the UI - users are assuming that to be sent with spaces with no delimiter.
