### ISSUE TITLE
Cannot delete task/app/... from the dashboard with ROLE_DESTROY - Missing button/links

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1249]
@Tetradeus commented on [Fri Jul 26 2019](https://github.com/spring-cloud/spring-cloud-dataflow/issues/3384)

**Description:**
Delete links/buttons are missing from the dashboard when security is enabled even with role ROLE_DESTROY. 

**Release versions:**
2.1.2

**Screenshots:**

<img width="283" alt="image" src="https://user-images.githubusercontent.com/1665874/61959095-edd22800-afc2-11e9-857b-18cf734efc6f.png">

---

@sabbyanandan commented on [Fri Jul 26 2019](https://github.com/spring-cloud/spring-cloud-dataflow/issues/3384#issuecomment-515478479)

This might be a UI bug, so I will move it there, and we can review it.

**Comment by sabbyanandan** [comment]
@Tetradeus: Based on our findings, with `ROLE_DESTROY` role correctly set, we are able to delete the task definition from the Dashboard - icons show up as expected. It checks out both in 2.1.x and 2.2.x release lines. 

Perhaps you can double-check whether if you're configuring the required role correctly. Maybe remove browser cache and retry to be sure also.

All that said, we did find another unrelated issue pertaining to a new feature that we are adding in 2.2: "task executions delete". That has been resolved with the attached PR.

**Comment by Tetradeus** [comment]
That is strange. Here is the list of roles my user have :
              new SimpleGrantedAuthority("ROLE_CREATE"),
              new SimpleGrantedAuthority("ROLE_DEPLOY"),
              new SimpleGrantedAuthority("ROLE_DESTROY"),
              new SimpleGrantedAuthority("ROLE_MANAGE"),
              new SimpleGrantedAuthority("ROLE_MODIFY"),
              new SimpleGrantedAuthority("ROLE_SCHEDULE"),
              new SimpleGrantedAuthority("ROLE_VIEW"));

All the other features like creating and running are available via the dashboard but not deleting.
I tried to clean and refresh but still the same on our dev and prod envs.

Here the ui artifact used:
org.springframework.cloud:spring-cloud-dataflow-ui:2.1.2.RELEASE

How did you test it ?

Can I debug it easily ?

Thanks.

**Comment by oodamien** [comment]
Hi @Tetradeus,

In the UI > About page > Open the Data Flow Server Implementation: you will have your roles listed.
Can you share this details?

Thanks,
Damien

**Comment by Tetradeus** [comment]
Thanks a lot @oodamien, my roles were not populated correctly! You can close this issue.
Very sorry for the time involved.

**Comment by sabbyanandan** [comment]
@Tetradeus: We are still fixing the bug that we identified on the new feature in 2.2.x - we will close the issue when the PR is merged later today.

It seems like you're creating a custom version of SCDF - why? What's types of customizations are in your custom build? I assume then you're hosting the custom server in an internal Docker registry to use it on K8s - yeah?

Any background here would help validate what we can do to improve the customization experience.

**Comment by Tetradeus** [comment]
@sabbyanandan yes I build a custom version for several reason that are required for our use cases :
- SQLServer
- Azure Ad oauth2 and custom role mapping
- Secret with environment variables
- Custom variables names for scdf datasource properties passing.
Indead this custom server use k8s and is stored in our private azure container registry.
