### ISSUE TITLE
Update tagline wherever applicable

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1254]
Currently, I see the following in the Dashboard's About page:

> Spring Cloud Data Flow is a toolkit for building data integration and real-time data processing pipelines.

Update it to:

> A microservices-based Streaming and Batch data processing in Cloud Foundry and Kubernetes.

Let's also double check to make sure the message is consistent across all the pages.

While we are at it change the `Sources` link-header-> `Source Code`.

**Comment by sabbyanandan** [comment]
While we are at it, let's change the following hint to the latest link served via Microsite.

![image](https://user-images.githubusercontent.com/1562654/62311996-e509a800-b441-11e9-91de-e833a918c544.png)


Example: https://dataflow.spring.io/kafka-maven-latest

**Comment by oodamien** [comment]
URI e.g. is address on PR1257
