### ISSUE TITLE
About Tab: Inconsistent platform information for Streams vs. Tasks

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1271]
As a user, while reviewing the platform profiles between Streams and Tasks, I see the inconsistency in what we are showing.

See: 

![image](https://user-images.githubusercontent.com/1562654/63119674-8f5ef080-bf55-11e9-9a64-94af3e092fe5.png)

Perhaps we should simply just show the `platform-name: <type>` for Tasks as well.

**Comment by oodamien** [comment]
Server side issue.

**Comment by sabbyanandan** [comment]
Issue moved to [spring-cloud/spring-cloud-dataflow #3454](https://github.com/spring-cloud/spring-cloud-dataflow/issues/3454) via [**ZenHub**](https://www.zenhub.com/)
