### ISSUE TITLE
Task arguments and parameters new line

### ISSUE THREAD

**Issue by Tetradeus** [spring-cloud/spring-cloud-dataflow-ui#1272]
Dataflow UI 2.2.1.RELEASE

/** Problem **/
It is not possible to write arguments and parameters on multiple lines.

<img width="884" alt="image" src="https://user-images.githubusercontent.com/1665874/63332001-171e7380-c337-11e9-89a5-397fc0f6a137.png">

/** Alternative **/
Separate each argument by a space

**Comment by oodamien** [comment]
@sabbyanandan Proposition:

**Arguments**
![image](https://user-images.githubusercontent.com/487067/63867052-80942700-c9b4-11e9-89b8-60758790e3f0.png)

**Properties:**
![image](https://user-images.githubusercontent.com/487067/63867101-9275ca00-c9b4-11e9-8a59-6d696d9cf1fc.png)

**Comment by Tetradeus** [comment]
Hello guys,

I understand that parameters must be separated with a ',' but it makes it hard to read when you have long/several parameters on the same line.
Presently, depending on the number of parameters, ui also add an empty line with line number  for each one.
Filling them on several lines seems better even if they are sent with a comma to the server.

@oodamien, parameters also supply deployer.* parameters, not just app.*

**Comment by oodamien** [comment]
@Tetradeus Thanks for the feedback.

On the UI side, one line for one parameter.
The UI build the request to the server and is in charge for the concatenation (with a space delimiter for args and a coma delimiter for the props)
