### ISSUE TITLE
Display all processor in graphical view

### ISSUE THREAD

**Issue by yogeshmprajapati** [spring-cloud/spring-cloud-dataflow-ui#1288]
I have created a sample with Source, Processor and Sink. The graphical view of the whole app is

![X2dUw](https://user-images.githubusercontent.com/14257174/64167533-2b01c380-ce67-11e9-8c31-f31db54bebda.png)

As I have an existing application which contains multiple Processor in a single project and enabled at once using code below

`@EnableBinding({Processor.class, Processor1.class, Processor2.class})`
Then, is there any possibility or configuration required so Data Flow can display all processor from the project?

It's really helpful if the Data Flow display processor with boundary and contains multiple processors in it (Shown in below image)

![E2kIu](https://user-images.githubusercontent.com/14257174/64167562-3c4ad000-ce67-11e9-95f5-77dca4a7d3f4.png)

**Comment by sabbyanandan** [comment]
Depends on the plugin change that would add the available channel/destinations to OOTB apps via: https://github.com/spring-cloud-stream-app-starters/app-starters-release/issues/232.

**Comment by sabbyanandan** [comment]
The scope of this spike is complete. The ongoing work will continue via spring-cloud/spring-cloud-dataflow-ui#1330.
