### ISSUE TITLE
Bulk import fails with large content

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow-ui#1308]
When importing apps from a local file, i.e pasting content of `https://dataflow.spring.io/rabbitmq-maven-latest` and using that cause too large header as those as passed via request params:
```
dataflow-server_1  | 2019-10-14 09:54:34.933  INFO 1 --- [nio-9393-exec-9] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
dataflow-server_1  |  Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
dataflow-server_1  | 
dataflow-server_1  | java.lang.IllegalArgumentException: Request header is too large
dataflow-server_1  | 	at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:721)
dataflow-server_1  | 	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:449)
dataflow-server_1  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:292)
dataflow-server_1  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
dataflow-server_1  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
dataflow-server_1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
dataflow-server_1  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
dataflow-server_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
dataflow-server_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
dataflow-server_1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
dataflow-server_1  | 	at java.lang.Thread.run(Thread.java:748)
```
Instead of blindly using request params, we could send those as a multipart request wrapping `apps` field as a form data. This allows us to use a larger content.

**Comment by sabbyanandan** [comment]
This is a limitation in the backend API. If the API supports the ability to pass the content as part of a POST parameter, we would not run into this limit. Even if it is supported as a parameter, there may still be a limitation for it, too. 

Also, this would be a limitation for every bulk operations that we support in the UI. We will have to review all the POST endpoints and come up with a consistent fix across the board.

**Comment by jvalkeal** [comment]
I'm not sure if it was implemented in a UI but workaround I mentioned works. This is one of those things we could implement better when we start to think about better `v2` api.
