### ISSUE TITLE
Add supporting for native multi-input/output destination mapping

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1330]
The goal of this epic is to explore, design, and implement the support for multiple input/output destination bindings from the visual canvas.

**Notes:**
- Flo will have to add native support for dynamic input/output bindings
- Design the rendering of multiple-input/output bindings
- Skin the multiple-input/output bindings for consistent UI/UX
- Take into account schema resolution capabilities in the future

**Comment by sabbyanandan** [comment]
Here's the outcome from the spike (#1288):

![image](https://user-images.githubusercontent.com/1562654/69084056-46a55080-09f8-11ea-8834-62010c742a14.png)

**Comment by lastakhov** [comment]
Hi. Why is this feature removed from milestone?

**Comment by sabbyanandan** [comment]
We are working on it incrementally. The scope is yet to be determined, too. Once we get a grip on things, we will revisit in what milestone this major enhancement will ship.
