### ISSUE TITLE
Out-of-the-box starters link should be provided by server

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow-ui#134]
We should have a config setting for the server to provide the URL for the out-of-the-box starters used in the "Bulk Import Applications" dialog. Since the server knows binder and repo type, there is no need to provide kafka/rabbit and maven/docker links, there should only be one link based on the servers capabilities.

**Comment by ericbottard** [comment]
I don't think the server knows the binder type (nor that it should know
it). A server could be used to deploy streams using several binding
technologies.
To a lesser extent, the same argument could even apply to the maven vs
docker choice.

**Comment by ghillert** [comment]
Duplicate of https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/146
