### ISSUE TITLE
Revisit the background color for the nodes

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1356]
The background gray isn't very appealing. On a large monitor, it looks almost transparent; it might be tricky to use for some users, so let's revise the coloring to make it more neutral for the broader userbase.

Example:
![image](https://user-images.githubusercontent.com/1562654/72003639-a94be900-31fe-11ea-94f4-d87ef7576fac.png)

**Comment by sabbyanandan** [comment]
One other thing. See:
![image](https://user-images.githubusercontent.com/1562654/72026413-2d6a9480-3230-11ea-8b2d-56203b0a1565.png)

I'd rather prefer to see the name given to the app more prominently positions as opposed to the `TIMESTAMP` everywhere in this graph.

**Comment by sabbyanandan** [comment]
While we are at it, let's review the following as well.

![image](https://user-images.githubusercontent.com/1562654/72352140-93bf3f00-3696-11ea-8f76-f46f008ffa93.png)

The icon on the left seems to hang randomly. It'd be nice to move it to the right side.

It looks somewhat better on the sink side:
![image](https://user-images.githubusercontent.com/1562654/72352194-a33e8800-3696-11ea-9b37-8d669c116e21.png)

The port and icon are somewhat close, so it makes it look nice .. maybe that’s why. If we do the same on the source, it might help.

For the processor, however, we may have to remove the funnel icon. We could come up with an icon that shows as if it is connected both on the left and right sides.

![image](https://user-images.githubusercontent.com/1562654/72352252-c5380a80-3696-11ea-9c5f-b8b73dde6bb8.png)

**Comment by sabbyanandan** [comment]
On the latest commit, I see that the app names are removed from the CT graph (which is good); however, the node shapes, and the text inside it are rendering tight. Could we consider either zooming-in a little by default or expand on the text/shape sizes?

See below:
![image](https://user-images.githubusercontent.com/1562654/72447812-d81c0f00-376a-11ea-968b-85482cbe8cc5.png)

**Comment by sabbyanandan** [comment]
It looks so much better now!
![image](https://user-images.githubusercontent.com/1562654/72469702-d404e700-3794-11ea-84b2-0444901deed5.png)

**Comment by sabbyanandan** [comment]
Oh, wait. One other thing. A looooong name on a node expands out of the defined node and its boundary, and that's ugly. Let's put ellipses or truncate the string?

![image](https://user-images.githubusercontent.com/1562654/72472709-f1887f80-3799-11ea-85d9-e8dba5168f64.png)

**Comment by BoykoAlex** [comment]
Should be fixed with 2e100d65d407e41f2fe933a54f1631374776e6bb

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/spring-cloud/spring-cloud-dataflow-ui/commit/2e100d65d407e41f2fe933a54f1631374776e6bb.
