### ISSUE TITLE
Introduce multi-in/out DSL support

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1360]
Given the `|` and `||` mean different things already (from the DSL perspective), we will have to study and decide the syntaxes to support multi-in/out.

**Comment by sabbyanandan** [comment]
Here's an attempt at a few use-cases.

**Use-case 1:**

The most basic 1-stream-listener requirement looks like this.

```
        @StreamListener(Processor.INPUT)
	@SendTo(Processor.OUTPUT)
	public Bar receive(Bar bar) {
		logger.info("******************\nAt the transformer\n******************");
		logger.info("Received value "+ bar.getValue() + " of type " + bar.getClass());
		logger.info("Transforming the value to " + TRANSFORMATION_VALUE + " and with the type " + bar.getClass());
		bar.setValue(TRANSFORMATION_VALUE);
		return bar;
	}
```

Here's the [sample](https://github.com/spring-cloud/spring-cloud-stream-samples/blob/master/processor-samples/streamlistener-basic/src/main/java/demo/SampleTransformer.java#L38) for reference.

**Use-case 2:**

It is common for a processor to have multiple inbound channels, and each of them is bound to a unique named destination.

```
         @StreamListener("input1")
	@SendTo("output1")
	public String transform1(String input) {
              .....
         }

        @StreamListener("input2")
	@SendTo("output2")
	public String transform2(String input) {
              .....
         }

        @StreamListener("input3")
	@SendTo("output3")
	public String transform3(String input) {
              .....
         }
```

This pattern is applicable to sink applications, as well.

**Use-case 2:**

The advanced Kafka Streams requirements.

```
        @StreamListener("usersbyregion_input")
	@SendTo("usersbyregion_output")
	public KStream<Object, UsersByRegionCount> aggregateHandler(KStream<Object, DomainEvent> input) {
           ......
        }
```

This could get even trickier with Kafka Streams, because of the input arguments having different types. Each of the input arguments can be mapped to a different named destination, too. The DSL and the UI representation for this are more trickier perhaps.

**Comment by sabbyanandan** [comment]
For the case-3 above, the complex branching sample would be useful to reason through; see: https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/kafka-streams-samples/kafka-streams-branching

**Comment by iliveforfun** [comment]
but  i dont see how to write multi-input/output dsl
