### ISSUE TITLE
Add an option to search for deployer/app properties

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1362]
As a user, while using the application or the deployer properties dialog window, I notice there are several 10s of properties, and it is hard to find the specific item by scrolling up and down. It'd be nice to search for a particular property with the help of a search bar on the top inside the dialog window.

**Acceptance:**
- Come up with a UX for searching for properties in the deployer or application properties window
- Searching for specific text will return context-specific results in the dialog window 
- Removing text from the search bar brings back all of the available properties for selection

**Comment by oodamien** [comment]
![crea](https://user-images.githubusercontent.com/487067/72380577-03c0da00-3716-11ea-8af1-16fc9f910777.png)

**Comment by sabbyanandan** [comment]
Looks great; let's go!
