### ISSUE TITLE
Show deployment properties from previous task execution in the Parameters field on task launch page

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow-ui#1387]
We have a scenario as described in issue https://github.com/spring-cloud/spring-cloud-dataflow/issues/3773 where users need to know what properties they will be using when they launch a task.  Hence we need to show them the deployment properties from the previous execution in the `Parameters` field on the task launch page.   The `deploymentProperties` can be obtained by calling the `tasks/executions/<task-execution-id>` using the `task-execution-id` field from the definitions request made when going to the task launch page.   
Make sure that if their is redacted data i.e. a value of `******` that we do not resend that data.

**Comment by oodamien** [comment]
To achieve this, we have to make 2 calls:
- Get the latest execution of a task
- Then get the details of the task execution

**Comment by sabbyanandan** [comment]
@cppwfs: Do you have any recommendations? Perhaps we could combine them in the same call instead?

**Comment by cppwfs** [comment]
@sabbyanandan We would want to create a new endpoint on SCDF vs updating the current one.   I'd say a 3 pointer.  Do you want me to add a story?

**Comment by sabbyanandan** [comment]
For now, we will make 2 calls to bring the relevant info on the task-launch details page. This is done on-demand, and only applicable for when a task is re-launched, so the performance may not be a paramount concern. Besides that, we don't support bulk launches (so no need to retrieve this info in bulk), and this doesn't apply at the time of scheduling, as well.

Long term, though, we can add a new API: https://github.com/spring-cloud/spring-cloud-dataflow/issues/3845.
