### ISSUE TITLE
Migrate to Angular2

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#139]
The current application infrastructure is ~~somewhat~~ outdated. This is not necessarily specific to the used Angular 1.x but also the surrounding tool-chain and problematic architectural decisions such as the usage of RequireJS

This is an umbrella task (epic), collecting some of the goals and intentions.

Upgrades:
- Grunt to NPM + Webpack
- JavaScript to TypeScript
- Eliminate RequireJS
- Angular 1.x to Angular2

As part of the refactoring, we should also rethink the model and state-management:
- We should ensure a proper domain model
  - Using TypeScript we can also use proper classes
  - With a domain model, we should also convert JSON to domain objects (don't hand returned JSON from REST-calls all the way to the UI)
- Ensure proper state-management in conjunction with the model
  - e.g. going to detail pages and then going back should result in the original state
  - when switching tabs, we may not want to reload the contents every single time 
- Remove the concept of polling the server
  - The server should detect changes and inform the client of potential state-changes (Push notifications / Webocket)

Depends on https://github.com/spring-projects/spring-flo/issues/7

**Comment by sabbyanandan** [comment]
This effort is already underway and the label "angular4-upgrade" can be used to track the theme progress.
