### ISSUE TITLE
Task logs are not shown when platformName is not 'default'

### ISSUE THREAD

**Issue by pavlafed** [spring-cloud/spring-cloud-dataflow-ui#1402]
Using cloud foundry as deployment platform and trying to open task execution details page, there is Logs section at the bottom.  The server side code accepts platformName parameter to help retrieve the logs when platformName is not default.

The UI does not pass the platformName leading to logs not being displayed.

example:  
this works: 
https://<host>/tasks/logs/1c78fc91-e2a5-4622-9134-cc08a2aad419?platformName=gap_na

this returns error: 
https://<host>/tasks/logs/1c78fc91-e2a5-4622-9134-cc08a2aad419
"Log could not be retrieved.  Verify that deployments are still available."

Relevant section of code:
task-execution.component.ts:
```
                if (val.taskExecutionStatus === 'COMPLETE' || val.taskExecutionStatus === 'ERROR') {
              return this.tasksService.getTaskExecutionLogs(val).pipe(
```

tasks.service.ts:
```
      /**
   * Get task execution logs
   * @param {TaskExecution} taskExecution
   * @returns {Observable<HttpResponse<any>>}
   */
  getTaskExecutionLogs(taskExecution: TaskExecution): Observable<any> {
    const httpHeaders = HttpUtils.getDefaultHttpHeaders();
    return this.httpClient
      .get<any>(`/tasks/logs/${taskExecution.externalExecutionId}`, { headers: httpHeaders })
      .pipe(
        catchError(this.errorHandler.handleError)
      );
  }
```

**Comment by sabbyanandan** [comment]
@pavlafed: Thanks for reporting this. I have tagged a few of us in the team to review whether this needs to be fixed in the backend vs. UI. Depending on the findings, we will then move it to the respective repo, and address it accordingly.

**Comment by sabbyanandan** [comment]
Also, @pavlafed, just so that we have a record of it, could you share the versions of SCDF and CF that you're using?

**Comment by pavlafed** [comment]
Thanks, please see below:

SCDF Version: 2.4.0.RELEASE

Deployed in internal private cloud version PCF 2.1.

Let me know if anything else is needed.

**Comment by ilayaperumalg** [comment]
@pavlafed The SCDF REST endpoint to display the log sets the platform name to `default` if the REST request is not set when retrieving the log. Hence, as you have suggested, the data flow UI is expected to set the `platform-name` as part of the task execution log retrieval request.

Thanks again for reporting this issue and your investigation as well.

**Comment by ilayaperumalg** [comment]
Confirming this as `bug` and resolution needs to be done at the UI itself.
