### ISSUE TITLE
Task execution count is wrong

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1406]
As a user, I'm registering a new application in the catalog, but the application count in the header is not reflecting the new addition. The pagination, however, appears to show the resulting count correctly.

**Comment by sabbyanandan** [comment]
At least in 2.4/2.5, we don't have any top-level header count, we only do at the pagination level. So, this might have been an oversight reported by the customer.

**Comment by wlund-pivotal** [comment]
<img width="1419" alt="scdf-count-tab" src="https://user-images.githubusercontent.com/5314240/80846240-7324e180-8bc0-11ea-94f7-32ff3c1ec16e.png">
The tab definitely has a count with the latest version.

**Comment by sabbyanandan** [comment]
@wlund-pivotal: That is execution count, and that has no relation to how many apps are registred in the app registry.

**Comment by wlund-pivotal** [comment]
The title is wrong.  It wasn't about registering apps.  it was about deploying apps and the pagination tab would show the correct number of executions but the executions tab was not in sync.

**Comment by sabbyanandan** [comment]
OK, that was not what was originally reported. We can certainly investigate this new thing.

**Comment by sabbyanandan** [comment]
Oh, I just realized we recently removed all the counts from tabs/sub-tabs (see: https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1348), so this doesn't apply anymore starting from v2.4.x and onwards. The pagination, however, continues to exist and the count will update automatically, as well.
