### ISSUE TITLE
UI: Allow user to select platform when Creating, deleting, and listing schedules

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow-ui#1415]
A user needs the ability to select the platform when creating, deleting, and listing schedules. 
Use schedulePlatform API call when retrieving scheduling platforms.   

This depends on  https://github.com/spring-cloud/spring-cloud-dataflow/issues/3944

**Comment by sabbyanandan** [comment]
Duplicates https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1433.
