### ISSUE TITLE
The Spring Cloud Dataflow UI is not refreshing the status correctly and deploy has issues

### ISSUE THREAD

**Issue by levystasman** [spring-cloud/spring-cloud-dataflow-ui#1416]
Name: spring-cloud-dataflow-server  Version: 2.5.0.BUILD-SNAPSHOT

Stream Deploy from the latest Spring Cloud Dataflow UI provides misleading status. In one page it shows deployed and in the other not deployed. 

The root cause of the problems seems to be the resource section. If i edit and remove the resource section directly in kubernetes deploy and update then the apps get deployed fine. 

Tried it in SCDF in two different environment Docker Desktop and GCP ran into same issue.
![image](https://user-images.githubusercontent.com/8647367/82073806-9bb3dd80-968e-11ea-8a95-8d957ba55857.png)

![image](https://user-images.githubusercontent.com/8647367/82073856-b71ee880-968e-11ea-9c27-31cdda35886e.png)

**Comment by levystasman** [comment]
Irrespective of any value given for CPU and Memory on deploy from Spring CloudDataflow UI,  in kubernetes corresponding deploy definition always shows 500m for CPU and memory 1Gi and fails with 

![image](https://user-images.githubusercontent.com/8647367/82739561-4d898480-9cf5-11ea-8d6d-40afa47da668.png)


Spring Cloud Dataflow UI
deployer.*.count=1
deployer.*.cpu=1
deployer.*.disk=1000
deployer.*.memory=1000
spring.cloud.dataflow.skipper.platformName=default

in .deploy kubernetes

resources:
    limits:
    cpu: 500m
    memory: 1Gi


![image](https://user-images.githubusercontent.com/8647367/82739612-9a6d5b00-9cf5-11ea-8dee-83c7cfe3f83d.png)

**Comment by levystasman** [comment]
Even on increasing the resource limit to 1CPU and 1GB memory directly in kubernetes the deploy fails. Only on delete of below resource section deploy is success. Tried creating multiple streams and deployed, in all cases same behavior.

resources:
limits:
cpu: 500m
memory: 1Gi

**Comment by levystasman** [comment]
Below is the root cause for this issue. Increasing the CPU size fixed the problem. Able to deploy without any issues. 

https://github.com/kubernetes/kubernetes/issues/33777

**Comment by levystasman** [comment]
But the inconsistent status shown by Spring Cloud Dataflow UI still to be considered.

**Comment by sabbyanandan** [comment]
@levystasman: Thanks for the details. We will have a look to check why the UI is showing with differences; it might as well be the API that is backing the UI page, too. 

@oodamien: Let's review it from the UI pov and move it to the backend if the API is returning that way always.

**Comment by oodamien** [comment]
@sabby Counters have been removed (performance issues).
See https://github.com/spring-cloud/spring-cloud-dataflow-ui/pull/1486
