### ISSUE TITLE
Redesign Flo tooltips using Clarity UI/UX 

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1424]

**Comment by BoykoAlex** [comment]
@oodamien looks like we are leaving the old tooltips in?
There are 2 libs: **ngx-bootstrap TooltipModule** and **tippy**. Shall we attempt to use one perhaps?
Shall i attempt to style the old tooltip similar to clarity's tooltip?

**Comment by oodamien** [comment]
@BoykoAlex Like you want. Tippy is a lightweight lib, used in the list pages.
It has been introduced following issue with ngx tooltip.
If we go for Tippy, there is no need to have ngx-bootstrap.
