### ISSUE TITLE
Edit undeployed stream feature

### ISSUE THREAD

**Issue by jvmlet** [spring-cloud/spring-cloud-dataflow-ui#143]
Hello
I can't find the "Edit stream definition" button, is this supported ?
It makes sense to edit the definiton when the stream is in undeployed state.
Thanks

**Comment by sabbyanandan** [comment]
This will be addressed via spring-cloud/spring-cloud-dataflow-ui#625.

**Comment by sabbyanandan** [comment]
This has been long addressed (see #625) - closing it.
