### ISSUE TITLE
Can not run tests

### ISSUE THREAD

**Issue by burakunlu26** [spring-cloud/spring-cloud-dataflow-ui#1496]
**Version**: 
3.0.0.BUILD-SNAPSHOT 

**Description**:
During the tests following error occurs.

**Reproduce**:

- clone the repository

- run `mvn clean install`

**Logs**:
`
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! spring-cloud-dataflow-ui@3.0.0 mavenbuild-tests: `**node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng test --code-coverage true --watch false --browsers ChromeCustom**`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR!
[ERROR] npm ERR! Failed at the spring-cloud-dataflow-ui@3.0.0 mavenbuild-tests script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR]
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /home/user/.npm/_logs/2020-07-20T07_45_34_284Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  08:07 min
[INFO] Finished at: 2020-07-20T07:45:34Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.6:npm (npm test) on project spring-cloud-dataflow-ui: Failed to run task: 'npm run mavenbuild-tests' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
`

**Environments**:
Ubuntu 18.04.1 LTS
8g ram

I also tried to apply the suggested solution [here.](https://github.com/nrwl/nx/issues/1110)

**Comment by oodamien** [comment]
Hi @burakunlu26,
Do you still have this error?

**Comment by oodamien** [comment]
No feedback -

**Comment by snimmagadda1** [comment]
I know this is closed but perhaps for future visitors - I was having issues running out of the box on my machine which produced the same log output as this issue when installing from maven.. When running npm it was a bit more clear that there was no response from the driver. It was due to the fact that the headless driver didn't exist on my machine after wiping chrome (memory hog 😄 ).
