### ISSUE TITLE
Can not build the project after "mvn clean" command

### ISSUE THREAD

**Issue by burakunlu26** [spring-cloud/spring-cloud-dataflow-ui#1497]
**Version**:
3.0.0.BUILD-SNAPSHOT

**Description**:
`mvn clean` command deletes files inside the _/spring-cloud-dataflow-ui/ui/protractor-docker-plugin_ folder, after building the project for the first time by running `mvn clean install` command. This causes errors during next build.

**Reproduce**:

- clone the repository

- run `mvn clean install`

- run `mvn clean`

- run `mvn clean install`

**Logs**:
`[ERROR] npm ERR! code ENOLOCAL
[ERROR] npm ERR! Could not install from "protractor-docker-plugin" as it does not contain a package.json file.
[ERROR]
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     C:\Users\burak\AppData\Roaming\npm-cache\_logs\2020-07-21T12_26_53_796Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  30.192 s
[INFO] Finished at: 2020-07-21T14:26:53+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.6:npm (npm install) on project spring-cloud-dataflow-ui: Failed to run task: 'npm install --scripts-prepend-node-path=auto' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException`

**Environments**:
Windows 10
16 GB ram

Note: We haven't faced the issue with Ubuntu.

**Comment by klopfdreh** [comment]
Hey 😃,

I just tested it with:

* macOS 12.1 / AArch64
* ZuluJDK 17.30.15 (17.0.1)
* Current main-branch (node v14.17.4)

the same order as mentioned in the issue, but without any problems.

**Comment by oodamien** [comment]
Not able to reproduce
