### ISSUE TITLE
Redo task-launch screen to follow similar UX as streams

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1515]

**Comment by jvalkeal** [comment]
![image](https://user-images.githubusercontent.com/50398/100466580-0677b400-30c9-11eb-99ba-1d48ac92c93b.png)

**Comment by jvalkeal** [comment]
Note that in case of a simple non ctr task, ui would be simpler:

![image](https://user-images.githubusercontent.com/50398/100467613-ac77ee00-30ca-11eb-87dc-2f54b7887423.png)
