### ISSUE TITLE
Clarity Integration: SCDF UI testing

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow-ui#1524]
- [x] App Registration @markpollack 
          - Bulk Import
          - Single App Registration
          - Register from file
          - Register multiple versions
          - Default version selection

- [x] Streams Page  @ilayaperumalg 
        - Stream Creation 
        - Stream Deployment (Override Application, Deployment properties, Change app version etc.,)
        - Stream Update
        - Stream Summary

- [ ] Task Page @cppwfs 
        - Task Creation/Launch
       - Task Execution
       - Task Scheduling

- [x] Batch Page @chrisjs 
       - Batch Execution (Step Execution)

- [ ] Audit Records

- [ ] About Page @tzolov

**Comment by cppwfs** [comment]
If a task fails to start because of an error on the SCDF Server on the Task Launcher page, the page shows the following error:
```
An error occurred TypeError: r is not iterable
```

**Comment by ilayaperumalg** [comment]
> If a task fails to start because of an error on the SCDF Server on the Task Launcher page, the page shows the following error:
> 
> ```
> An error occurred TypeError: r is not iterable
> ```

@cppwfs Could you create a new issue for this please?

**Comment by cppwfs** [comment]
I found the UI issue while fixing:
https://github.com/spring-cloud/spring-cloud-dataflow/pull/4105 
And reviewing 
https://github.com/spring-cloud/spring-cloud-dataflow/issues/4021 

:-)

**Comment by cppwfs** [comment]
Done: https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1526

**Comment by chrisjs** [comment]
batch page issues opened: 

https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1527 
https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1528

otherwise seems good AFAICT

**Comment by cppwfs** [comment]
Task Create and Launch:

https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1529
https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1530
https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1531

**Comment by ilayaperumalg** [comment]
Created the following on Streams testing:

https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1535
https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1536

**Comment by markpollack** [comment]
Created the following on Application Registration testing:

**Comment by sabbyanandan** [comment]
Looks like 99% of the reported issues are already resolved/fixed. @oodamien: Do you want to continue to keep this issue open or it can be closed?
