### ISSUE TITLE
"INFORMATIONS" on job execution page

### ISSUE THREAD

**Issue by chrisjs** [spring-cloud/spring-cloud-dataflow-ui#1528]
on a job-executions page, ie /dashboard/#/tasks-jobs/job-executions/1 it says `INFORMATIONS` -- seems like this should be `INFORMATION`

**Comment by oodamien** [comment]
Should we use `Information` everywhere instead of `informations`?

**Comment by chrisjs** [comment]
yes i believe it should be `information` rather than `informations` everywhere

**Comment by sabbyanandan** [comment]
👍
