### ISSUE TITLE
App Name is duplicated on Task Detail Page

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow-ui#1529]
![image.png](https://images.zenhubusercontent.com/5c93c5e09543816d30f633f7/dc38a44b-34c3-41fc-a74d-dcde2e0733f3)

**Comment by oodamien** [comment]
Not able to reproduce

![image](https://user-images.githubusercontent.com/487067/90375281-094c1d00-e075-11ea-87be-e011b3d95309.png)

What is the DSL used in your sample?

**Comment by cppwfs** [comment]
Understood.   Closing as invalid.
