### ISSUE TITLE
Issue creating new stream definition

### ISSUE THREAD

**Issue by kedarr** [spring-cloud/spring-cloud-dataflow-ui#154]
I am trying to create new stream definition using the Spring Cloud Dataflow UI but the "Create" button is disabled. Also I don't see option for providing a name to my stream definition. 

I have written custom implementation of StreamDefinitionRepository. 

Versions : 

spring-cloud-dependencies : Camden.SR4
spring-cloud-dataflow-dependencies : 1.1.2.RELEASE

<img width="1157" alt="screen shot 2017-01-30 at 1 08 01 am" src="https://cloud.githubusercontent.com/assets/7211560/22418135/9e512f14-e6fd-11e6-91d3-b12cfce44156.png">

**Comment by BoykoAlex** [comment]
Are you able to create this stream via CLI? Any chance you can share your SCDF repo with us to try your stream definition creation scenario? I assume that a stream creation built from out-of-the-box apps (i.e. 'time | log') works, right?

**Comment by kedarr** [comment]
I have't tried creating the stream via CLI. Will do it and share the result. I want to use Redis to store the stream data definition and for that I implemented "StreamDefinitionRepository". My implementation is pretty much similar to [https://github.com/spring-cloud/spring-cloud-dataflow/blob/v1.0.0.RELEASE/spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/repository/RedisStreamDefinitionRepository.java](RedisStreamDefinitionRepository)

**Comment by BoykoAlex** [comment]
One more thing: any errors in the browser console?

**Comment by kedarr** [comment]
I see this error Uncaught  

Error: [$injector:unpr] Unknown provider: ParserServiceProvider <- ParserService
http://errors.angularjs.org/1.3.5/$injector/unpr?p0=ParserServiceProvider%20%3C-%20ParserService
    at angular.js:63
    at angular.js:3950
    at Object.getService [as get] (angular.js:4097)
    at angular.js:3955
    at getService (angular.js:4097)
    at Object.invoke (angular.js:4129)
    at controllers.js:42
    at Object.execCb (require.js:1658)
    at Module.check (require.js:874)
    at Module.<anonymous> (require.js:1121)

**Comment by BoykoAlex** [comment]
OK, this is the cause of the UI for entering stream name missing and create button disabled. What is the version on the about page?

**Comment by BoykoAlex** [comment]
What are `Source`, `P` and `Sink` apps? How did you create them? Anyway I can import exactly the same apps? (Can't reproduce it with out-of-the-box apps)

**Comment by kedarr** [comment]
It does work with out-of-the-box app.

**Comment by kedarr** [comment]
The issues was in my custom implementation of StreamDefinitionRepository. The logic was always sending a non null value when it tries to find a stream based on name. The UI is rightly disabling the "Create" button but I feel the text box for entering name should still be visible.
