### ISSUE TITLE
Hide irrelevant fields from the scheduled task execution

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1546]
As a user, I've scheduled task launches set up on Cloud Foundry. The task logs and the runtime level properties, such as app/platform properties, are handled directly by the scheduling system as opposed to SCDF. 

Showing "empty" logs or the "empty" app/platform properties in the task execution pages is confusing, and it can be hidden/removed for the scheduled launches.

More details: https://pivotal-io.atlassian.net/secure/RapidBoard.jspa?rapidView=37&projectKey=SCDF&selectedIssue=SCDF-9

**Comment by sabbyanandan** [comment]
The 3 fields that don't apply for scheduled logs:

![image](https://user-images.githubusercontent.com/1562654/95097785-bab91780-06e2-11eb-9503-b21f8e0dbe6a.png)

**Comment by sabbyanandan** [comment]
@cppwfs: Could you help @oodamien with the identifier that he can use to determine whether the Task is a scheduled launch versus manual.

**Comment by cppwfs** [comment]
If you have an external-execution-id you will show the `View Log` button.   Else hide it.

**Comment by cppwfs** [comment]
@sabbyanandan, @oodamien and I had a discussion on this a few days ago.   He agreed with the opinion above.  I think he's still working on it.
