### ISSUE TITLE
Notification for AppAlreadyRegisteredException

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1550]
@MariusKl commented on [Fri Sep 11 2020](https://github.com/spring-cloud/spring-cloud-dataflow/issues/4139)

**Problem description:**
Register an application via browser. Afterwards register another application with the same name.
An exception is thrown
`09:30:07.373 ERROR [https-jsse-nio-9393-exec-20] [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.cloud.dataflow.server.controller.AppAlreadyRegisteredException: The 'task:yyy' application is already registered as maven://xxx] with root cause
org.springframework.cloud.dataflow.server.controller.AppAlreadyRegisteredException: The 'task:yyy' application is already registered as maven://xxx
`

**Solution description:**
An additional notification/popup in the browser would be nice.

**Additional context:**
Not sure if this is a bug or a feature request. Tested with latest version of Brave and Firefox and spring-cloud-dataflow version 2.6.1

---

@sabbyanandan commented on [Sun Sep 13 2020](https://github.com/spring-cloud/spring-cloud-dataflow/issues/4139#issuecomment-691755280)

Thanks for the report, @MariusKl. It'd be nice to gracefully handle it and show a user-friendly message in the Dashboard. I will move it to the UI repo.

**Comment by oodamien** [comment]
Fixed -
Current error message on the APP registration:
![image](https://user-images.githubusercontent.com/487067/93070003-a0a98d80-f67e-11ea-8f49-6f35401fda64.png)

@sabbyanandan Is it enough? Or should we have a more friendly error message?

**Comment by sabbyanandan** [comment]
@oodamien: This error message is fine, but the URI can be removed. It makes it look odd.

How about?

> The 'processor:aggregator' application is already in the application registry.

**Comment by oodamien** [comment]
@sabbyanandan This message is returned bu the server side.

**Comment by sabbyanandan** [comment]
@oodamien: Right, I get that, we can always handle it gracefully on the front-end, though. The front-end message can be more user-friendly.

**Comment by sabbyanandan** [comment]
This is addressed in 2.7 M2.
