### ISSUE TITLE
Task Logs not displayed in multi-platform setup

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow-ui#1551]
If user has multiple platforms and requests a log from a task that was not run on the default platform the log is not returned.

To support the UI the platformName will be added to the result of the task execution (instead of the UI having to dig through the properties or command line arg).   Refer to issue: https://github.com/spring-cloud/spring-cloud-dataflow/issues/4145

A platformName can be specified as follows when obtaining the log:
`http://<my dataflow>/tasks/logs/bd0915b-rgpqr124l2?platformName=<myplatform>`

**Comment by cppwfs** [comment]
Updating the repo resolved this issue.

**Comment by imitbn** [comment]
Spring Cloud Data Flow 2.9.6 has this issue. "platformName" is missing in the request.
