### ISSUE TITLE
Add error message on stream/task name validation

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow-ui#1552]
Based on https://github.com/spring-cloud/spring-cloud-dataflow/pull/4141, we have validation on stream/task name. The SCDF UI needs to provide appropriate error message based on the validation result.

Currently, it says: "Failed to create stream"

Also, we need to remove the default stream name `STREAM_1` from the UI as underscore is not a valid character for a stream name.

**Comment by BoykoAlex** [comment]
Anything you'd recommend to use instead of `_`? Perhaps a `-`?

**Comment by ilayaperumalg** [comment]
@BoykoAlex Let's go with '-' for now. Thanks for checking!
