### ISSUE TITLE
Improve UX for long stream/task names

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1557]
Background: https://github.com/spring-projects/spring-flo/issues/80

![image](https://user-images.githubusercontent.com/487067/91634552-7fe00780-e9f1-11ea-9679-b2de5ef761c9.png)

**Comment by BoykoAlex** [comment]
@oodamien can you reproduce this with the UI from master? I could only see the stream label not being truncated all the others seem to be truncated as expected...

**Comment by sabbyanandan** [comment]
Update: The label with massive length is correctly truncated; however, the stream with massive length is still problematic.

Let's also review the same on the Tasks, and fix it there, too.

**Comment by BoykoAlex** [comment]
Tasks seemed fine to me in terms of label truncation. There are control nodes that display label outside the shape but those label are always fixed expected strings. Therefore, I think it is only stream name label that requires adjustment.
