### ISSUE TITLE
UX feedback on Clarity-based SCDF UI

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1558]
As I was continuing to exercise the Clarity-based UI on 2.7.x, I have had some suggestions where the UX can be improved.

1) The developer journey in SCDF begins with applications. The app registration tab is at the bottom of the left-nav. It needs to be moved up and front-facing as the first thing.

2) I'd suggest making the non-dark as the default UX theme (users can change it to others they prefer)

3) I don't fully understand the reasoning behind `Dev Mode`. All that includes is the shortcut to create pages and then info of what we used to show in the `About` tab. What are we trying to provide as a value-add from this new tab? The moment I read "Dev Mode", it makes me want to think about debugging and enable extra logging traces etc., but none of it exists anyway.

4) In "Dev Mode", there's a section with "Stores". We show the API results of what we used to show in `About` tab. Maybe come up with a different heading to describe it?

5) I can get to `About` info from a few places, but I don't see an option to copy to clipboard all the results into a JSON-friendly format. We need to continue to support it because the community/customers are used to submitting the results when reporting problems. Removing this would be a breaking change, as well. We also list in the new bug-report [GH template](https://github.com/spring-cloud/spring-cloud-dataflow/issues/new?template=bug_report.md).

6) Audit tab appears to renamed to "Records", why? We don't want to change the naming convention unless there's a benefit from it; I don't seem to see any, however.

7) On the list pages, from UX pov, I see me wanting to "create" or "add" something as the first thing. However, every list page starts with "Group Actions". The buttons the top look denser, as well, so it seems a bit awkward to click the middle button to begin my journey. Maybe it is just me.

8) Replace "We couldn't find any streams!", "We couldn't find any tasks!", etc. with something like: "No results found."

9) By default, each stream definition expands to a predefined width; it seems big, though. Should we shorten it? (The graph itself seems to stick to the top anyway; lots of whitespace in the bottom) (cc: @BoykoAlex)
![image](https://user-images.githubusercontent.com/1562654/93618257-de165f80-f98b-11ea-9858-7108cfc3b40c.png)

10) Replace all the "VISUALIZE" heading in the detail pages to "Show Data Pipeline".

11) The drag option from the task nodes are so tricky to use; most of the time, I am dragging the entire start node as opposed to just pulling an arrow from it. (cc: @BoykoAlex @aclement) 
![image](https://user-images.githubusercontent.com/1562654/93618432-1d44b080-f98c-11ea-915f-4287334f1914.png)

12) I created the following graph, but then I was given an option to delete a task definition from the list page individually. Would the following graph be bogus then? (cc: @BoykoAlex @aclement @cppwfs) 
![image](https://user-images.githubusercontent.com/1562654/93618762-93491780-f98c-11ea-8e13-813a02311170.png)

13) Curious why we seem to show the label and app name side by side; they are both the same unless tagged with a custom label. Seems redundant most of the time. Similar UX in streams, as well.
![image](https://user-images.githubusercontent.com/1562654/93618974-dc00d080-f98c-11ea-953f-5962c41e24d5.png)

14) I attempted to deploy a stream with Wavefront using: `docker-compose -f ./docker-compose.yml -f ./docker-compose-wavefront.yml down` on `2.7.0-SNAPSHOT`; it appears the WF toggle is not turned-ON automatically, so none of the WF buttons or the integration is showing up on the UI. Perhaps this was added only on 2.6.x branch and not in `master`? I looked at this [commit](https://github.com/spring-cloud/spring-cloud-dataflow-ui/commit/135ed19c0d9c5bd1a683558d46f9030c9f6098b8). (cc: @tzolov)

![image](https://user-images.githubusercontent.com/1562654/93620883-942f7880-f98f-11ea-9112-9988f51d8b1a.png)

**Comment by BoykoAlex** [comment]
11. - Yes, I wasn't happy about it either... think i had better zoning for dragging vs creating link at some point.

**Comment by oodamien** [comment]
1. Done
2. By default, browser theme detection
3. Remove Dev Mode
4. Remove Dev Mode
5. Done
6. Done
7. Done
8. Done
9. /
10. Done

**Comment by sabbyanandan** [comment]
@BoykoAlex @cppwfs @tzolov: I'd appreciate it if you could review the remaining items and share your recommendations on whether to address/ignore them.

**Comment by BoykoAlex** [comment]
@sabbyanandan 

11. I looked at it briefly. The idea is have different cursor for dragging vs starting a link. Thus depending where os the START/END user hovers the cursor would change appropriately. Also I'm thinking of making zones for creating link and dragging the shape a bit better. For example link creation area would be a circle at the bottom of the START node and top of the END node. I haven't started this work but it won't take long i think.

12. Not sure about the validity of the CT graph. I think if of the tasks used in CT graph nodes was deleted then at least you should a red error marker on the shape stating that task is unresolved. I'd have to play with it a bit and hope i understand the problem correctly. If the deleted task still shows on the palette than this might be the reason for red marker not shown on the shape. I think if the page is reloaded then the task might be gone from the palette and error marker would show up on the shape.

**Comment by sabbyanandan** [comment]
The only items that remain on this list are 11 and 14.
