### ISSUE TITLE
Add ability for users to filter Job Executions by a Job Instance ID

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow-ui#1567]
Epic spring-cloud/spring-cloud-dataflow#3866 shows how a user would like filter job executions via the UI. The user would like to filter job executions by a JobInstanceId . This is associated with issue spring-cloud/spring-cloud-dataflow#4166

**Comment by sabbyanandan** [comment]
Duplicates https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/920.
