### ISSUE TITLE
DSL text after deploy

### ISSUE THREAD

**Issue by oodamien** [spring-cloud/spring-cloud-dataflow-ui#1583]
![image](https://user-images.githubusercontent.com/487067/96698248-2eb71900-138d-11eb-8952-a530998f4d82.png)

Create a stream: `foobar=f3: file | filter | f4:file`
Deploy the stream

The stream definition is now: `f3: file application' | filter application' | f4: file application' `

**Comment by ilayaperumalg** [comment]
This is fixed via https://github.com/spring-cloud/spring-cloud-dataflow/commit/3b126a71c0e042db7918716f17de1d52cb677ff5

**Comment by ilayaperumalg** [comment]
Please re-open the issue if you still see the issue.
