### ISSUE TITLE
Grafana console does not display in Firefox

### ISSUE THREAD

**Issue by dturanski** [spring-cloud/spring-cloud-dataflow-ui#1597]
From the Streams page, with Grafana/Prometheus configured. Press Grafana button.  Blank page

![image (2)](https://user-images.githubusercontent.com/886859/99096117-ea8df180-25a3-11eb-8d1e-f181b3a95ba7.png)

Same install works as expected in Chrome

**Comment by oodamien** [comment]
+ @tzolov

**Comment by sabbyanandan** [comment]
Issue moved to [spring-cloud/spring-cloud-dataflow #4253](https://github.com/spring-cloud/spring-cloud-dataflow/issues/4253) via [**ZenHub**](https://www.zenhub.com/)
