### ISSUE TITLE
As a user I would like to be redirect to the task execution when triggering a task

### ISSUE THREAD

**Issue by MariusKl** [spring-cloud/spring-cloud-dataflow-ui#1599]
Hi,

after triggering a task via the ui at tasks/definitions/my-task/summary, right now there is a redirect to the task overview at dashboard/#/tasks/definitions. 

I assume that for most usecases it would be great to be redirected to the execution of the started task dashboard/#/tasks/executions/1234

Could you improve the ui in such a way? Will save three clicks each time ;) Might even make sense to do so after triggering a task from the task overview at dashboard/#/tasks/definitions.

**Comment by oodamien** [comment]
We need to adapt first the server side to get the execution ID when launching a task:
- redirect to the task execution (not a job)
- redirect to the job execution (job)

**Comment by cppwfs** [comment]
But what if I'm launching multiple tasks, now I have to go back to the Definitions page to launch the apps.   The definitions page currently has a status field that states that the task is "UNKNOWN", "RUNNING", "ERROR", or "COMPLETE", so they can see the status of the launch from the definitions page.

**Comment by jvalkeal** [comment]
It's true that depending what you're doing you might to land on different page. Maybe allow user to make a choice?

**Comment by oodamien** [comment]
Right.
If you are launching multiple tasks (bulk action), the launch should redirect to the list page.
If you are launching one task, the launch should redirect to the task execution page or the job execution page.

**Comment by jvalkeal** [comment]
Bulk action? We don't have that for launch. Or did you mean like intend to launch more tasks after each others.

**Comment by oodamien** [comment]
Oh sorry yes.

> launching multiple tasks

I guess we are talking about tasks in task - In that case, redirect to the parent task execution / job execution
