### ISSUE TITLE
The shell download link should use the core version, not the server version

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow-ui#160]
The link for downloading the shell seems to follow the server version which could be different than the core version, especially for k8s, mesos and yarn servers. We should use the core version for the link since that is where the shell is built anyway.

**Comment by ericbottard** [comment]
Similarly, links to the ref docs on the about page should use the core version, not the version of the server product itself

**Comment by ghillert** [comment]
@sabbyanandan @trisberg Strange, looks like one of my comments from yesterday got lost in outerspace. Anyway, using the actuators we only provide the following version meta-data on the server side:

```
management:
  contextPath: /management
  security:
    enabled: false
info:
  app:
    name: "@project.artifactId@"
    description: "@project.name@"
    version: "@project.version@"
```

Providing the core-version is a bit tricky. It looks like we don't have common strategy, so it can be pulled uniformly. E.g. in the implementations we do specify the core version of SCDF, e.g. Kubernetes:

```
<properties>
		<spring-cloud-dataflow.version>1.2.0.M2</spring-cloud-dataflow.version>
...
</properties>
```

But for the local servers we don't.
