### ISSUE TITLE
Using ctrl+space conflicts with DSL<->Search controls

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1613]
As a user, I am attempting to use the code-assist with ctrl+space on the DSL section, but the UI search is getting activated instead.

To reproduce, type `|` and hit ctrl+space to see it in action. I'd expect DSL options to in the code-assist dropdown, but it is not.

![image](https://user-images.githubusercontent.com/1562654/101844386-21065000-3b01-11eb-8451-9c8567f8fd1b.png)

**Comment by jvalkeal** [comment]
Shall we replace it with `ctrl+f` as what it probably should have been(it's a common shortcut for find) in a first place?

**Comment by oodamien** [comment]
@jvalkeal `ctrl+f` is already used by browser.

**Comment by jvalkeal** [comment]
Ah right, dump me, it's a catch are release problem. Can we then even have reliable shortcuts.

**Comment by oodamien** [comment]
Not really, I suggest we remove this shortcut.
