### ISSUE TITLE
when can scdf suppport multi-input/output?

### ISSUE THREAD

**Issue by iliveforfun** [spring-cloud/spring-cloud-dataflow-ui#1614]
well, we need to combine multiple input to our Source, but scdf doesnt support to make it in dashboard. is there any way to solve it?

**Comment by sabbyanandan** [comment]
Hi, @iliveforfun. The [commercial version of SCDF](https://docs.pivotal.io/scdf-k8s/1-2/pro-features/index.html) includes support for multi IO and more. Feel free to try it out. 

For questions, please use StackOverflow going forward.
