### ISSUE TITLE
Jobs executions spins infinitely on NoSuchTaskBatchException

### ISSUE THREAD

**Issue by snimmagadda1** [spring-cloud/spring-cloud-dataflow-ui#1620]
Did some searching and didn't see reference to this so apologies if this is duplicate or expected behavior.. 

I've run into this on a couple different dataflow servers in which an app or task gets imported and run, then the job executions tab becomes unusable with the following 404 for `jobs/thinexecutions?page=0&size=20`

```
{
  "_embedded": {
    "errors": [
      {
        "message": "No corresponding taskExecutionId for jobExecutionId 1.  This indicates that Spring Batch application has been executed that is not a Spring Cloud Task.",
        "logref": "NoSuchTaskBatchException",
        "_links": {
          "self": {
            "href": "/"
          }
        }
      }
    ]
  }
}
```

The only resolution I've found is to manually go into the DB and delete or clear the job history in order for that screen to become usable again (perhaps this is also doable via the shell also). Is there a provided way to correct this on the UI? Maybe the messaging around it could be clearer on the UI.

<img width="1127" alt="Screen Shot 2020-12-18 at 11 02 53 PM" src="https://user-images.githubusercontent.com/19558427/102681325-97085800-418e-11eb-9fc1-d176e8675c21.png">

**Comment by jvalkeal** [comment]
Maybe we can do a bit more on a server side but UI side bug I'd say is the spinner and missing error handling.

**Comment by cppwfs** [comment]
This needs to be backported to 3.0.x line.

**Comment by cppwfs** [comment]
Backported.
