### ISSUE TITLE
I can see password thought UI, is it ok?

### ISSUE THREAD

**Issue by ebezdomnikov** [spring-cloud/spring-cloud-dataflow-ui#1621]
Hello everyone,
I'm playing around with v2.7 of SCDF server using k8s and I've noticed what the db password showed as is through UI.
Is it ok? 
![2B99081F-5C9A-41A0-A51E-49DE3EFD8D14](https://user-images.githubusercontent.com/18294474/102909038-645da880-4489-11eb-8b4f-f2678bcd74d9.jpg)
Thank you.

**Comment by sabbyanandan** [comment]
Thanks, @ebezdomnikov. We have attempted to mask credentials from clear-text in Shell/UI/API before; we will review to see how it is reintroduced again.

**Comment by sabbyanandan** [comment]
@cppwfs @oodamien: We may have to review the backend/API call. We can move the issue accordingly.

**Comment by ebezdomnikov** [comment]
@sabbyanandan hi,
just a side node, i've took a look on the backend, and most probably this file hasn't mask functionality: 
[https://github.com/spring-cloud/spring-cloud-dataflow/blob/9344e72a3acc093bd2bbb62a339af7c11a89a25b/spring-cloud-dataflow-server-
core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskDefinitionController.java#L233](url)
I hope it helps.
Thank you.

**Comment by sabbyanandan** [comment]
Thanks for digging! It could be that, yeah. We have [ArgumentSanitizer.java](https://github.com/spring-cloud/spring-cloud-dataflow/blob/f62b067c21039f984985ae1bd18a6809f2415c04/spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/util/ArgumentSanitizer.java) that gets used by the REST controllers to sanitize/mask sensitive credentials. 

It is used in the [TaskExecutionController.java](https://github.com/spring-cloud/spring-cloud-dataflow/blob/63324f1815b5dc62d073716a73d8a353a680be29/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskExecutionController.java), but not in `TaskDefinitionController.java`.

If you want to take a stab at following what we do on the execution and repeat it on the definition controller, feel free to submit a PR. We can collaborate.

**Comment by ebezdomnikov** [comment]
I've create an issue here as is not a UI related: https://github.com/spring-cloud/spring-cloud-dataflow/issues/4297
