### ISSUE TITLE
Hover-over / tooltip text overflows on the stream-list page

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1624]
![image](https://user-images.githubusercontent.com/1562654/103713806-0d200380-4f72-11eb-9728-80dcd8aefe8d.png)

Depending on whether it is Flo or core UI, we may have to move the issue.

**Comment by BoykoAlex** [comment]
This is the right spot for the issue. This the result of **tippy** adoption for tooltips. The text is truncated by ellipsis as expected i think... it is the tooltip div size being off... Maybe a popover is a better option than a tooltip... Tooltip is not a good choice for unbound amount of data...

**Comment by BoykoAlex** [comment]
Fixed the width of the tooltip. Popover should be treated as a new feature... tooltip cannot fit a large table anyway. If are to display something meaningful in this case we'd need a popover feature. For example user hovers on the shape and information bulb pops up at the top right corner. Clicking on it brings up a popover with the table inside. (popover: https://angular-ui.github.io/bootstrap/#!#popover, although Clarity UI doesn't have Popover thus it's a bit unclear what to have there)

**Comment by BoykoAlex** [comment]
@sabbyanandan I noticed the label **for/backport** Which branch do we want to backport it to?
