### ISSUE TITLE
Empty schedule-list fails to load

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1627]
When there's no schedule available, the schedules page fails to load. SCDF 2.7 on K8s.

![image](https://user-images.githubusercontent.com/1562654/103824120-28e5e100-5028-11eb-8317-7b79ba585ca3.png)

**Comment by cppwfs** [comment]
I was unable to reproduce this with 2.8 and 2.7 on minikube using our kubectl setup instructions.   Can you provide a bit more detail on your environment.   Thanks!

**Comment by sabbyanandan** [comment]
Perhaps try the PRO server just to be sure.

**Comment by cppwfs** [comment]
This is a UI issue.   I've tested the back-end on Pro and looks fine.   I can show Damien what I'm seeing.

**Comment by cppwfs** [comment]
@oodamien resolved this issue via the following commit.   https://github.com/pivotal/scdf-pro-ui/commit/073f88726edc967e8e85eb792fab12967a66ed4a
