### ISSUE TITLE
Change the color of 'Destroy' buttons/labels with red border

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1632]
It has been reported by users that they wrongly click to "Destroy" the stream as opposed to "Deploying". From UX pov, should we rearrange the buttons? Perhaps also make the border of the "Destroy" button highlighted in red. We already are highlighting the `Cancel` button in red. 

Whatever we decide, we will have to consistently apply the change to all "Destroy" buttons in the UI.

See -> https://vmware.slack.com/archives/C1RU2QDJL/p1610437807328600

**Comment by jvalkeal** [comment]
We should not to tricks like red border on green as you know some people have color blindness. But then starting from `3.x` we don't have buttons anymore as those are in a dropdown.

![image](https://user-images.githubusercontent.com/50398/104435173-fb4aeb80-5583-11eb-9e29-b14b600e4aca.png)

And even that will ask to confirm stream destroy.

**Comment by sabbyanandan** [comment]
@jvalkeal: we already show red border for `Cancel` button. Also, there are buttons in the top-section still, apart from the dropdown choice.
