### ISSUE TITLE
Fail to import task application starters

### ISSUE THREAD

**Issue by dturanski** [spring-cloud/spring-cloud-dataflow-ui#1637]
The first couple of times, I checked `import task application starters` after importing stream apps successfully. I got a javascript error. Something like `cannot iterate over r` . I just tried to get a screen shot and it worked. 

<img width="591" alt="image" src="https://user-images.githubusercontent.com/886859/104643504-86a6a880-567a-11eb-8aca-7d57f12d30fd.png">

**Comment by jvalkeal** [comment]
With some other issues when importing we tried to re-prod this but didn't see these particular errors on a console.

**Comment by sabbyanandan** [comment]
@dturanski: Could you retest, please?
