### ISSUE TITLE
Composed Task Graph is not rendered properly when using $END

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow-ui#1653]
The following statement ` timestamp '*'->t1: timestamp 'FOO'->$END` the graph is rendered as 
![image.png](https://images.zenhubusercontent.com/5c93c5e09543816d30f633f7/d4bc921f-742b-416b-898e-5b2dc3f87667)

It should look something like:
![image.png](https://images.zenhubusercontent.com/5c93c5e09543816d30f633f7/7dd2ecb9-08b0-476d-829e-9d6a356e88f0)
also notice that timestamp is also flagged invalid.   But the syntax is parseable by CTR

**Comment by cppwfs** [comment]
Refer to issue for additional detail: https://github.com/spring-cloud/spring-cloud-dataflow/issues/4373

**Comment by BoykoAlex** [comment]
The problem is on the server side
POST to `/tools/parseTaskTextToGraph` with body:
```
{
  dsl: "timestamp '*'->t1: timestamp 'FOO'->$END"
  name: "unknown"
}
```

The response is: 
```
{
   "graph":{
      "nodes":[
         {
            "id":"0",
            "name":"START"
         },
         {
            "id":"1",
            "name":"timestamp"
         },
         {
            "id":"2",
            "name":"timestamp",
            "metadata":{
               "label":"t1"
            }
         },
         {
            "id":"3",
            "name":"$END"
         },
         {
            "id":"4",
            "name":"END"
         }
      ],
      "links":[
         {
            "from":"0",
            "to":"1"
         },
         {
            "from":"1",
            "to":"2",
            "properties":{
               "transitionName":"*"
            }
         },
         {
            "from":"1",
            "to":"3",
            "properties":{
               "transitionName":"FOO"
            }
         },
         {
            "from":"1",
            "to":"4"
         },
         {
            "from":"2",
            "to":"4"
         }
      ]
   },
   "dsl":null,
   "errors":[
      
   ]
}
```

**Comment by cppwfs** [comment]
This is a fairly old issue.  Tracked it back to 2.0.     Opened parser issue here: https://github.com/spring-cloud/spring-cloud-dataflow/issues/4399
