### ISSUE TITLE
Stream retrieval hangs with "Please Wait"

### ISSUE THREAD

**Issue by hvandenb** [spring-cloud/spring-cloud-dataflow-ui#167]
We've seen this now in a number of times where the UI hangs for no apparent reason. This is running on PCF 1.9, SCDF 1.0.1.RELEASE (055d973). There are no errors raised in the JavaScript console or the application log.

![2017-03-02_07-57-50](https://cloud.githubusercontent.com/assets/401017/23512518/14d80620-ff1e-11e6-9dfd-5cbf59bc93c7.png)

**Comment by BoykoAlex** [comment]
Once in a while i have the same with dev version of UI ran via `grunt serve`. Browser console shows that HTTP request fetching stream definition is pending. Possibly a server issue...

**Comment by sabbyanandan** [comment]
Hi, @hvandenb. Thank you for reporting this. There could be a variety of reasons for this hang-up; however, we addressed this in the recent release that includes significant improvements - please review the [1.1.1.RELEASE blog](https://spring.io/blog/2017/02/22/spring-cloud-data-flow-for-cloud-foundry-1-1-1-maintenance-release-available) for more details. Specifically, there have been a lot of improvements to "stream list" operation. Try the latest version and let us know if you still see any issues with it.

**Comment by sabbyanandan** [comment]
This has been resolved in 1.1.1 and we are at 1.2.1 right now. Please reopen the issue if the issue still persists.
