### ISSUE TITLE
Platform name not displayed with Task Schedules

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow-ui#1670]
Schedule entries don't display the platform name(they report only N/A) on schedules page.
The also don't show up with the schedules on the Task Definition Detail page.

Refer to issue: https://github.com/spring-cloud/spring-cloud-dataflow/issues/4369

**Comment by storm1kk** [comment]
Any possibility that fix can (When?) be ported to 2.7.x?
