### ISSUE TITLE
Task Schedule Detail can only viewed for one of the platforms

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow-ui#1671]
**[To Reproduce]**
Create 2 schedules 1 for default (sched-a) and 1 for practice (sched-b).
On either the task schedule page or the task definition details page select sched-b and the detail page will appear, but get an error when trying to get to sched-a.   The error reported in the browser console is: 
![image](https://user-images.githubusercontent.com/695673/109076175-2b7bc300-76c8-11eb-8188-b33868ca48d3.png)

**[Cause]**
The UI does not pass the platform that is associated with schedule when requesting the detail i.e. it requests `http://192.168.99.103:30152/tasks/schedules/task-sched-a`.   It should request `http://192.168.99.103:30152/tasks/schedules/myschedc?platform=default`

To answer the question, why does it work in one case and not the other.   This is because the server will use the last platform in the list to search for a schedule detail if the platform is not specified.    

Task Detail also does not show platform.
Refer to issue: spring-cloud/spring-cloud-dataflow#4369

**Comment by storm1kk** [comment]
Do you have any plans to apply the fix to 2.7.* versions?
