### ISSUE TITLE
Test the new Task UI/UX with existing 2.7.x DB footprint

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1676]
The goal here is to make sure that any existing DB footprint (previously used database) continues to work just fine when upgrading to 3.1.x UI.

**Comment by cppwfs** [comment]
Issues Identfied:
- [ ] #1668 - dataflow-server-use-user-access-token is not available as an option on the builder tab
- [ ] https://github.com/spring-cloud/spring-cloud-dataflow/issues/4405 - When launching a composed task where the CTR is a docker image, CTR's properties don't show up.
- [ ]

**Comment by jvalkeal** [comment]
Could you copy/paste old manifests here as I think we need to test from those manually.

**Comment by cppwfs** [comment]
From an empty database, execute the following from SCDF -Shell
```
#Maven
# Import Streams
app import --uri https://dataflow.spring.io/rabbitmq-maven-latest
# Import Tasks
app import --uri https://dataflow.spring.io/task-maven-latest
#Maven
# Import Streams
app import --uri https://dataflow.spring.io/rabbitmq-maven-latest
# Import Tasks
app import --uri https://dataflow.spring.io/task-maven-latest
```
The previous instruction produce:

{"taskDeploymentRequest":{"definition":{"name":"ts0301a","properties":{"management.metrics.tags.service":"task-application","timestamp.format":"YYYYDD","spring.datasource.username":"root","spring.datasource.url":"jdbc:mariadb://localhost:3306/task","spring.datasource.driverClassName":"org.mariadb.jdbc.Driver","management.metrics.tags.application":"${task.name:unknown}-${task.execution.id:unknown}","spring.cloud.task.name":"ts0301a","spring.datasource.password":"password"}},"resource":"maven://org.springframework.cloud.task.app:timestamp-task:jar:2.1.1.RELEASE","deploymentProperties":{"app.timestamp.format":"YYYYDD"},"commandlineArguments":["--spring.cloud.task.executionid=1"]},"platformName":"default"}
--
{"taskDeploymentRequest":{"definition":{"name":"ctr0301a","properties":{"management.metrics.tags.service":"task-application","spring.datasource.username":"root","spring.datasource.url":"jdbc:mariadb://localhost:3306/task","spring.datasource.driverClassName":"org.mariadb.jdbc.Driver","management.metrics.tags.application":"${task.name:unknown}-${task.execution.id:unknown}","platform-name":"default","spring.cloud.task.name":"ctr0301a","composed-task-properties":"app.ctr0301a-1.app.timestamp.timestamp.format=YYYYDD","graph":"ctr0301a-1   &&   ctr0301a-2","spring.datasource.password":"password"}},"resource":"maven://org.springframework.cloud:spring-cloud-dataflow-composed-task-runner:jar:2.7.1","deploymentProperties":{"app.composed-task-runner.composed-task-properties":"app.ctr0301a-1.app.timestamp.timestamp.format=YYYYDD"},"commandlineArguments":["--spring.cloud.task.executionid=2","--spring.cloud.data.flow.taskappname=composed-task-runner"]},"platformName":"default"}
{"taskDeploymentRequest":{"definition":{"name":"ctr0301a-1","properties":{"timestamp.format":"YYYYDD","management.metrics.tags.service":"task-application","spring.datasource.username":"root","spring.datasource.url":"jdbc:mariadb://localhost:3306/task","spring.datasource.driverClassName":"org.mariadb.jdbc.Driver","management.metrics.tags.application":"${task.name:unknown}-${task.execution.id:unknown}","spring.cloud.task.name":"ctr0301a-1","spring.datasource.password":"password"}},"resource":"maven://org.springframework.cloud.task.app:timestamp-task:jar:2.1.1.RELEASE","deploymentProperties":{"app.timestamp.timestamp.format":"YYYYDD"},"commandlineArguments":["--spring.cloud.task.parent-execution-id=2","--spring.cloud.task.executionid=3"]},"platformName":"default"}
{"taskDeploymentRequest":{"definition":{"name":"ctr0301a-2","properties":{"management.metrics.tags.service":"task-application","spring.datasource.username":"root","spring.datasource.url":"jdbc:mariadb://localhost:3306/task","spring.datasource.driverClassName":"org.mariadb.jdbc.Driver","management.metrics.tags.application":"${task.name:unknown}-${task.execution.id:unknown}","spring.cloud.task.name":"ctr0301a-2","spring.datasource.password":"password"}},"resource":"maven://org.springframework.cloud.task.app:timestamp-task:jar:2.1.1.RELEASE","deploymentProperties":{},"commandlineArguments":["--spring.cloud.task.parent-execution-id=2","--spring.cloud.task.executionid=4"]},"platformName":"default"}

**Comment by sabbyanandan** [comment]
@cppwfs: it seems we are all good, are we OK with closing it?
