### ISSUE TITLE
Add visual distinction between regular and composed tasks/jobs

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#171]
As a user, I'd like to easily differentiate between regular and composed task based task/job in the task/job details page respectively.

**Acceptance:**
In the details page, visual (:heavy_multiplication_x: vs. :heavy_check_mark:) indicator represents regular vs. composed task/job respectively.

**Comment by ilayaperumalg** [comment]
The current HTML changes to show up `Composed Task` are placeholder implementations to support the feature once the corresponding data flow core support is added. 

Given this, I see that the `TaskExecutionDetail` doesn't have any information about composed task yet. Hence, this issue needs to be addressed only after SCDF core is supported to show up `Task/Job execution detail` information.

**Comment by sabbyanandan** [comment]
We show a check-box in the Task details page for composed-tasks.
