### ISSUE TITLE
Add "cleanup-all" operation under the Manage section

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1710]
Add a new page task cleanup-all page under the Manage section of the UI.
![image](https://user-images.githubusercontent.com/1562654/118513699-d1980180-b6e8-11eb-92a2-f37600d74363.png)

Requires UI/UX exploration.

Think about the warning message, as well.

Tests included.

**Comment by ilayaperumalg** [comment]
Here are the REST endpoints to handle clean-all on task executions:

Cleanup all the task executions and delete the associated records:

```
DELETE /tasks/executions?action=CLEANUP,REMOVE_DATA
```

Cleanup all the task executions and delete the associated records of a given task definition:

```
DELETE /tasks/executions?action=CLEANUP,REMOVE_DATA&name={task-definition-name}
```

Cleanup all the task executions that are **completed** and delete the associated records:

```
DELETE /tasks/executions?action=CLEANUP,REMOVE_DATA&completed=true
```

Cleanup all the **completed** task executions of a given task definition and delete the associated records:

```
DELETE /tasks/executions?action=CLEANUP,REMOVE_DATA&completed=true&name={task-definition-name}
```
