### ISSUE TITLE
Handle old ctr props

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow-ui#1715]
With new task launch ui we moved to not require task name in props anymore so that those are portable between tasks.
```
app.t1.timestamp.format=yyyy
```
On a server we still handle old style:
```
app.ctr1.t1.timestamp.format=yyyy
```
Need to think how we represent this in UI.

**Comment by sabbyanandan** [comment]
@oodamien: Feel free to share your thoughts on the UX. We need to be able to evaluate if it is possible to wrap it in RC, though.
