### ISSUE TITLE
Unclear what Dashboard refers to in the About section

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1724]
See: 
![image](https://user-images.githubusercontent.com/1562654/119704483-90040680-be0c-11eb-8cc2-65b51d11a9ef.png)

If it refers to monitoring, please be descriptive and say just that.

If it refers to something else, let's discuss how to present the detail in the about section. "Dashboard" terminology inside a dashboard is confusing, that's why.

**Comment by tzolov** [comment]
This stands for **Monitoring** Dashboard, such as Grafana or Wavefont.
