### ISSUE TITLE
Cleanup choices under the "Tools" section is confusing to use

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1727]
I see these 2 under the "Tools" section:

![image](https://user-images.githubusercontent.com/1562654/119712341-57b4f600-be15-11eb-90ba-e2c55286146f.png)

Issues:
1- Both the links appear to show the same results for cleanup.
2- I'd expect the "completed" link would only show the successfully ran task executions (and, not include the error'd bits, but it does).
3- Change the title of the section to " CLEAN UP TASK EXECUTIONS".

**Comment by ilayaperumalg** [comment]
If missing the name, the URL for the completed task executions has http://localhost:9393/tasks/info/executions?completed=true%27 instead of `http://localhost:9393/tasks/info/executions?completed=true

**Comment by ilayaperumalg** [comment]
https://github.com/spring-cloud/spring-cloud-dataflow-ui/commit/b5e257bdfa67207bb05ebf4c4a35469050979a6e#diff-30ede4b91e58705[…]e58e2901fc2f7918R128
