### ISSUE TITLE
Job execution detail fails with task-execution being not found

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1729]
I have 2 Job executions in `FAILED` state:
![image](https://user-images.githubusercontent.com/1562654/119730265-622dba80-be2a-11eb-8280-cc81fe772187.png)

The corresponding Task executions for these 2 Jobs are:
![image](https://user-images.githubusercontent.com/1562654/119730479-9bfec100-be2a-11eb-9389-1ef80657b681.png)

**Problem:**
Clicking to view the Job execution with ID "13" fails with `Could not find TaskExecution with id 13`:
![image](https://user-images.githubusercontent.com/1562654/119730367-7c679880-be2a-11eb-9f6c-146269039cba.png)

Either the Job execution ID that we list is wrong, or the redirect mapping is confused with some other ID reference.

**Comment by sabbyanandan** [comment]
@mminella: Maybe you will have an opinion on what columns we currently show, and what they should actually be.

**Comment by jvalkeal** [comment]
Not an issue on oss side, see linked issue above.
