### ISSUE TITLE
Race condition when creating/deploying stream?

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-dataflow-ui#174]
While creating a stream and also checking the `deploy` checkbox, I got the following exception on the serverside (the progress bar in the modal dialog then did not move). The stream was actually created and deployed.

```
2017-03-17 13:51:26.011  WARN 37160 --- [nio-9393-exec-9] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request: Could not find stream definition named googo
```

Could it be a race condition ?

**Comment by sabbyanandan** [comment]
We haven't observed this behavior in a long time. Given this is an aging issue with no other reports associated with it, I'm closing it.
