### ISSUE TITLE
Create task from DSL Error

### ISSUE THREAD

**Issue by dturanski** [spring-cloud/spring-cloud-dataflow-ui#1752]
v 2.9.0-SNAPSHOT

Steps to reproduce:
Register timestamp task multiple times as task1 thru task6

Paste `task1  && <task2 || task4 || task3> && <task5 || task6>`

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/886859/126993011-b34bc1d2-fac4-4955-90bf-6a49793bcb1f.png">

**Comment by dturanski** [comment]
Delete `task1`, drag and reconnect fixes it

**Comment by dturanski** [comment]
Simpler example:

<img width="739" alt="image" src="https://user-images.githubusercontent.com/886859/128719323-efacef1c-7e13-41c9-9dd4-e9698906dbf4.png">

**Comment by dturanski** [comment]
Looks like it only has an issue with `task1`, e.g., i can do `task2 && task3`

**Comment by oodamien** [comment]
@BoykoAlex Is it an issue with Flo?

**Comment by BoykoAlex** [comment]
I'll have a look... probably not Flo itself but rather something on SCDF UI side integrating Flo.

**Comment by BoykoAlex** [comment]
@oodamien @dturanski is this some specific instance of SCDF you're trying this use case on? I've just pulled the latest from repo for Skipper, SCDF and SCDF UI, built everything and ran SCDF server locally and UI in dev mode on port 4200. Registered task1... task6 - worked fine. Is this Pro or OSS version?

**Comment by dturanski** [comment]
What it states in the description OSS 2.9.0-SNAPSHOT

**Comment by BoykoAlex** [comment]
I cannot reproduce this... Are you still able with the latest? Every time tasks are registered like above you get an issue with `task1` only? Any differences between `task1` registration and the rest of the tasks? I can only guess it is something special about `task1` registration... 
Do you register tasks via the UI form or is there a properties file you use via the UI (i.e. paste contents of properties file)?

e.g.:
![Screen Shot 2021-08-11 at 15 57 47](https://user-images.githubusercontent.com/6433390/129094937-1d4ee72c-2466-4a98-b62f-5a3acdb81ee3.png)

vs

![Screen Shot 2021-08-11 at 15 57 59](https://user-images.githubusercontent.com/6433390/129094971-cf6268c7-3473-4b0c-96ba-53c8a70df122.png)


Do you paste/type the DSL into the UI or create the graph manually? Feels like it is pasted DSL, can you try creating the same manually using the UI? Do you get an error on the task1 in this case?

**Comment by dturanski** [comment]
My bad, the version is 2.8.1

**Comment by dturanski** [comment]
@BoykoAlex After reinstalling 2.8.1 and also testing on 2.9.0-SNAPSHOT, I cannot reproduce this either. Thanks for looking.
