### ISSUE TITLE
UI does not show required property prefixes on app info view

### ISSUE THREAD

**Issue by dturanski** [spring-cloud/spring-cloud-dataflow-ui#1755]
**Description:**
The UI shows only simple property names, omitting prefixes that are required to configure the app in some cases. `tasklauncher-dataflow` sink is one example.
**Release versions:**
2.0.5.BUILD-SNAPSHOT

**Steps to reproduce:**
Click on the app details view for `tasklauncher-dataflow` sink and compare to `app info` in the shell.

![Screen Shot 2020-03-03 at 1 29 43 PM](https://user-images.githubusercontent.com/886859/75807307-21441480-5d53-11ea-9203-3cc52679f679.png)
![image](https://user-images.githubusercontent.com/886859/75807401-5486a380-5d53-11ea-9246-5cd055601310.png)

**Comment by jvalkeal** [comment]
Fixed per 253a82320daa643188700e243d4b93fcf805471f and #1754
