### ISSUE TITLE
Update flo to release version

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow-ui#1768]
Need a release from flo and use that instead of git ref.

**Comment by BoykoAlex** [comment]
Sounds good. When do we need Flo to be released? Any date in mind?

**Comment by jvalkeal** [comment]
I think Damien can green light when we don't need changes anymore.

**Comment by BoykoAlex** [comment]
I've released **Flo 0.11.0** such that we can kick the tires on it a bit. If more Flo changes required I'll release **0.11.1**
