### ISSUE TITLE
Plus signs are replaced with spaces in task launcher properties provided via UI

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow-ui#1776]
Description:
When providing additional properties to a task launch via the UI, plus signs within Strings passed are replaced by spaces.

Release versions:
SCDF v2.9.0, see JSON below

Steps to reproduce:

Start up Spring Cloud Data Flow (2.9.0), e.g. via spring-boot:run locally, with spring.cloud.dataflow.features.tasks-enabled=true in the config
Register any app, in the snapshots called "my-test-app"
Register any task, in the snapshots called "my-test-task", which just runs "my-test-app"
In the UI, go to "Tasks", choose your task, and press "Launch Task"
Provide some properties to the tasks that contain plus signs, e.g. by going to "Freetext" and entering
deployer.my-test-task.kubernetes.environmentVariables:=MY_ENV_PLUS='MY+ENV+WITH+PLUS',MY_ENV_SPECIAL_CHARS='!@#$%^&*()_+_ENV'
Launch the task
Check the task execution and its environment variables, e.g. go to "Tasks executions", check the latest execution of your task and validate that the Strings passed have all plus signs replaced by spaces.

Refer to issue https://github.com/spring-cloud/spring-cloud-dataflow/issues/4728 for more detail

**Comment by oodamien** [comment]
@cppwfs

Capture of the API request (header):

![image](https://user-images.githubusercontent.com/487067/140326421-a6e85721-4a7e-402d-a14a-2ac2ed808a54.png)

The `+` sign is present.

**Comment by cppwfs** [comment]
Yep, this looks like its how the server side is handling the + as a space.    Going back to original issue.
