### ISSUE TITLE
i18n: German Translation

### ISSUE THREAD

**Issue by oodamien** [spring-cloud/spring-cloud-dataflow-ui#1797]
Related #701

**Comment by klopfdreh** [comment]
Hey @oodamien - I just saw this issue. Is the current implementation ready to be translated, now?

I may find some time at the weekend and would create a PR for it. 👍

**Comment by oodamien** [comment]
Hi @klopfdreh,
Yes it's. Let me know if there is any blockers, I will be happy to help.
Thanks -
