### ISSUE TITLE
Bad encoding get parameters on Launch task

### ISSUE THREAD

**Issue by oodamien** [spring-cloud/spring-cloud-dataflow-ui#1808]
Step to reproduce:
- Create a task
- Launch the task with a the following value parameter: `{jre: {version: '11.+'}}`
- Check parameter in the header
 
![image (4)](https://user-images.githubusercontent.com/487067/150957506-c61c511f-59e5-490f-91f4-1d1c18156d3e.png)

**Comment by claudiahub** [comment]
Hi @oodamien.
I've tried several solutions applying encoding/decoding URI functions. 
This solves on client side but when we get response from server, the received object still contains the space.
It seems this relates to HttpParameterCodec and there is an open angular issue. [https://github.com/angular/angular/issues/11058]
One solution would be to add an interceptor for this HttpParameterCodec. 
But honestly this would have an impact through all the API server application requests and we should be careful before doing anything on this.

**Comment by claudiahub** [comment]
After investigating, it seems any `+` gets converted into space symbol on server side controller.

Request sent from ui side:

![ frontend](https://user-images.githubusercontent.com/54085737/151543863-4bb448d0-11f5-410c-9880-8761a874a493.png)

On server controller we get this command:

![server](https://user-images.githubusercontent.com/54085737/151543961-cb3d3e85-f50d-42e2-920a-83b65ddd44a0.png)

Also this refers to https://github.com/spring-cloud/spring-cloud-dataflow/issues/4728
