### ISSUE TITLE
Problem with filter task execution in tab Task executions

### ISSUE THREAD

**Issue by szopal** [spring-cloud/spring-cloud-dataflow-ui#1811]
It would be nice, if SCDF would be have a posibility to filter a task execution - i.e. when I want to filter only task-name-1 in task execution tab or to filter by start time. In Task tab is only visible first 10 task execution. 

And second question - it is possible to make a color for rows in Task executions tab if exit code is different than 0? Like a Status in Job executions tab.

**Comment by oodamien** [comment]
Hi @szopal,
Thanks for the feedback. 

I created dedicated issues to move forward:
- https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1824: Paginate executions on Task Page
- https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1825: Filtering Task Execution(s)

The last point will be discuss in the following days with the core team.
