### ISSUE TITLE
Cannot launch tasks with arguments in SCDF 2.9.2

### ISSUE THREAD

**Issue by slobodanl** [spring-cloud/spring-cloud-dataflow-ui#1828]
Hi,

The normal way we launched tasks so far was e.g 
--spring.batch.job.names=testImportJob --spring.profiles.active=development
now that seems not supported from the UI and error is reported "r not iterable".

In old version 2.7.1 there were clear instructions on how we can set arguments:
Arguments can be prefixed by -- (optional). Example:
--myarg1=value1
--myarg2=value2

While in the new version i tried different options all of them failed e.g. with the same error "r not iterable"
app.pia-import-synthetization.0="spring.batch.job.names: testImportJob"
app.pia-import-synthetization.1="spring.profiles.active: development"

I was not able to find documentation of what is expected in the new version related to argument handling.

Thank you for the help beforehand.

**Comment by oodamien** [comment]
Closing - no feedback
