### ISSUE TITLE
Optimize asset loading

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-dataflow-ui#183]
The usual concatenation / minification / etc

See this waterfall capture
<img width="1878" alt="0029-03-30 14 37 49" src="https://cloud.githubusercontent.com/assets/313494/24497189/e2c7167a-153a-11e7-89e4-237f5b3aeceb.png">

cc @making

**Comment by BoykoAlex** [comment]
Should probably look at the size of `spring-flo`... It has `code-mirror` lib with all add-ons and modes bundled with it. Think we can at least use the add-ons and modes that are required and forget about the rest... this should improve the size of `spring-flo` greatly.

**Comment by ghillert** [comment]
If it were me we had all those things in place 2 years ago. But we made some (unfortunate) architectural decision back in the day (using the legacy RequireJS) that broke the original setup. RequireJS has its own bundler. So at this point our assets are unfortunately un-optimized.

Once `1.2` is out we plan to do some serious refactoring towards SCDF `2.0` and have asset optimization in place by default for production deployments.

See also https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/139
