### ISSUE TITLE
Translation issue with missing properties (task executions)

### ISSUE THREAD

**Issue by klopfdreh** [spring-cloud/spring-cloud-dataflow-ui#1860]
Hi,

there is an issue with the translations (keys  EXECUTIONS.EXECUTION.VIEWLOG / EXECUTIONS.EXECUTION.VIEWEXECUTION)

![image](https://user-images.githubusercontent.com/980773/173499250-62737e0d-95f7-49c1-bbad-5fc8f1a0bdda.png)

@claudiahub / @oodamien - have you time to look at it?

**Comment by claudiahub** [comment]
Thanks @klopfdreh for finding this!
