### ISSUE TITLE
Remove bootstrap from logout page

### ISSUE THREAD

**Issue by oodamien** [spring-cloud/spring-cloud-dataflow-ui#1867]
Bootstrap isn't used anywhere else and we should rather remove it or include the files in our project as assets.
Backport to 2.10.x, 2.9.x and 2.8.x

**Comment by klopfdreh** [comment]
Hey @oodamien and @oodamien - I am currently testing 2.10.0-M2 and what I noticed is that you removed bootstrap from logout page, but in login page it is still present. It should be removed from there, too so that bootstrap is not used any longer.
