### ISSUE TITLE
Format numbers to reduce the numbers after the decimal.

### ISSUE THREAD

**Issue by corneil** [spring-cloud/spring-cloud-dataflow-ui#1870]
In statistics we display averages and standard deviations with up too many digits. I suggest we reduce it to 2 digits.

**Comment by claudiahub** [comment]
Hi @corneil,

Thanks for the report on statistics number formatting.

Is this happening in a specific page/area only (e.g.: streams ) or through the whole application ?

Thanks,
Claudia
