### ISSUE TITLE
Bad request when there are no task executions

### ISSUE THREAD

**Issue by klopfdreh** [spring-cloud/spring-cloud-dataflow-ui#1877]
Hey everyone,

we currently have an issue when there are not task executions available for a task. The ui then try to make a request against `/undefined`. I guess this occurs because the last task execution could not be determined and the ui resolves `undefined` for it.

![image](https://user-images.githubusercontent.com/980773/178405491-749f0871-7a46-4b01-b1f5-e0bddce38c72.png)

SCDF Server: 2.9.4
SCDF UI: 3.3.0-SNAPSHOT (current state of main branch)

I guess this could be prevent by just checking the last execution id not to be undefined.

**Comment by onobc** [comment]
Thanks for the report @klopfdreh . We will discuss at team meeting tomorrow.
