### ISSUE TITLE
 Child task properties are not showing up in composed task runner task ui

### ISSUE THREAD

**Issue by klopfdreh** [spring-cloud/spring-cloud-dataflow-ui#1880]
Because the composed task runner needs their child task properties configured like the following example:

`app.<composed task definition name>.<child task app name>.<property>` or `deployer.<composed task definition name>.<child task app name>.<deployer-property>`

This is described here: https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_passing_properties_to_the_child_tasks

The UI of the composed task does not show the properties / arguments in the builder, because only the following properties / arguments are parsed:

`app.<child task app name>.<property>` or `deployer.<child task app name>.<deployer-property>`

The UI should also consider to check if there are child task properties defined and also show this in the builder / do not show them as errors.

If you configure the composed task without the composed task definition name the properties and arguments are shown in the correct fields in the builder UI but not transferred to the child task - this is very confusing.

**Comment by cppwfs** [comment]
@klopfdreh Thank you for submitting this issue.   In this case we have deprecated the use of `app.ctr-name.child-app-name`.  The updated docs can be found here: https://dataflow.spring.io/docs/feature-guides/batch/composed-task/#arguments-and-properties

I have opened a [PR](https://github.com/spring-cloud/spring-cloud-dataflow/pull/5005) that updates the docs in the dataflow manual (Again thank you for finding this).

**Comment by cppwfs** [comment]
Can you provide a little more detail as to the properties you are setting? 
I did a quick check on a local deployment using the following format:   
`deployer.timestamp-batch.local.java-cmd` and the format worked.     

Thanks again.

**Comment by klopfdreh** [comment]
Sure.

So we are currently building up a whole SCDF infrastructure in kubernetes.

When we start a single task for example `task-a` we followed the instructions here: https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_application_and_server_properties 

So when we start the `task-a` and we hand over environment variables like `deployer.task-a.kubernetes.environmentVariables=myenvvar=test`. When the docker pod starts the environment variables are given to `task-a` and all is working like expected. After the task finished the environment variable is shown in the last task execution.

For Composed Task Runner this is not working, somehow. What we tried is to create a task called `test` and we thought that we can also apply the environment variables like `deployer.task-a.kubernetes.environmentVariables=myenvvar=test`

An example config for the composed task would look like this:
```plain
deployer.*.kubernetes.environmentVariables=OAUTH2_CLIENT_CREDENTIALS_SCOPES=scope1
...
deployer.task-a.kubernetes.environmentVariables=myenvvar=test
...
```

![image](https://user-images.githubusercontent.com/980773/179556044-0305f7fb-300a-4c12-97ff-1dcc19f483b5.png)

We expected the global properties with `*` to be applied to the `test` composed task which was working. And the `deployer.task-a.kubernetes.environmentVariables=myenvvar=test` to be applied to `task-a` which is also shown in the builder ui. But when the composed task runner launches `task-a` the environment variables are not used to start the Docker Pod. When we use `deployer.test.task-a.kubernetes.environmentVariables=myenvvar=test` the environment variables are given to `task-a` but not shown in the builder ui. The only place were they are shown are in `test-task-a` which is created when the composed task `test` is created. 

Hope this helps. 😀

**Comment by klopfdreh** [comment]
Hey @onobc / @cppwfs - I saw this issue is closed, now.

Did you already checked if there is an issue that the properties are not given to the child tasks if kubernetes is used when using the new described way of defining them in the CTR
e.g. `deployer.task-a.kubernetes.environmentVariables`?

**Comment by klopfdreh** [comment]
This issue is not fixed to me.

![image](https://user-images.githubusercontent.com/980773/183574630-882af298-3c95-4779-9128-a423470587bc.png)

When I use the way the documentation is updated the properties of the composed task are not given to the child task.

Here an example:

Composed task name: `test` with DSL `zuwendungen-cleaner-komo-app && zuwendungen-transformer-komo-app`
Task 1: `zuwendungen-cleaner-komo-app` registered as task application
Task 2: `zuwendungen-transformer-komo-app` registered as task application

Task application example screenshot:
![image](https://user-images.githubusercontent.com/980773/183575354-ace12a18-4786-409f-93bb-2e93b0de4043.png)

Spring Cloud Data Flow creates two tasks named `test-zuwendungen-cleaner-komo-app` and `test-zuwendungen-transformer-komo-app` beside the composed task `test`.

When I use the following property:

`deployer.zuwendungen-cleaner-komo-app.kubernetes.environmentVariables=myenvvar=test` it is not given to the child task application `zuwendungen-cleaner-komo-app`. When I use `deployer.test.zuwendungen-cleaner-komo-app.kubernetes.environmentVariables=myenvvar=test` (with `test` after deployer) it is working.

**Comment by onobc** [comment]
Hi @klopfdreh ,
Yeh, I closed it as we thought it was fixed by the recommendation in the docs. We will take a look tomorrow and get back w/ you on this. Sorry this is giving us trouble - we will get you squared away. 

Thanks

**Comment by cppwfs** [comment]
Hello @klopfdreh ,
Sorry for the delay.   I just retried a test where I had a definition of `timestamp && timestamp-batch` and a CTR name of `t`.   
I used the following deployment properties and they both appeared as expected in the pod description:
```
deployer.timestamp-batch.kubernetes.environment-variables=try=that
deployer.timestamp.kubernetes.environment-variables=try=me
```

I tested this on the latest milestone of SCDF which is 2.10.   What version of SCDF are you using?

**Comment by klopfdreh** [comment]
We are using SCDF 2.9.4. Maybe it has something to do with kebab-case vs. camelCase. I am doing some retest and report back later.

**Comment by klopfdreh** [comment]
@cppwfs I tested it with kebab-case, too but it is still now working for me:
```plain
deployer.child-task.kubernetes.environment-variables=APPLICATION_NAME='child-task', .........
```
After I launched the task I checked if the environment variables were set. In the editor however I could see them:

Screenshot of the composed task:
![image](https://user-images.githubusercontent.com/980773/184805046-746a8625-6fd4-43a8-a016-e438f7102b53.png)

Screenshot of one of the child task that were started with the environment variables mentioned above:
![image](https://user-images.githubusercontent.com/980773/184805190-9622570e-df74-4af1-9d0b-bca61cb586e4.png)

Sadly the pod does not receive the envonment variable APPLICATION_NAME. 😞

**Comment by klopfdreh** [comment]
I just checked the pod of the CTR in kubernetes. What I noticed is that when i used `deployer.test.mytask.environment-variables` is that there are only two environment variables `COMPOSED-TASK-APP-PROPERTIES_BASE64_.......` but when I used `deployer.mytask.environment-variables` there are a lot more. Maybe this is an indicator of what happens.

**Comment by klopfdreh** [comment]
I saw that the CTR properties are somehow decoded (propertiesFrom): https://github.com/spring-cloud/spring-cloud-dataflow/blob/main/spring-cloud-dataflow-composed-task-runner/src/main/java/org/springframework/cloud/dataflow/composedtaskrunner/ComposedTaskRunnerStepFactory.java#L131

But the task specific properties (this.taskSpecificProps) aren't:
https://github.com/spring-cloud/spring-cloud-dataflow/blob/450027466c43fdd1c20dd8503a97fced205bf336/spring-cloud-dataflow-composed-task-runner/src/main/java/org/springframework/cloud/dataflow/composedtaskrunner/ComposedTaskRunnerStepFactory.java#L138

Maybe I don't see the implementation, but should the task specific properties also be decoded, shouldn't they?

**Comment by cppwfs** [comment]
Hello @klopfdreh 
I'm still not able to replicate.    
Can you modify this deployment property I'm sharing with you such that it will not succeed on your deployment.   
`deployer.timestamp.kubernetes.environment-variables=APPLICATION_NAME='one',CLOUD_ENV='two'`

Thanks

**Comment by klopfdreh** [comment]
Hey @cppwfs 

I changed the child app deployer reference to something which is not working. In this case the editor shows it like expected

![image](https://user-images.githubusercontent.com/980773/185547566-8e1385ba-5721-4d9f-9700-488bed37a194.png)

**Comment by cppwfs** [comment]
Can you share a cleansed version of your deployer property so that I can replicate .   I can't see what is in the content that is not working, because of the redaction.  
And sharing it in text vs. screenshot would be most helpful.

Thanks.

**Comment by klopfdreh** [comment]
Hey @cppwfs - sure, but it will take some time.

**Comment by klopfdreh** [comment]
Hey @cppwfs

here the cleansed examples.

**when I use these properties, the compose task runner is launching the child task without any problems and with env vars, pvc, etc. (this way is now deprecated as I understood)**:
```plain
deployer.*.kubernetes.environmentVariables=debug='all',SPRING_CLOUD_TASK_BATCH_FAILONJOBFAILURE='true',OAUTH2_CLIENT_CREDENTIALS_SCOPES='scope1,scope2,scope3,scope4,scope5,scope6',OAUTH2_CLIENT_CREDENTIALS_TOKEN_URI='https://tokenserverdomain.de/komo/authenticationServer/api/oauth2/token',OAUTH2_CLIENT_CREDENTIALS_CLIENT_AUTHENTICATION_METHOD='CLIENT_SECRET_POST'
deployer.*.kubernetes.secretKeyRefs=[{envVarName: 'OAUTH2_CLIENT_CREDENTIALS_CLIENT_ID', secretName: 'iam-oauth-client-credentials-flow-credentials-dev', dataKey: 'clientId'},{envVarName: 'OAUTH2_CLIENT_CREDENTIALS_CLIENT_SECRET', secretName: 'iam-oauth-client-credentials-flow-credentials-dev', dataKey: 'clientSecret'}]

deployer.test.task-a.kubernetes.limits.cpu=1200m
deployer.test.task-a.kubernetes.environmentVariables=APPLICATION_NAME='task-a',CLOUD_ENV='dev',RT_ENV='KOMO',ENV='komo',DRYRUN='true',TASK_RESULT_DATASOURCE_URL='jdbc:postgresql://db-dev.cluster-xxxxxxxxxxxx.eu-central-1.rds.amazonaws.com:5432/task_komo',TRANSACTION_LOG_MOUNT_PATH='/persistent',OTEL_SERVICE_NAME='task-a-komo-task',RETENTION_DAYS='150'
deployer.test.task-a.kubernetes.secretKeyRefs=[{envVarName: 'TASK_RESULT_DATASOURCE_USERNAME', secretName: 'task-db-credentials-komo', dataKey: 'username'},{envVarName: 'TASK_RESULT_DATASOURCE_PASSWORD', secretName: 'task-db-credentials-komo', dataKey: 'password'}]
deployer.test.task-a.kubernetes.volumes=[{name: 'pvc-task-a-atomikos-komo', persistentVolumeClaim: { claimName: 'pvc-task-a-atomikos-komo', readOnly: 'false' }}]
deployer.test.task-a.kubernetes.volumeMounts=[{name: 'pvc-task-a-atomikos-komo', mountPath: '/persistent'}]
deployer.test.task-a.kubernetes.deploymentLabels=myLabel

deployer.test.task-b.kubernetes.limits.cpu=1200m
deployer.test.task-b.kubernetes.environmentVariables=APPLICATION_NAME='task-b',ENV='komo',RT_ENV='KOMO',DRYRUN='true',TASK_RESULT_DATASOURCE_URL='jdbc:postgresql://db-dev.cluster-xxxxxxxxxxxx.eu-central-1.rds.amazonaws.com:5432/task_komo',TRANSACTION_LOG_MOUNT_PATH='/persistent',OTEL_SERVICE_NAME='task-b-komo-task',AWS_ACCOUNT_ENDPOINT='https://bucket.vpce-xxxxxxxxxxxxxxxxx-5icphead.s3.eu-central-1.vpce.amazonaws.com',AWS_BUCKET_NAME='lf-lums-s3-bucket-dev',MONATS_FORTSCHREIBUNG_CONFIG_PATH='/monatsfortschreibung/monatsfortschreibung.csv'
deployer.test.task-b.kubernetes.secretKeyRefs=[{envVarName: 'TASK_RESULT_DATASOURCE_USERNAME', secretName: 'task-db-credentials-komo', dataKey: 'username'},{envVarName: 'TASK_RESULT_DATASOURCE_PASSWORD', secretName: 'task-db-credentials-komo', dataKey: 'password'},{envVarName: 'AWS_IAM_USER_ACCESS_KEY_ID', secretName: 'aws-s3-dev', dataKey: 'AWS_IAM_USER_ACCESS_KEY_ID'},{envVarName: 'AWS_IAM_USER_SECRET_KEY', secretName: 'aws-s3-dev', dataKey: 'AWS_IAM_USER_SECRET_KEY'}]
deployer.test.task-b.kubernetes.volumes=[{name: 'pvc-task-b-atomikos-komo', persistentVolumeClaim: { claimName: 'pvc-task-b-atomikos-komo', readOnly: 'false' }},{name: 'monatsfortschreibung-dev', configMap: { name: 'monatsfortschreibung-dev', defaultMode: 256 }}]
deployer.test.task-b.kubernetes.volumeMounts=[{name: 'pvc-task-b-atomikos-komo', mountPath: '/persistent'},{name: 'monatsfortschreibung-dev', mountPath: '/monatsfortschreibung/'}]
deployer.test.task-b.kubernetes.deploymentLabels=myLabel
```

the properties `deployer.*.kubernetes....` are stored into the CTR `test` and the properties `deployer.test.task-a.kubernetes...` are stored into the task `test-task-a` /  the properties `deployer.test.task-b.kubernetes...` are stored into the task `test-task-b` which are created when you create the CTR itself. (DSL: task-a && task-b)

I checked this by pressing the launch button in the SCDF-UI after the first run of the CTR with the given properties.

**but when I use these - it is not working (note: after deployer we removed `.test`**:
```plain
deployer.*.kubernetes.environmentVariables=debug='all',SPRING_CLOUD_TASK_BATCH_FAILONJOBFAILURE='true',OAUTH2_CLIENT_CREDENTIALS_SCOPES='scope1,scope2,scope3,scope4,scope5,scope6',OAUTH2_CLIENT_CREDENTIALS_TOKEN_URI='https://tokenserverdomain.de/komo/authenticationServer/api/oauth2/token',OAUTH2_CLIENT_CREDENTIALS_CLIENT_AUTHENTICATION_METHOD='CLIENT_SECRET_POST'
deployer.*.kubernetes.secretKeyRefs=[{envVarName: 'OAUTH2_CLIENT_CREDENTIALS_CLIENT_ID', secretName: 'iam-oauth-client-credentials-flow-credentials-dev', dataKey: 'clientId'},{envVarName: 'OAUTH2_CLIENT_CREDENTIALS_CLIENT_SECRET', secretName: 'iam-oauth-client-credentials-flow-credentials-dev', dataKey: 'clientSecret'}]

deployer.task-a.kubernetes.limits.cpu=1200m
deployer.task-a.kubernetes.environmentVariables=APPLICATION_NAME='task-a',CLOUD_ENV='dev',RT_ENV='KOMO',ENV='komo',DRYRUN='true',TASK_RESULT_DATASOURCE_URL='jdbc:postgresql://db-dev.cluster-xxxxxxxxxxxx.eu-central-1.rds.amazonaws.com:5432/task_komo',TRANSACTION_LOG_MOUNT_PATH='/persistent',OTEL_SERVICE_NAME='task-a-komo-task',RETENTION_DAYS='150'
deployer.task-a.kubernetes.secretKeyRefs=[{envVarName: 'TASK_RESULT_DATASOURCE_USERNAME', secretName: 'task-db-credentials-komo', dataKey: 'username'},{envVarName: 'TASK_RESULT_DATASOURCE_PASSWORD', secretName: 'task-db-credentials-komo', dataKey: 'password'}]
deployer.task-a.kubernetes.volumes=[{name: 'pvc-task-a-atomikos-komo', persistentVolumeClaim: { claimName: 'pvc-task-a-atomikos-komo', readOnly: 'false' }}]
deployer.task-a.kubernetes.volumeMounts=[{name: 'pvc-task-a-atomikos-komo', mountPath: '/persistent'}]
deployer.task-a.kubernetes.deploymentLabels=myLabel

deployer.task-b.kubernetes.limits.cpu=1200m
deployer.task-b.kubernetes.environmentVariables=APPLICATION_NAME='task-b',ENV='komo',RT_ENV='KOMO',DRYRUN='true',TASK_RESULT_DATASOURCE_URL='jdbc:postgresql://db-dev.cluster-xxxxxxxxxxxx.eu-central-1.rds.amazonaws.com:5432/task_komo',TRANSACTION_LOG_MOUNT_PATH='/persistent',OTEL_SERVICE_NAME='task-b-komo-task',AWS_ACCOUNT_ENDPOINT='https://bucket.vpce-xxxxxxxxxxxxxxxxx-5icphead.s3.eu-central-1.vpce.amazonaws.com',AWS_BUCKET_NAME='lf-lums-s3-bucket-dev',MONATS_FORTSCHREIBUNG_CONFIG_PATH='/monatsfortschreibung/monatsfortschreibung.csv'
deployer.task-b.kubernetes.secretKeyRefs=[{envVarName: 'TASK_RESULT_DATASOURCE_USERNAME', secretName: 'task-db-credentials-komo', dataKey: 'username'},{envVarName: 'TASK_RESULT_DATASOURCE_PASSWORD', secretName: 'task-db-credentials-komo', dataKey: 'password'},{envVarName: 'AWS_IAM_USER_ACCESS_KEY_ID', secretName: 'aws-s3-dev', dataKey: 'AWS_IAM_USER_ACCESS_KEY_ID'},{envVarName: 'AWS_IAM_USER_SECRET_KEY', secretName: 'aws-s3-dev', dataKey: 'AWS_IAM_USER_SECRET_KEY'}]
deployer.task-b.kubernetes.volumes=[{name: 'pvc-task-b-atomikos-komo', persistentVolumeClaim: { claimName: 'pvc-task-b-atomikos-komo', readOnly: 'false' }},{name: 'monatsfortschreibung-dev', configMap: { name: 'monatsfortschreibung-dev', defaultMode: 256 }}]
deployer.task-b.kubernetes.volumeMounts=[{name: 'pvc-task-b-atomikos-komo', mountPath: '/persistent'},{name: 'monatsfortschreibung-dev', mountPath: '/monatsfortschreibung/'}]
deployer.task-b.kubernetes.deploymentLabels=myLabel
```

In this case all properties are stored into the CTR `test` as shown in the screenshot (also `deployer.test.task-a.kubernetes...` and  `deployer.test.task-b.kubernetes...`), but the Kubernetes-PODs are not started with the corresponding environment variables, or pvcs, etc.

Hope this helps.

**Comment by cppwfs** [comment]
Here is how I modified the parameters above:
```
deployer.task-a.kubernetes.limits.cpu=1200m
deployer.task-a.kubernetes.environment-variables=APPLICATION_NAME='t-timestamp',CLOUD_ENV='dev',RT_ENV='KOMO',ENV='komo',DRYRUN='true',TASK_RESULT_DATASOURCE_URL='jdbc:postgresql://db-dev.cluster-xxxxxxxxxxxx.eu-central-1.rds.amazonaws.com:5432/task_komo',TRANSACTION_LOG_MOUNT_PATH='/persistent',OTEL_SERVICE_NAME='t-timestamp-komo-task',RETENTION_DAYS='150'
deployer.task-a.kubernetes.secret-key-refs=[{envVarName: 'TASK_RESULT_DATASOURCE_USERNAME', secretName: 'task-db-credentials-komo', dataKey: 'username'},{envVarName: 'TASK_RESULT_DATASOURCE_PASSWORD', secretName: 'task-db-credentials-komo', dataKey: 'password'}]
deployer.task-a.kubernetes.volumes=[{name: 'pvc-t-timestamp-atomikos-komo', persistentVolumeClaim: { claimName: 'pvc-t-timestamp-atomikos-komo', readOnly: 'false' }}]
deployer.task-a.kubernetes.volume-mounts=[{name: 'pvc-t-timestamp-atomikos-komo', mountPath: '/data'}]
deployer.task-a.kubernetes.deployment-labels=alabel:myLabel

deployer.task-b.kubernetes.limits.cpu=1200m
deployer.task-b.kubernetes.environment-variables=APPLICATION_NAME='t-timestamp-batch',ENV='komo',RT_ENV='KOMO',DRYRUN='true',TASK_RESULT_DATASOURCE_URL='jdbc:postgresql://db-dev.cluster-xxxxxxxxxxxx.eu-central-1.rds.amazonaws.com:5432/task_komo',TRANSACTION_LOG_MOUNT_PATH='/persistent',OTEL_SERVICE_NAME='t-timestamp-batch-komo-task',AWS_ACCOUNT_ENDPOINT='https://bucket.vpce-xxxxxxxxxxxxxxxxx-5icphead.s3.eu-central-1.vpce.amazonaws.com',AWS_BUCKET_NAME='lf-lums-s3-bucket-dev',MONATS_FORTSCHREIBUNG_CONFIG_PATH='/monatsfortschreibung/monatsfortschreibung.csv'
deployer.task-b.kubernetes.secret-key-refs=[{envVarName: 'TASK_RESULT_DATASOURCE_USERNAME', secretName: 'task-db-credentials-komo', dataKey: 'username'},{envVarName: 'TASK_RESULT_DATASOURCE_PASSWORD', secretName: 'task-db-credentials-komo', dataKey: 'password'},{envVarName: 'AWS_IAM_USER_ACCESS_KEY_ID', secretName: 'aws-s3-dev', dataKey: 'AWS_IAM_USER_ACCESS_KEY_ID'},{envVarName: 'AWS_IAM_USER_SECRET_KEY', secretName: 'aws-s3-dev', dataKey: 'AWS_IAM_USER_SECRET_KEY'}]
deployer.task-b.kubernetes.volumes=[{name: 'pvc-t-timestamp-batch-atomikos-komo', persistentVolumeClaim: { claimName: 'pvc-t-timestamp-batch-atomikos-komo', readOnly: 'false' }},{name: 'monatsfortschreibung-dev', configMap: { name: 'monatsfortschreibung-dev', defaultMode: 256 }}]
deployer.task-b.kubernetes.volume-mounts=[{name: 'pvc-t-timestamp-batch-atomikos-komo', mountPath: '/data'},{name: 'monatsfortschreibung-dev', mountPath: '/monatsfortschreibung/'}]
deployer.task-b.kubernetes.deployment-labels=blabel:myLabel
```

* Replaced camel case with kabob case for the deployment property keys
* Updated the deployment labels so that it was syntactically correct.
* Added mounts and secrets as needed to my local system.   

We are missing something here.  I'm not sure what.

**Comment by klopfdreh** [comment]
Hey @cppwfs,

as I mentioned here: https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1880#issuecomment-1216171056 I also tested with kebab-case which doesn’t solve the problem.

The deployment-label was a mistake of the cleanse - we are using key:value syntax.

Maybe this is also important - we are using the entry point style shell: https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_entry_point_style

**Comment by klopfdreh** [comment]
I tested the CTR with (1) `deployer.test.task-a` against (2) `deployer.task-a` and set spring to debug. I found out that (1) sends the properties to the rest api of the scdf server, when starting the child task:
```plain
{"timestamp":"2022-08-23T06:52:59.526+0200","level":"DEBUG","thread":"main","logger":"org.springframework.web.client.RestTemplate","message":"HTTP POST https://scdf-server:8443/context/tasks/executions?name=task-a","context":"default"}
{"timestamp":"2022-08-23T06:52:59.527+0200","level":"DEBUG","thread":"main","logger":"org.springframework.web.client.RestTemplate","message":"Accept=[application/json, application/*+json]","context":"default"}
{"timestamp":"2022-08-23T06:52:59.527+0200","level":"DEBUG","thread":"main","logger":"org.springframework.web.client.RestTemplate","message":"Writing [{properties=[deployer.task-a.kubernetes.volumes...]...] with org.springframework.http.converter.support.AllEncompassingFormHttpMessageConverter","context":"default"}
```
I shortened the properties with `...]...`

(2) however does not send them to the server:
```
{"timestamp":"2022-08-23T06:49:03.536+0200","level":"DEBUG","thread":"main","logger":"org.springframework.web.client.RestTemplate","message":"HTTP POST https://scdf-server:8443/context/tasks/executions?name=task-a","context":"default"}
{"timestamp":"2022-08-23T06:49:03.536+0200","level":"DEBUG","thread":"main","logger":"org.springframework.web.client.RestTemplate","message":"Accept=[application/json, application/*+json]","context":"default"}
{"timestamp":"2022-08-23T06:49:03.537+0200","level":"DEBUG","thread":"main","logger":"org.springframework.web.client.RestTemplate","message":"Writing [{properties=[spring.cloud.dataflow.task.platformName=default], arguments=[--spring.cloud.task.parent-execution-id=844]}] with org.springframework.http.converter.support.AllEncompassingFormHttpMessageConverter","context":"default"}
```

As far as I understand there is a logic that retrieves the properties for each child task from out of the environment variables of the CTR. While this is working for `deployer.test.task-a`, it is not working for `deployer.task-a` for us.

**Comment by cppwfs** [comment]
WOOOT WOOT.... Entrypoint was the missing element of this mystery.   Investigating

**Comment by klopfdreh** [comment]
😃 yeeeeesss!

**Comment by cppwfs** [comment]
Moving this issue over to SCDF as it is not a UI issue .     @klopfdreh thanks for your help on this .
The new issue is https://github.com/spring-cloud/spring-cloud-dataflow/issues/5070
