### ISSUE TITLE
Task executions status label

### ISSUE THREAD

**Issue by claudiahub** [spring-cloud/spring-cloud-dataflow-ui#1904]
_**Description:**_
The "Task executions" view shows a wrong status for RUNNING tasks. 
The running tasks are currently reported as "ERROR".
The detail view shows the correct status as "RUNNING".
The tasks run fine. No, errors in the logs.

**_Screenshots:_**
![image](https://user-images.githubusercontent.com/54085737/213549751-0199f413-1277-489d-88dd-7f76d50335ad.png)

![image](https://user-images.githubusercontent.com/54085737/213549783-00a14dbd-1a71-40fe-baa0-40717d1ac0d3.png)

**Comment by onobc** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-dataflow-ui/commit/37eb5d7dcb196fab53f3b6b3be8971fd7e7171c3
