### ISSUE TITLE
Call the /metrics endpoint in SCDF to annotate Flo graph with message rates

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow-ui#191]
This depends on a PR for https://github.com/spring-cloud/spring-cloud-dataflow/issues/1286

One can get a head start on seeing the returned data that you can expect by building https://github.com/spring-cloud/spring-cloud-dataflow-metrics-collector and hitting the http://localhost:8080/collector/metrics endpoint

**Comment by BoykoAlex** [comment]
Do I need to add `mterics-collector` to `dataflow` classpath? In other words add a maven dependency to `dataflow` on `metrics-controller` to make it work?
