### ISSUE TITLE
Remove Step Counts from Step Execution page

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow-ui#1932]
Remove the following statistics on the step execution page as they are scheduled for [deprecation](https://github.com/spring-cloud/spring-cloud-dataflow/pull/5126):
* Filter Count
* Process Skip Count
* Read Count
* Read Skip Count
* Rollback Count
* Write Count
* Write Skip Count
* Duration Per Read

**Comment by oodamien** [comment]
@cppwfs Should we remove info from this panel (on Job execution page)?

<img width="1518" alt="image" src="https://github.com/spring-cloud/spring-cloud-dataflow-ui/assets/487067/e72be08b-7c63-4192-a359-d81a94ad8341">

**Comment by cppwfs** [comment]
Great question.   We need to remove the StepExecution History section from the Step Execution Page.  For example:
<img width="613" alt="image" src="https://github.com/spring-cloud/spring-cloud-dataflow-ui/assets/695673/4dd160be-cb1a-46db-948e-158773b91e6e">
The other statistics we can keep.  Sorry for the confusion.
