### ISSUE TITLE
Task Execution Log doesn't scroll horizontally

### ISSUE THREAD

**Issue by corneil** [spring-cloud/spring-cloud-dataflow-ui#1944]
The task execution log view only scrolls vertically but doesn't wrap the output. 
So one cannot see the output.
We should consider providing for a log download.

**Comment by corneil** [comment]
![image](https://github.com/spring-cloud/spring-cloud-dataflow-ui/assets/466422/b1d6552c-f760-4f14-998c-5729ed2aa162)

**Comment by corneil** [comment]
Works as expected on Firefox, Chrome and Edge.

**Comment by rajesh-rajasekaran** [comment]
Updated SCDF server to 2.11.2, but still having this issue, please refer the Screenshot below

![image](https://github.com/spring-cloud/spring-cloud-dataflow-ui/assets/133942896/9949cb4a-9282-4b2b-9097-d729eaeb1dd4)
