### ISSUE TITLE
Sorting on column "Schema target" in task executions UI gives error dialog

### ISSUE THREAD

**Issue by onobc** [spring-cloud/spring-cloud-dataflow-ui#1948]
- Navigate to SCDF UI
- Create task
- Launch task
- Navigate to task executions
- Click the "Schema Target" column

💥 💥 
<img width="1150" alt="Screen Shot 2023-08-29 at 22 52 22" src="https://github.com/spring-cloud/spring-cloud-dataflow-ui/assets/28907971/07d0b6c9-aadf-4e32-96fb-1a175cc5c79a">

**Comment by oodamien** [comment]
Wait server side feature.
