### ISSUE TITLE
jobs.main.stop translation missing

### ISSUE THREAD

**Issue by klopfdreh** [spring-cloud/spring-cloud-dataflow-ui#1961]
**Description:**
When you stop a job execution the translation `jobs.main.stop` is missing and the translation key is show in the button.

**Release versions:**
2.11.0-RC1

**Custom apps:**
N/A

**Steps to reproduce:**
Start a task application and stop it.

**Screenshots:**
N/A

**Additional context:**
N/A

**Comment by klopfdreh** [comment]
I am going to upgrade to 2.11.0 when it is released - if this issue still occurs I come back and show it here. :-)

**Comment by klopfdreh** [comment]
Hey @claudiahub,

I just checked it. The translation was missing at 2.10.3 but is fixed at 2.11.0-RC1.

Sorry for the effort and thanks for having a look!

**Comment by claudiahub** [comment]
@klopfdreh thanks, glad to hear this!
