### ISSUE TITLE
Task Execution Detail Page is not displayed properly 

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow-ui#1968]
The Task Detail page that is shown immediately following the task launch does not display the page.   
1. Launch a task definition
2. The task detail page will not be displayed properly
Possible Cause:
The HTTP request sent to dataflow looks like `http://localhost:9393/tasks/executions/[object%20Object]?schemaTarget=undefined`

We are also unable to view Task detail for a task execution. 
1. Go to task executions page and click a task execution number, UI does not navigate to the detail page.
2. Clicking the task definition name on the task execution will take you to the latest task execution which is displayed.

This was observed on SCDF-CF and is reproducible on the other versions SCDF-Local and SCDF-K8s.

**Comment by oodamien** [comment]
Fixed https://github.com/spring-cloud/spring-cloud-dataflow-ui/pull/1969
