### ISSUE TITLE
Polish Metrics on Flo graph

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#198]
As a follow up to https://github.com/spring-cloud/spring-cloud-dataflow-ui/pull/195

We should:

* Minimize logging output
* Polish code
  - Consider refactoring some code from `ui/app/scripts/stream/controllers/stream.js` into a service
  - Revisit commented-out code
* Consider polishing tooltip position (Avoid going beyond bottom browser-window)
* Optimize the way we load metrics on the stream definitions page:

We have a pageable list of stream definitions which only constitutes a subset of the data but we load the metrics un-parameterized:

* Shouldn't that ideally take the pageable into account?
* OR should the metrics information be loaded only on mouse-over?
* We load the metrics without using the BusyPromise. In case the loading takes a long time, the user does not have a visual hue.

**Comment by sabbyanandan** [comment]
Metrics widgets have evolved in the v2.0 line. I'm closing this as invalid.
