### ISSUE TITLE
Spring boot version field is disabled in SCDF UI 2.11.0 dashboard while registering the app in dashboard, this is preventing registration of app because of missing fields

### ISSUE THREAD

**Issue by rathodajay10** [spring-cloud/spring-cloud-dataflow-ui#1991]
**Description:**
Recently I upgraded Spring cloud dataflow Server and skipper from 2.9.0 to 2.11.0, After the upgrade first of all all the apps that were running earlier were gone, I don't see anything on the dashboard. secondly, I am trying to import the application manually by importing the docker URI. In latest version we can choose the Spring boot version field which is disabled for me and that is preventing me from registering existing apps. It wasn't the case in the previous version. Let me know if i am missing some propert y or some environment variables? Thanks
<img width="1589" alt="Screenshot 2024-03-13 at 12 55 49" src="https://github.com/spring-cloud/spring-cloud-dataflow/assets/53635157/1f4fc56c-b83f-4bc4-a97d-be99ee0d64ec">

**Release versions:**
SCDF server version - 2.11.0
SCDF skipper version - 2.11.0

**Custom apps:**
This app is running on the Kubernetes cluster behind the proxy, If i run the jar locally i can see the spring boot version field in the application register tab but not on kubernetes cluster.

**Comment by corneil** [comment]
Can you use developer tools (F12) to view network activity.

When you click on Applications and expand the Registry one or more applications you should see a request to the server like `http://localhost:9393/schema/versions` and then a response: `{"defaultSchemaVersion":"2","versions":["2","3"]}` This is used to provide the entries for the dropdown.

**Comment by rathodajay10** [comment]
Thanks Corneil for the reply and solution. There was issue with our Nginx which was blocking this API calls hence not rendering the default versions of it. we can close this issue.
