### ISSUE TITLE
Add SPI type and version in 'about' section

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#2]
As a user, I'd like to see the version and SPI type in the `about` section, so I can confirm which build of *admin-ui* I'm currently using.

**Acceptance:**
The requirement for REST-API to include SPI type and the corresponding release revision is documented

**Comment by ghillert** [comment]
PR: https://github.com/spring-cloud/spring-cloud-dataflow-ui/pull/26
