### ISSUE TITLE
Create Task Modules tab

### ISSUE THREAD

**Issue by mminella** [spring-cloud/spring-cloud-dataflow-ui#20]
As a developer, I want to be able to see a list of task modules I can run.

**Comment by ghillert** [comment]
Depends on https://github.com/spring-cloud/spring-cloud-dataflow/issues/436

**Comment by ghillert** [comment]
Depends on https://github.com/spring-cloud/spring-cloud-dataflow/issues/433
Depends on https://github.com/spring-projects/spring-boot/pull/5335

**Comment by ghillert** [comment]
PR https://github.com/spring-cloud/spring-cloud-dataflow-ui/pull/29
