### ISSUE TITLE
set timezone to scdf dashboard

### ISSUE THREAD

**Issue by GYEOLELEE** [spring-cloud/spring-cloud-dataflow-ui#2009]
- I use spring-cloud-dataflow(scdf) in the k8s environment. 
- As a team rule, the application and database time zone must be set to Asia/Seoul.
- The timezone will be modified by changing the application property as follows. `spring.cloud.dataflow.task.platform.kubernetes.accounts.default.environmentVariables=JAVA_TOOL_OPTIONS=-Duser.timezone=Asia/Seoul`

However, in scdf dashboard, it is considered UTC and shows +9 at the stored time.
How can I set the dashboard default timezone?

GOAL: set timezone to scdf dashboard

Ref: https://stackoverflow.com/questions/77952329/spring-cloud-dataflow-ui-timezone-use-only-utc
Cc: @[hotjoy](https://github.com/hotjoyit)

**Comment by corneil** [comment]
@GYEOLELEE 
The property `spring.cloud.dataflow.task.platform.kubernetes.accounts.default.environmentVariables` will only affect the timezone of deployed tasks.

Setting the `environmentVariables` to `TZ=Asia/Seoul` will apply to all programs in the pod as well as JVM.
Also configure the timezones of Dataflow and Skipper by adding to deployments.

```yaml
    env:
        TZ: Asia/Seoul
````

**Comment by corneil** [comment]
@GYEOLELEE Can you provide a screen shot of the times that are not being displayed as expected. If this includes the desktop display of the system time it will be helpful.

**Comment by hotjoyit** [comment]
@corneil Thank you so much for your response! Your guidance was instrumental in resolving our issue, and we truly appreciate the support you’ve provided. Our team can now move forward smoothly thanks to your help.
