### ISSUE TITLE
Hitting the back button on the step page use stepID instead of JobExecutionId

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow-ui#205]
Steps to recreate:
1) On the batch jobs tab select a Job Execution by clicking magnifying glass icon
2) Select the last Step from job execution by clicking magnifying glass icon
3) Click Back Button
And the following message will be displayed `The Job Execution Details for Execution ID 4 could not be found`

**Comment by ghillert** [comment]
@cppwfs  Please retest - it seems to work for me.

**Comment by cppwfs** [comment]
Yeah this an old issue we found.   LGTM now.
