### ISSUE TITLE
UI should add checkboxes for cleanup of individual task executions

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#217]
_From @ericbottard on December 12, 2016 11:40_

builds on top of https://github.com/spring-cloud/spring-cloud-dataflow/issues/1055

_Copied from original issue: spring-cloud/spring-cloud-dataflow#1056_

TODOs:
- Test with multiple standalone tasks and also tasks with batch-jobs
- Verify the behavior in Shell vs. REST-APIs

**Comment by oodamien** [comment]
Individual delete + multiple deletes

**Comment by oodamien** [comment]
Bug server side, a task execution can not be deleted.
Reported on the main project (update doc + remove service)
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/2552
