### ISSUE TITLE
Add bulk-operations support for stream-list view

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#223]
As a developer, I'd like to add bulk-operations support in stream-lists view. 

**Acceptance:**

Following bulk operations are supported: 
- Deploy
- Undeploy
- Destroy

The bulk operation support is implemented for the App Registration page:

![image](https://user-images.githubusercontent.com/685363/30560417-943441ae-9c53-11e7-8503-ad0080d6c8d4.png)

It uses the:

* `TriStateCheckboxComponent`
* `TriStateButtonComponent`

**Comment by ghillert** [comment]
Created https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/515 as a follow-up issue.
