### ISSUE TITLE
Refactor and port job launch view to Angular 4

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#236]
As a developer, I'd like to refactor and port Job Launch view (including: props and args widgets) to Angular 2.0 stack.

**Acceptance:**
- Tab ported over based on the standardized infrastructure 
- Data model between the UI and backend is consistent (since Typescript supports generics and casting like Java)
- Tab adapts to PUI theme
- Existing tests adapted to the new stack
- Test coverage improved

**Comment by cppwfs** [comment]
There is no job launch per se'.   It is handled by task launch.   The re-launching of a job is handled by the retry button on Job Execution list page.  So unless there is an objection, I'm closing this issue.
