### ISSUE TITLE
Regression: Task apps list page is broken

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow-ui#244]
With the pagination added to the Apps Controller at the server side, the task tab's apps list page doesn't render the apps correctly.

**Comment by ilayaperumalg** [comment]
This is fixed in data flow server core: https://github.com/spring-cloud/spring-cloud-dataflow/pull/1572

**Comment by sabbyanandan** [comment]
This has been fixed in the server core - no updates necessary in the UI.
