### ISSUE TITLE
Stream definition pagination with filter broken

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow-ui#257]
When using a filter list correctly shown filtered entries but original pagination number is still reflected. i.e if you have 30 defs, filter gives only one, there should be on one page.

**Comment by jvalkeal** [comment]
Well this is weird, server gives wrong total count if `search` is used `curl "http://localhost:9393/streams/definitions?page=0&size=10&search=m14"`
In this case I had defs from `foostream1` to `foostream29`.
```
{
  "_embedded": {
    "streamDefinitionResourceList": [
      {
        "name": "foostream14",
        "dslText": "time|log",
        "status": "undeployed",
        "statusDescription": "The app or group is known to the system, but is not currently deployed",
        "_links": {
          "self": {
            "href": "http://localhost:9393/streams/definitions/foostream14"
          }
        }
      }
    ]
  },
  "_links": {
    "first": {
      "href": "http://localhost:9393/streams/definitions?page=0&size=10"
    },
    "self": {
      "href": "http://localhost:9393/streams/definitions?page=0&size=10"
    },
    "next": {
      "href": "http://localhost:9393/streams/definitions?page=1&size=10"
    },
    "last": {
      "href": "http://localhost:9393/streams/definitions?page=2&size=10"
    }
  },
  "page": {
    "size": 10,
    "totalElements": 29,
    "totalPages": 3,
    "number": 0
  }
}
```

**Comment by jvalkeal** [comment]
Right, current UI is broken as well showing three pages all having one item.

**Comment by ghillert** [comment]
@jvalkeal Thanks for writing this up - I forgot that one. Created a corresponding issue in SCDF:

https://github.com/spring-cloud/spring-cloud-dataflow/issues/1598

**Comment by jvalkeal** [comment]
Fixed with latest changes in SCDF master. Invalid in this project, closing.
