### ISSUE TITLE
About page starts non-working requests

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow-ui#258]
Requests to `http://localhost:4200/websocket/info` start when visiting about page which result `404`. There requests doesn't stop even if navigating away from about page.

![ui-about-bug](https://user-images.githubusercontent.com/50398/28204058-4b0d7864-6874-11e7-8405-340070a68d82.png)

**Comment by jvalkeal** [comment]
Looks like `AboutComponent` contains some prototyping code for websocket which probably should not be there?

**Comment by ghillert** [comment]
@jvalkeal Yes. Need to remove.
