### ISSUE TITLE
Add Cache-Bust to static resources

### ISSUE THREAD

**Issue by Chnoch** [spring-cloud/spring-cloud-dataflow-ui#287]
When upgrading to a new version of the Spring Cloud Data Flow Server, the browser will still load the cached files (HTML, CSS, JS & Images) of the UI from the older release. The user needs to manually clear the cache and refresh the page in order to get the update UI version.
The Spring Cloud Data Flow UI should implement a Cache-Bust for all the files that are updated between releases.

**Comment by sabbyanandan** [comment]
Hi, @Chnoch: We have upgraded the stack to Angular4 and with this, we can compile for production and it creates cache-busting filenames. 

A SNAPSHOT version is available [[1.3.0.BUILD-SNAPSHOT](http://repo.spring.io/libs-snapshot/org/springframework/cloud/spring-cloud-dataflow-server-local/1.3.0.BUILD-SNAPSHOT/spring-cloud-dataflow-server-local-1.3.0.BUILD-SNAPSHOT.jar)] for your testing and feedback. 

This is planned for 1.3 release. If you have any other feedback/concerns around this, please reopen it.

**Comment by Chnoch** [comment]
Perfect, thanks for the information!
