### ISSUE TITLE
Unregister multiple apps doesn't clear button state

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow-ui#288]
After unregistring apps via tri-state-button, it still shows to unregister same count of apps.
![ui-unregister-multiple-apps](https://user-images.githubusercontent.com/50398/28630762-138c59ec-7223-11e7-91d2-f5b87bbe4e2b.png)

**Comment by cppwfs** [comment]
Duplicate of https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/282
