### ISSUE TITLE
Port security infrastructure to Angular4 stack

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#297]
As a developer, I'd like to port and refactor security infrastructure from the legacy to newly updated Angular4 stack.

**Acceptance:**
- Login form and action events ported to the new infrastructure
- Validation mechanics to adapted to the new stack
- Unit tests ported and the coverage improved
- Docs generated

**Comment by ghillert** [comment]
Created https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/368 to ensure that we also migrate OAuth2 security.
