### ISSUE TITLE
UI Spinner stays even after page is loaded

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow-ui#303]
When navigating from tab to tab in the task section the spinner stays spinning.   After spinner is hung, going to other pages will show the same behavior.  Reloading the app resolves the issue.

To Reproduce:
Quickly go from task execution tab to task definition to apps (repeatedly).

**Comment by sabbyanandan** [comment]
Probably related to: spring-cloud/spring-cloud-dataflow-ui#306

**Comment by jvalkeal** [comment]
I think we should remove a whole app level busy indicator as it's more of a annoyance than something providing good feedback to a user. Good example is the app details page which keeps spinning until server returns response which may take a long time waiting app to get loaded.

I don't think it's desirable that user cannot do anything in UI while this spinner is busy.

**Comment by sabbyanandan** [comment]
The task page-load bug is fixed. I don't think there's a specific issue around spinner anymore. Can we close this?

**Comment by sabbyanandan** [comment]
Ping.
