### ISSUE TITLE
Runtime tab missing deployment attributes

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#304]
As a user, I'm trying to review the deployment specifics of running apps (using local server), but I don't see the deployment attributes. 

![image](https://user-images.githubusercontent.com/1562654/28835405-127e5160-769a-11e7-9e39-3c70c90eeeb3.png)

**Comment by ilayaperumalg** [comment]
This issue is the regression of [this](https://github.com/spring-cloud/spring-cloud-dataflow-ui/commit/676da9babda32d605a50fd9edbaa9da3af8f65e8#diff-4272b5dabdc5f4062badbed69fc5edc8R5) change.
