### ISSUE TITLE
Loading task-list-view results in an error

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#306]
As a user, I'm loading the task-list-view and I notice the following in browser console.

![image](https://user-images.githubusercontent.com/1562654/28835609-d3ac7650-769a-11e7-858b-3d14f5264a69.png)

**Comment by sabbyanandan** [comment]
This is noticed when no apps are registered (this URI: http://localhost:9393/dashboard/#/tasks/apps).

**Comment by sabbyanandan** [comment]
Reloading this view after registering apps, I see the following:

![image](https://user-images.githubusercontent.com/1562654/28835703-23e9a43a-769b-11e7-85f9-6d850964541a.png)

**Comment by cppwfs** [comment]
To add detail here.  When no apps are registered, you can click `created composed task`, then `definitions` then apps and each screen is appended to the current screen.

**Comment by jvalkeal** [comment]
I've seen content getting mixed if there are errors in a code. This was cause by gunnar not initialising `appRegistrations` in a constructor when he tweaked things.
