### ISSUE TITLE
Remove XD and module references in the codebase

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow-ui#31]
Several scripts inside the dataflow UI has references to XD as we moved some of the changes from XD admin UI client. It is better we rename them to use `dataflow` instead.

**Comment by sabbyanandan** [comment]
`growl` error messages still shows -> `XD server is down`, when the dataflow-server goes down.

**Comment by ilayaperumalg** [comment]
Merged PR #56 along with the changes as part of 9fef7f8c41234ba0502fe83a38c1dca0c1a5a854
