### ISSUE TITLE
Add Sass Lint support

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#324]
We should ensure that the full build also executed SCSS Lint - 3 options exist:

https://github.com/sasstools/sass-lint
https://github.com/brigade/scss-lint
https://github.com/stylelint/stylelint

See also:

https://stackoverflow.com/a/44038244/835934

So we can execute Angular CLI linting and style linting in 1 command:

`npm run lint`

**Comment by sabbyanandan** [comment]
1.3 release already includes SaaS Lint support; however, further refinement is targeted via spring-cloud/spring-cloud-dataflow-ui#614.
