### ISSUE TITLE
Incorrect value for task duration

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#326]
As a user, I ran a task and while reviewing the task execution, I noticed the task duration with invalid valid - see below.

![image](https://user-images.githubusercontent.com/1562654/28943979-a675d2dc-7855-11e7-8773-76ec7007dede.png)

**Comment by jvalkeal** [comment]
This is something I noticed during the initial work and just added TBD placeholder and then forget to follow up. But looking current 1.2.2 and seeing what task execution details returns from rest for `http://localhost:9393/tasks/executions/1`. (as simple run of timestamp).

`startTime` and `endTime` are missing and 1.2.x UI calculated duration from those(I think). 


```
{
  "executionId": 1,
  "exitCode": 0,
  "taskName": "footask1",
  "startTime": null,
  "endTime": null,
  "exitMessage": null,
  "arguments": [
    
  ],
  "jobExecutionIds": [
    
  ],
  "errorMessage": null,
  "externalExecutionId": "footask1-2e028df9-2333-4043-87e8-abddfaecf952",
  "_links": {
    "self": {
      "href": "http://localhost:9393/tasks/executions/1"
    }
  }
}
```
maybe @mminella or @cppwfs could give some light what we're missing.

**Comment by jvalkeal** [comment]
Also looking 1.2.2, duration is also missing
![tasks-execution-duration-missing](https://user-images.githubusercontent.com/50398/29073645-4bf7313c-7c44-11e7-8ec9-8b12520ef264.png)

**Comment by cppwfs** [comment]
Tested 1.2.2, 1.2.1 of task against SCDF 1.3.0.BUILD-SNAPSHOT.  
When testing against MySQL DB it works fine.
When testing against H2, the task blocks waiting to connect to h2 database.  To verify that SCDF was an issue I attempted to connect to H2 via SQuirreL and it blocked as well.  

(The reason you see an `empty` task execution record is that SCDF creates a empty task execution record prior to launching the task, and then passes the task-execution-id as a parameter to the task.) 

If you confirm you are using H2, we can close this ticket and create one for SCDF.

**Comment by jvalkeal** [comment]
Yeah I was using embedded H2 and not external DB. Always configuring mysql or something else is a bit too much when developing or switching versions. Thx a bunch for pointing this out!

**Comment by sabbyanandan** [comment]
I was using H2 as well. Let's add a story in SCDF.

**Comment by jvalkeal** [comment]
but lets keep this ticket open as duration among other things around it are broken even if external DB is in place.

**Comment by cppwfs** [comment]
Refer to https://github.com/spring-cloud/spring-cloud-dataflow/issues/1628
