### ISSUE TITLE
Error message still shows on valid task definition name

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow-ui#342]
When creating a task definition the comment
`The name of the definition must be different from the app name` still shows up even though the name is valid.  It is no longer highlighted with error coloration, but still present.

**Comment by jvalkeal** [comment]
I didn't hide it because that's how old UI works which I suppose is wrong. At a same time we can show validation error message as I'm also checking if there's spaces.
