### ISSUE TITLE
Improve json-to-typescript domain model

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#358]

**Comment by jvalkeal** [comment]
Moving this to future releases as we need to have discussion how much time we want to invest on this. https://github.com/edcarroll/ta-json have some same ideas from jackson but I'm kinda nervous to use it. We could also invest some time to make similar library which I think would pay back in the future.

**Comment by ghillert** [comment]
Closing for now - For now, Model classes implement the `Serializable<MyModelClass>` interface and the `deserialize` method. That seems to work okay for now. We can revisit in the future in case better options emerge.
