### ISSUE TITLE
Step Name column on StepExecutions list on Job Execution Detail page spills over into other column

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow-ui#359]
From the Job's tab click a magnifying glass button by one of the job executions.  Scroll to the bottom of the page.  When viewing the `Step Name` in the Steps table, if the step name is like `workerStep:partition2` it will spill over into the `Reads` column.

**Comment by jvalkeal** [comment]
NOTE: caused by PUI messing every table.
```
table.table {
  table-layout: fixed;
}
```
