### ISSUE TITLE
Migrate AppsService#getAppInfo() to shared-services module 

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#373]

**Comment by BoykoAlex** [comment]
This will become a blocker pretty soon for Flo...

**Comment by BoykoAlex** [comment]
@ghillert there is no `description` field on the `DetailedAppRegistration`. The response has `shortDescription` field which is `null` for many apps... Is it going to be around after everything is migrated? Or is it intentional?
