### ISSUE TITLE
Runtime and Stream tab results are empty

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#39]
As a user, I deployed the `ticktock` stream successfully, but I cannot see the stream listing in the UI. The same issue is observed with the `runtime` tab as well. However, I do see the results when hitting the respective REST-APIs directly. Following requests result with runtime and stream listing correctly. 

```
http://dataflow-server.navy.springapps.io/runtime/modules
```

```
http://dataflow-server.navy.springapps.io/streams/definitions
```

**Comment by ilayaperumalg** [comment]
I could at least see the stream listed on the `streams` tab but the `runtime` page doesn't list anything.

**Comment by trisberg** [comment]
I don't see anything under the 'Apps' tab or the 'Streams' tab when deploying CF server running on CF, there are entries under `/modules` and `/streams/definitions`

The same UI tabs seem to work fine for the Kubernetes server running locally.

**Comment by trisberg** [comment]
I see the same UI problem running the CF server locally
