### ISSUE TITLE
Focusing for new link controls needs adjustment

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#396]
_There is an issue with focus. Create a stream in the DSL editor, leave your focus in there but hover over a link on the canvas and flip it to secondary. The DSL will not update because the canvas didn't get focus soon enough (when the DSL box loses focus is when the autosync from graph>text switches on). After this first click you will notice the filter box in the palette has focus and things work after that. We need to adjust to a mouseup event for the link control press, rather than mousedown, that should ensure the event happens after the dsl box loses focus._

**Comment by sabbyanandan** [comment]
We will have to restest this story.

**Comment by aclement** [comment]
Retested, all working now! (So fixed implicitly by the general move of everything Flo to latest angular)
