### ISSUE TITLE
Avoid complete re-rendering of D3 charts upon data-changes

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#409]
In the old UI as well as in the current refactoring of the UI, we should not re-render the entire chart for each data-update. By adding this functionality, we can take advantage of smooth D3 transitions as the data is updated for each polling interval.

This not only requires updating the the chart components themselves but also the Angular in regards to table-renderings - need to use `trackBy` e.g.:

```
trackByIndex(index: number, data: any) { return index; }
```

**Comment by ghillert** [comment]
See also https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/416

**Comment by sabbyanandan** [comment]
The current analytics view is unusable when there are multiple charts with different time-triggers. The entire view is reloaded upon each refresh, which is annoying.

**Comment by sabbyanandan** [comment]
Analytics tab is removed in v2.0. This is not required anymore.
