### ISSUE TITLE
TAP'ed streams don't work when created/deployed from Flo

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#413]
As a user, I deployed the following streams from Flo and it doesn't appear to be working as expected. The TAP'ed streams specifically don't appear to be connected to the same consumer-group, so there are no new messages in `STREAM_2` and `STREAM_3` log-apps. 

```
STREAM_1=time | scriptable-transform --script="return ""#{payload.tr('^A-Za-z0-9', '')}""" --language=ruby | log
STREAM_2=:STREAM_1.time > scriptable-transform --script="function double(p) \n{\n     return p + '--' + p;\n}\ndouble(payload);" --language=javascript | log
STREAM_3=:STREAM_1.time > scriptable-transform --script="return payload + '::' + payload" --language=groovy | log
```

**Comment by aclement** [comment]
Does this work when done from the shell? 

I pasted that DSL into the create stream box. I then pressed 'create stream' at this point they all look fine. But then if I browse them in 'definitions'' streams page I can see that all the + characters have disappeared - this affects streams 2 and 3.  Somebody isn't encoding something perhaps.

**Comment by aclement** [comment]
Seems to be the encoding used on the POST.  Old SCDFUI:

http://0.0.0.0:8000/streams/definitions?definition=:STREAM_11.time+%3E+scriptable-transform+--script%3D%22function+double(p)+%5Cn%7B%5Cn+++++return+p+%2B+%27--%27+%2B+p;%5Cn%7D%5Cndouble(payload);%22+--language%3Djavascript+%7C+log&deploy=false&name=STREAM_22

New SCDF UI:

http://localhost:4200/streams/definitions?name=STREAM_2&definition=:STREAM_1.time%20%3E%20scriptable-transform%20--script=%22function%20double(p)%20%5Cn%7B%5Cn%20%20%20%20%20return%20p%20+%20%27--%27%20+%20p;%5Cn%7D%5Cndouble(payload);%22%20--language=javascript%20%7C%20log

**Comment by sabbyanandan** [comment]
Thanks for digging, Andy. As I was prepping for a Flo-demo, I didn't try it on the shell when I logged it. 

@jvalkeal @ghillert - could one of you have a look?

**Comment by BoykoAlex** [comment]
Yes, I'm making a fix for it, but if someone on the core team wants to take over then go ahead.
