### ISSUE TITLE
Provide chart-data with timestamps and use a timescale for the x-axis

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#416]
In an even further improvement of the graph-chart - We should support a true time-series graph. Currently (incl. the old UI), each data-point is placed along the x-axis using the implicit `unitsPerTickX` property and the raw data only represents y-data (It currently behaves more like an ordinal scale)

However, it would be better if each data point had a time-value for the x-axis being passed in. Therefore, the chart would be independent of the polling interval, and any changes we do to the polling interval would be automatically reflected in the chart and we would not have to discard data stemming from old interval data.

**Comment by sabbyanandan** [comment]
Analytics tab is removed in v2.0.
