### ISSUE TITLE
Provide a more robust poller-implementation for analytics 

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#417]
Currently the poller for the analytics page is rather simplistic using `Rx.Observable.interval` [1] 
It would be nice if we had a more robust implementation that might also do incremental back-off in case of errors etc.

See also https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/416

[1] https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/interval.md

**Comment by sabbyanandan** [comment]
Analytics tab is removed in v2.0.
