### ISSUE TITLE
DSL format resets when switching between tabs

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#423]
As a user, I typed `seconds = :timer.time > transform --expression=` in the DSL editor and upon switching tabs and back to the canvas, the DSL changes to `seconds=:timer.time > transform`. Notice the removal of extra spaces and `--expression=` property.

**Comment by aclement** [comment]
You can simulate the problem without switching tabs by simply entering the text above and then clicking on the palette filter text field. This drives the blur action on the DSL text field in the same way that switching tabs would.  I think the fix will be to remove the blur action on the text field and add a focus action on the palette/canvas (likely the palette text box) that turns on graphToSync'ing.  This will mean switching tabs won't trigger the graphToSyncing to happen, only when you start interacting with the graph.  I'm having an easy time turning off blur for the dsl text box but adjusting the textfield focus action is proving tricky, I'll get help from Alex.
