### ISSUE TITLE
Analytics: Improve UX for selecting Counters (Make Pagination aware)

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#426]
The behavior of the pre-existing UI is to select a Metric Type (e.g. Counter) and then the counter name. The counter name is selected from a select-box. However, the REST endpoint to retrieve the list of counters IS paginated.

Therefore, a simple select box will not work for large amounts of counters. We should come up with a smarter/richer select capability (maybe via modal dialog) that takes pagination into account.

**Comment by sabbyanandan** [comment]
Analytics tab is removed in v2.0.
