### ISSUE TITLE
Force package versions

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow-ui#427]
We should have a known set of deps, as much as it's in our control, not to get nasty bugs from packages which just resolves to `latest`.

i.e we had a dance with github.com/valor-software/ngx-bootstrap/issues/2596 where their update broke prod build.

**Comment by ghillert** [comment]
@jvalkeal @cppwfs I wonder if we should lock-down only our OWN custom-provided dependencies but leave the Angular CLI provided dependencies AS-IS. That would:

1. make it easier to spot differences when upgrading Angular CLI
2. most people would probably (maybe?) leave Angular CLI dependencies as provided, thus would be the most-tested constellation of deps.

**Comment by cppwfs** [comment]
Let's ask this question: Can we build a previous release (from scratch) of the UI that is exactly the same as what was released?  If we leave the `^` symbols in the package.json , this will not be the case.  It could introduce a bug if we have to fix a previous version. Or even mask the bug that was reported.

**Comment by jvalkeal** [comment]
When I opened this ticket I was wondering what happens if we force version of module `A` which then have dependence to module `B` with version `^`. Better question is - how or can you lock down versions so that whenever(now or a year later) you build, you get exactly same versions of everything.

With maven this is pretty clear but i.e. with ivy or crazy deps versions defs what eclipse packages are using it's not always clear what you use. I feel that npm package are like wild west where you never really know what's going on.

**Comment by cppwfs** [comment]
In this case I'm suggesting we remove the ^ from the package.json.
