### ISSUE TITLE
Disable "create stream" button if there are validation errors in the DSL/graph

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow-ui#450]
`foo=time` will not show an error with syntax highlighting.  It is caught however, when attempting to creae stream.

**Comment by BoykoAlex** [comment]
Oh think i had to do a bit more than just parse DSL for the DSL editor validation...
Should have made one more function call to get to the errors. Should be easy to correct, will push this fix with my next PR. Anyway, good thing you spotted this problem.

**Comment by BoykoAlex** [comment]
@sabbyanandan I think this should be in M2. It seems to me that this should have been a part of the validation story I've been working on.

**Comment by BoykoAlex** [comment]
@sabbyanandan NVM, I'm already showing all the errors i can in the DSL editor. Other errors don't have a `range` property, thus, cannot be shown for now.
