### ISSUE TITLE
Login errors in browser console

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#454]
As a user, I'm trying the 1.3.BS of CF-server with basic-auth enabled (`SPRING_APPLICATION_JSON: '{"security.basic.enabled": "true", "security.user.name" : "user", "security.user.password" : "password"}'`), but I'm unable to get to the login screen. I see the attached errors in the browser console and the "about" tab shows bogus information.

_Note: Apart from the browser errors, I also suspect the recent [security refactoring work](https://github.com/spring-cloud/spring-cloud-dataflow/pull/1638) might be the cause for it._

**error 1:**
![image](https://user-images.githubusercontent.com/1562654/30387549-aa8a6528-9861-11e7-9595-3c9429ac34c2.png)

**error 2:**
![image](https://user-images.githubusercontent.com/1562654/30387625-ec9b5e36-9861-11e7-9fdc-ce70fecb7ff4.png)

**Comment by jvalkeal** [comment]
I don't see this. What exactly you mean by `BS bits` other than what `BS` usually stands for? ;)

**Comment by sabbyanandan** [comment]
Oops. I meant 1.3.0.BUILD-SNAPSHOT. Have you tried with security enabled?

**Comment by jvalkeal** [comment]
Yeah, `java -jar spring-cloud-dataflow-server-local-1.3.0.BUILD-20170913.162347-66.jar --security.basic.enabled=true --security.user.name=test --security.user.password=pass --security.user.role=VIEW` works fine.

**Comment by jvalkeal** [comment]
Maybe your browser is keeping some stale js libs.

**Comment by sabbyanandan** [comment]
I cleared the cache and it is still the same experience. Also, I'm using 1.3.BS of CF-server.

**Comment by jvalkeal** [comment]
cf server points to 1.3.0.M1 https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/blob/master/pom.xml#L11 so it doesn't used snapshots. And security were broken in first milestone.

**Comment by sabbyanandan** [comment]
Bringing cf-server up to 1.3.BS compatibility (+  security refactoring) fixes the problem. I'm able to login and the basic-auth from the dashboard appears to be working as expected. 

Thanks, @jvalkeal! 

![image](https://user-images.githubusercontent.com/1562654/30392495-dfc31b44-9871-11e7-8ae4-8d9938678115.png)
