### ISSUE TITLE
Analytics: Make all D3 charts updatable

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#457]
Currently, all D3 charts are re-rendered upon data changes. This leads to a choppy user experience. Each chart should provide a `create()` and an `update()` method, and should ensure that data updates  will lead to smooth UI chart transitions.

This issue may be broken into per-chart issues in case of substantial refactoring needs.

**Comment by sabbyanandan** [comment]
We don't use D3 charts anymore. They are delegated to Micrometer backends such as Prometheus + Grafana stack.
