### ISSUE TITLE
Improve error-handling when bulk-defining tasks

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#497]
On the bulk-define task page, the error handling is still lacking compared to the old UI:

![image](https://user-images.githubusercontent.com/685363/31115266-5e3db830-a7bd-11e7-8c85-9ad1366d56e4.png)

Compared to the old UI there is also a checkbox missing to toggle `Verify Apps`)

A work-around solutions was provided as part of:

https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/325

**Comment by sabbyanandan** [comment]
This feature is not in the UI anymore. Closing it as invalid.
