### ISSUE TITLE
Create Streams Tab - Palette not populated

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#511]
Steps to reproduce:

1. Start a fresh SCDF Server (No apps visible yet)
2. `http://localhost:4200/#/streams/create` --> Palette is empty
3. `http://localhost:4200/#/apps` --> List is empty
4. Bulk Import apps: `http://bit.ly/Bacon-RELEASE-stream-applications-rabbit-maven
5. `http://localhost:4200/#/apps` --> Apps are being listed
6. `http://localhost:4200/#/streams/create` --> List is still empty

You have to do a full browser-refresh to get the list of apps.

**Comment by BoykoAlex** [comment]
I'd say this is somewhat expected for now... There used to be a listener mechanism for this in shared (MetmodelListener) and now it's missing. Bug - not a question, but somewhat expected kind of bug.
