### ISSUE TITLE
Automate stream deployment properties based on platform selection

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#515]
When deploying a single stream or if bulk-deploying a stream, you can currently specify ANY property key, when specifying deployment properties. This will error out on the server-side with:

```
Only deployment property keys starting with 'app.' or 'deployer.' allowed, got 'foo.bar'
```

We should improve the validator to pro-actively only allow for those 2 prefixes.

**Comment by sabbyanandan** [comment]
We could further simplify it in the UI by providing the reserved prefixes in a drop-down and perhaps also based on the platform-selection (cf vs. local vs. k8s), we could autofill the secondary dropdown with all the available properties at the deployer and app level (given the stream in focus). 

Lesser of the freeform text, the easier it is to prevent typos. Validations may not be required at all.

**Comment by sabbyanandan** [comment]
Explore UX options to include the following in stream-deployment page.

- platform (dropdown) 
- generic deployment properties (maybe in a table form; a column for each app)
  - memory
  - disk
  - cpu
  - count
  - app-version(s)
  - (an option to add new rows)
- platform-deployer properties (e.g., cf props)
  - buildpack
  - services (rabbit, mysql etc.,)
- app properties 
  - "n" number of app properties (an option to add new rows)

**Comment by oodamien** [comment]
**Stream Deploy** (skipper enable)

![image](https://user-images.githubusercontent.com/487067/36260325-553e27c4-1261-11e8-8638-981c09799667.png)

**Stream Deploy - Application Properties**

![image](https://user-images.githubusercontent.com/487067/36260329-5d004802-1261-11e8-99c2-7e960eefd621.png)

**Comment by sabbyanandan** [comment]
The scope of the spike is complete, #633 will be used for feature implementation.
