### ISSUE TITLE
Fix Windows build issues

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#522]

**Comment by ghillert** [comment]
See https://github.com/spring-projects/spring-flo/pull/12

**Comment by sabbyanandan** [comment]
@ghillert: Can this be closed now since the PR is megred?

**Comment by BoykoAlex** [comment]
Think we need to point to the new spring-flo commit in scdf-ui. This commit: 16d0d3daa74cd19be1b82e17f97ef60c5e792101

**Comment by BoykoAlex** [comment]
I have updated Flo commit to include Gunnar's fix, but there seems to be more stuff to do on the SCDF UI side. There are 2 test failures and `npm start` fails with error about `const` being used in `strict mode`... More work to do here.

**Comment by sabbyanandan** [comment]
We couldn't fix this in the backend; likewise, this continues to be an issue in UI also.
