### ISSUE TITLE
Update to Angular 5 (Incl CLI 1.5)

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#526]
See https://blog.angular.io/version-5-0-0-of-angular-now-available-37e414935ced

**Comment by cppwfs** [comment]
The following issues need to be worked on following this PR merge.
https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/538
https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/536

**Comment by BoykoAlex** [comment]
Think we are blocked by RxJS 5.5.2 issues:
https://github.com/ReactiveX/rxjs/issues/3060
Flo sample doesn't work because of: https://github.com/ReactiveX/rxjs/issues/3011 or https://github.com/ReactiveX/rxjs/issues/2971
