### ISSUE TITLE
Streams Page is not finishing async calls

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow-ui#549]
When testing using protractor it fails to begin the tests because the async calls made in this page do not complete.  We have a workaround in the test  for it now, but it is not ideal .  Here is what angular says about it. https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular 

This may affect issue #544

**Comment by sabbyanandan** [comment]
Addressed in the latest test-coverage improvements.
