### ISSUE TITLE
Unable to stop job or restart job from UI

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow-ui#554]
Created a job that had 2 steps.  
 1st step had a 20 seconds pause
Clicked stop button from UI and it failed to stop.  but next step still fired.

Created a job that had 2 steps
1st job 1 step failed failed with exception .
Clicked play button on failed job and nothing happened.

**Comment by sabbyanandan** [comment]
Relates to: spring-cloud/spring-cloud-dataflow#1800

**Comment by cppwfs** [comment]
Not sure it relates to #1800 .  The only relation is we can reproduce #1800 outside a curl command without the UI.

**Comment by sabbyanandan** [comment]
This will be fixed on the server-side via spring-cloud/spring-cloud-dataflow#1800.
