### ISSUE TITLE
Add logout button & show logged-in username

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#57]
As a user, I'd like add a logout button, so I can logout from dataflow-ui session.

**Acceptance:**
- Logged-in user name is displayed in the top-right corner
- Logout option is listed when you click the logged-in user name
- Clicking logout option ends the dataflow-ui session

**Comment by ghillert** [comment]
Requires the merge of PR https://github.com/spring-cloud/spring-cloud-dataflow/pull/798
