### ISSUE TITLE
Make the stream-list's status column a hyperlink for deployed streams

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#572]
As a developer, I'd like to make the stream lists status column a hyperlink, so we can show a dialog-view of details returned from the `stream info` command/endpoint. 

Refer to spring-cloud/spring-cloud-dataflow#1848 for the background.

**Acceptance:**
- Apply this change only when SCDF is configured to be on Skipper-mode (i.e., spring.cloud.dataflow.features.skipper-enabled).
- Automatically render a hyperlink when the status is either "Deployed", "Deploying", or "Failed".
- Rename the "status" column to "info".
- Add "stream info" tool-tip to the hyperlink.
- When clicking the hyperlink, open a new dialog window to include the associated stream information returned via `stream info` command/endpoint.

**Comment by sabbyanandan** [comment]
![image](https://user-images.githubusercontent.com/1562654/34222462-775a8910-e570-11e7-9e91-5ecb3c368e76.png)

**Comment by sabbyanandan** [comment]
This effort depends on spring-cloud/spring-cloud-dataflow#1848 implemented and merged to the core.

**Comment by sabbyanandan** [comment]
The backend support is now available for the SNAPSHOTs via: https://github.com/spring-cloud/spring-cloud-dataflow/commit/ff54bef595b055eaadfc27c4bdc884e32e9a8bb5.

**Comment by BoykoAlex** [comment]
@sabbyanandan is it ok to have the deployment info as a bootstrap pop-over? I thought this deployment info isn't large and shouldn't be as intrusive as a modal dialog...
Also I'm leaving the column header as it is - it's still showing the deployment status, the only difference in skipper mode one would see a hyperlink (hmm... maybe a button? or hyperlink?). Click on it brings up a pop-over (similar as for disabled deployment button in skipper mode) with the info.
What do you think?
