### ISSUE TITLE
Dashboard won't load

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#58]
As a user, I'm trying to launch the dashboard; however, I only see the `loading...` prompt and the SPA never renders. Browser console includes the attached `require.js` timeout error. Similar errors with Local and PCF dataflow-server variants. 

Note: This is noticed sporadically and it is not consistently repeatable. Perhaps there's some default timeout setting that needs bumped to allow backend service calls to complete in reasonable time?

![image](https://cloud.githubusercontent.com/assets/1562654/15505424/5eea9f9a-2178-11e6-89c0-38345720210b.png)

**Comment by BoykoAlex** [comment]
Default is 7 but we can indeed bump the value (http://requirejs.org/docs/api.html#config-waitSeconds)

**Comment by ghillert** [comment]
It was not my decision / desire to ever use requirejs - just for the record :-).

**Comment by markpollack** [comment]
Yes, but is that the root cause or some crap network and a bad timeout value?  Would there be no timeout to download angular.js w/o require.js.  Also, we could revisit the use of require.js if it seems to be an issue for us going forward.  Certainly we are not making use of it's feature set ATM.
