### ISSUE TITLE
Read-only Flo graph fails to load

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#587]
With the latest build from `master`, an undeployed ticktock stream failed with the following error. The read-only graph won't render either.

![image](https://user-images.githubusercontent.com/1562654/34729969-e9577044-f512-11e7-8d7c-416aabed5fb5.png)

![image](https://user-images.githubusercontent.com/1562654/34730035-1fd072c4-f513-11e7-854e-c5b9cb3cff71.png)

**Comment by BoykoAlex** [comment]
Hmm... can'r reproduce. Works for me with the latest in the dev mode and the built UI too on port 9393. The error doesn't help either. Any special circumstances when that happens... perhaps the deployment status is `unknown`?

**Comment by sabbyanandan** [comment]
Hmm, yeah, I'm unable to reproduce it now. As for the `unknown`, @tzolov is reviewing it via spring-cloud/spring-cloud-dataflow#1889.
