### ISSUE TITLE
Remove unused code

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#59]
As a developer, I'd like to remove unused code and refactor old terminology references. There are still several references to [xd](https://github.com/spring-cloud/spring-cloud-dataflow-ui/search?utf8=%E2%9C%93&q=xd), [admin](https://github.com/spring-cloud/spring-cloud-dataflow-ui/search?utf8=%E2%9C%93&q=admin), and [containers](https://github.com/spring-cloud/spring-cloud-dataflow-ui/search?utf8=%E2%9C%93&q=container).

**Comment by aclement** [comment]
PR merged.
