### ISSUE TITLE
Adapt to PUI color theme

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#6]
As a developer, I'd like to adapt `admin-ui` and `flo` with PUI color theme, so it inherits consistent look and feel. 

**Acceptance:**
- PUI's teal color is applied instead of the usual green

**Comment by ghillert** [comment]
The goal would be to use the:

http://styleguide.pivotal.io/

Theme it consistent with projects, such as `spring-cloud-service-broker`
