### ISSUE TITLE
Add support to switch the default version in the app registry

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#602]
As a user, I'd like to have the option to switch the default version in the app registry.

**Notes:**
The backend supports the option to switch the "default" version for an app. The following Shell command allows it.
> dataflow:>app default --id source:time --version 1.0.1.RELEASE

**Acceptance:**
- Enable this only on Skipper mode
- Remove duplicate rows for the same app from the list page (it shows multiple because of the different versions; we only want to show the "default" version)
- Design UI/UX to list all the available versions of each application
- The current app-list page is the good candidate as to where we would like to embed the versions
- This option is applicable to all the rows, so it'd be nice to consider how to reduce noise in each row

**Comment by sabbyanandan** [comment]
Hi, @tzolov:  While discussing this addition to the Dashboard, we were wondering how the following command retrieves the app specific versions. 

```
dataflow:>app list --id source:time
╔══════════════════════╤═════════╤════╤════╗
║        source        │processor│sink│task║
╠══════════════════════╪═════════╪════╪════╣
║> time-1.3.1.RELEASE <│         │    │    ║
║time-1.1.1.RELEASE    │         │    │    ║
║time-1.1.2.RELEASE    │         │    │    ║
╚══════════════════════╧═════════╧════╧════╝
```

Currently, the `/apps` endpoint brings all the available apps from the registry and it is also pagination aware. Thus, it won't be an optimized solution to fetch all the apps to determine the available versions. 

To mimic what we do in the Shell, what must we do from the UI to get the app specific versions?

**Comment by oodamien** [comment]
Work around:
The client side groups versions by application.
The applications list component have to retrieve all the applications in a single request.
