### ISSUE TITLE
Minor regression - Initial loading spinner only shown briefly

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#612]
When we fixed https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/574, we overlooked that the initial loading spinner on `index.html` also uses the `fade` CSS class. We should switch to a different class and reapply the fading animation to that new class.

![image](https://user-images.githubusercontent.com/685363/35669395-091953e8-06d9-11e8-8398-906139a23609.png)

**Comment by sabbyanandan** [comment]
Relates to #610
