### ISSUE TITLE
Fix Lint Errors due to latest Lint upgrade

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#614]
Also consider implementing https://github.com/cartant/rxjs-tslint-rules to provide more detailed linting in regards to RxJS.

Depends on https://github.com/spring-cloud/spring-cloud-dataflow-ui/pull/534

This issue will fix Lint errors - Lint _warnings_ will be addressed by https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/536

**Comment by oodamien** [comment]
Frist investigation:
- Fix type (use --fix)
- Http Deprecated: migrate to HttpClient

**Comment by ghillert** [comment]
Rebase and polished
