### ISSUE TITLE
Remove KeyValuePipe as it is not being used

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow-ui#621]

**Comment by oodamien** [comment]
KeyValuePipe is used on Runtime App Component

**Comment by sabbyanandan** [comment]
Yeah, it is used in a [few other places](https://github.com/spring-cloud/spring-cloud-dataflow-ui/search?utf8=%E2%9C%93&q=KeyValuePipe&type=), too.
