### ISSUE TITLE
Support features endpoint to disable sections of the UI

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow-ui#64]
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/640

If the task support is disabled, the UI should not show task/job related components.

**Comment by BoykoAlex** [comment]
Is this only for hiding/showing the `STREAMS`, `JOBS`, `TASKS` and `ANALYTICS` tabs?
The user can still navigate to /streams page anyway? Or that has to be prevented too?

**Comment by ilayaperumalg** [comment]
@BoykoAlex The user won't be able to navigate to `/streams` if the streams is disabled as the REST controller is modified not to expose the features that are disabled.

**Comment by ilayaperumalg** [comment]
@BoykoAlex Now I see what you mean by user still be able to navigate only at the UI. Though we disable the REST endpoints, the UI routes would still be active and load the template html without any response data. While it would be nice to prevent those navigation (if the user has bookmarked links), I think it is OK to have those as is (Given the user has disabled the features)

**Comment by BoykoAlex** [comment]
I have added the fix for router navigating to URL... I can add it here and thus we'd resolve this issue Disable navigations to specific features when they are disabled #80 as well
