### ISSUE TITLE
Remove Glyphicons / Update fontawesome version

### ISSUE THREAD

**Issue by oodamien** [spring-cloud/spring-cloud-dataflow-ui#652]
Font Awesome provides a better integration for icons (svg, fonts ...) and it's already used in the project.
Glyphicons is obsolete and it's not required for using Twitter Bootstrap 3.
- Remove all the glyphicons references / Use only Fontawesome Icons
- Update Fontawesome
- Remove import (css, fonts ...) of glyphicons

**Comment by sabbyanandan** [comment]
It appears we are on FontAwesome v4.0.7 and there are no hits for `Glyphicons` anymore. Closing it as resolved.
