### ISSUE TITLE
Rethink the loader

### ISSUE THREAD

**Issue by oodamien** [spring-cloud/spring-cloud-dataflow-ui#653]
We currently use `ng-busy` to display the state of a component to the user.

Problem:
- the UI is freeze during a request (backdrop + message loading)
- if we have 2 components on a same page without any dependency, all the UI is freeze when one component is loading (or reloading).
- With the last fix (leak memory issue), we have to handle the complete state of ngBusy in each component (not elegant)
- Not compatible with a modal

Expectation:
- Each component should display is state (use `async` pipe)
- If we have 2 components on the same page, each component display a loader
- provide a global indicator to the user when an HTTP request is on going without freeze the UI, using an interceptor HTTP

**Comment by sabbyanandan** [comment]
The progress bar on the clarity UI includes a pretty neat UX, so that's sufficient for now.
