### ISSUE TITLE
Verify the default app-version is not deletable

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#654]
As a developer, I'd like to add a validation routine to prevent the unregistration of an application; specifically, when it is already used in stream(s).

Note: This is a continuation of spring-cloud/spring-cloud-dataflow#2013, once the PR is merged, we can implement it.

**Comment by ilayaperumalg** [comment]
@sabbyanandan I just tried this and I get the exception at the server log for the stream that is `deployed`.  But, the deletion would still go through if the stream has not been deployed at least once (to have the manifest available in Skipper) - this is expected as we don't check for apps in use from the stream definitions:
```
o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request: The app [time:source:1.3.1.RELEASE] you're trying to unregister is currently used in stream 'a1'.

```

**Comment by ilayaperumalg** [comment]
Also, noticed that, when the stream is deployed and the app deletion causes exception:

```
o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request: The app [time:source:1.3.1.RELEASE] you're trying to unregister is currently used in stream 'a1'.
```

In this case, the UI doesn't handle the response as the `unregistration` dialogue box remains open without any response message.

**Comment by sabbyanandan** [comment]
Thanks for the analysis. We can address the server response via spring-cloud/spring-cloud-dataflow-ui#658.
