### ISSUE TITLE
Move bulk-import from a file button from the current position

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#659]
As a user, after entering the bulk-import link, my immediate instinct is to click the next available button (`Import A Local File`), which is a wrong button in this context. I tend to do it every time I go to this page. Maybe it is just me, but I see it as bad UX.

![image](https://user-images.githubusercontent.com/1562654/37126984-6d694ab4-2228-11e8-8e4a-69924147e883.png)

**Comment by oodamien** [comment]
We should review this UX, the `OR` is not a good option.
The button `Import a local file` is attached to the textarea which is good, maybe review the color of this button.

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/spring-cloud/spring-cloud-dataflow-ui/commit/5c01cc24fd702cef18dd30982aefa1de419c68be.
