### ISSUE TITLE
 Stream Deployment: Add Button to highlight that the file will be downloaded

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#664]
Maybe add a download icon to the button to highlight that the file will be downloaded: 

![image](https://user-images.githubusercontent.com/685363/37178670-4c7d7344-22c7-11e8-8514-2870b5b15130.png)

**Comment by sabbyanandan** [comment]
The UX has evolved significantly since when this issue .was created. Adding an icon is a trivial thing, but it won't improve the UX very much anyway.
