### ISSUE TITLE
Stream Deployment: Consider moving radio buttons to tabs

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#667]
- Consider moving the radio buttons to tabs to optimize space
- Consider removing of parent tabs (`Create Stream` could be made a button?)

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/spring-cloud/spring-cloud-dataflow-ui/commit/28f94cafeea281bb38cff41df97a2ec69c124c41.
