### ISSUE TITLE
Not opening properly NPM build 

### ISSUE THREAD

**Issue by mgobinath30** [spring-cloud/spring-cloud-dataflow-ui#684]
![screenshot 2018-03-16 09 31 21](https://user-images.githubusercontent.com/15941909/37503191-e83abe64-28fc-11e8-922b-8d356a26eb05.png)

I am getting this message while I build the project.

**Comment by sabbyanandan** [comment]
@mgobinath30: From the error, it seems you don't have SCDF-server running in the background to successfully make the connection to test the infrastructure setup. Please start the server and then building the UI project should get you started. Let us know if you continue to face build issues.
