### ISSUE TITLE
Use full column width dynamically

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#687]
![image](https://user-images.githubusercontent.com/685363/37551004-abedfa0e-293b-11e8-99e9-777928c6f7ea.png)

It would be neat if we could fill the column dynamically. Or at least according to the Bootstrap width classes.

**Comment by sabbyanandan** [comment]
Depends on what we find out from spring-cloud/spring-cloud-dataflow-ui#705.
