### ISSUE TITLE
Return-key should submit form

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#696]
When setting a property in the Composed Task Runner Create-screen, a return-key should submit a form (besides pressing `ok`).

![image](https://user-images.githubusercontent.com/685363/37686718-affc60be-2c3c-11e8-8d2b-761c1faf1550.png)

**Comment by sabbyanandan** [comment]
Also, apply it to stream properties dialog window as well.
