### ISSUE TITLE
What does `cancel` mean?

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#699]
We start having more and more cases where we can cross-reference component state. E.g. a task execution may have a link to job executions but we also have a job execution list page links to a job execution details page. Therefore, a page may have been entered from multiple source locations. Therefore, the user might have different expectation of where (s)he is expected to be routed when pressing a `Cancel` button. I wonder if we may have to have some form of `state management service` that keeps track of where the user might have been. So when somebody presses `Cancel`, then we may have a better idea of where to route the user to.

**Comment by oodamien** [comment]
The following pages should go back on the browser history (and not a redirection to the parent page):
- Application details
- Stream details
- Task details
- Task execution details

The button should display `Back` in this case.
