### ISSUE TITLE
i18n: initialize

### ISSUE THREAD

**Issue by oodamien** [spring-cloud/spring-cloud-dataflow-ui#701]
https://angular.io/guide/i18n
Lang: EN

**Comment by sabbyanandan** [comment]
Probably also related to https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1592.

**Comment by zjsun** [comment]
I forked a branch and I'm trying to work on this ...

**Comment by klopfdreh** [comment]
I provide a PR today
