### ISSUE TITLE
CTR: Duplicate app name message not appearing on UI

### ISSUE THREAD

**Issue by aclement** [spring-cloud/spring-cloud-dataflow-ui#714]
This is a spin off from https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/712 covering cases 2/3 - it captures  the problem where a composed task definition like:

`appA && appA`

returns

```
{
  "graph": null,
  "dsl": null,
  "errors": [
    {
      "position": 8,
      "message": "166E:(pos 8): duplicate app name. Use a label to ensure uniqueness"
    }
  ]
}
```

to the browser but the message doesn't make it onto the text in the DSL window for some reason.

**Comment by BoykoAlex** [comment]
Looks like composed-tasks are behind streams in terms of showing validation errors in the DSL... Think I should be able to fix this just by porting some code from streams in to composed-tasks :-)

**Comment by aclement** [comment]
Hopefully this would also cover case 3 from #712 - the graph there is turning blank because we think there are no errors, so it updated.  If there are errors after tweaking the DSL text, the graph shouldn't change until those are fixed.
