### ISSUE TITLE
Define Platform/Browser combinations we should E2E test against

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#720]
See: 

- https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/
- https://www.browserstack.com/automate/capabilities

**Comment by sabbyanandan** [comment]
As discussed in the design notes, let's start with the following set and improve upon feedback on other browser targets.

```
npm run test-saucelabs-local
npm run e2e-saucelabs-local
npm run test-browserstack-local
npm run e2e-browserstack-local
```

**Comment by sabbyanandan** [comment]
Review complete.
