### ISSUE TITLE
Disallow multiple task definitions in text-area

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#723]
Currently we allow multiple lines in the textarea for the Task Definition editor. This can cause the Flo editor to get out-of-sync:

![image](https://user-images.githubusercontent.com/685363/38839158-0d3c1e3e-4175-11e8-9316-c289a9590bfe.png)

![image](https://user-images.githubusercontent.com/685363/38839200-3b018b10-4175-11e8-9ba3-e63345db835b.png)

- We should disallow multiline definitions. 
- If the user adds multiple lines we should show an error AND disable the `CREATE TASK` button

Currently users can click the `Create Task` button:

![image](https://user-images.githubusercontent.com/685363/38839256-7f96dbb8-4175-11e8-9f7b-d8fbaa190507.png)

And then clicking the `Create` button gives you a vaguely cryptic error message.

**Comment by BoykoAlex** [comment]
Fix merged
