### ISSUE TITLE
Error logged in console for Composed Task details

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#739]
When viewing the details of a composed task, an error is logged to the console. However, everything seems to just work fine.

![image](https://user-images.githubusercontent.com/685363/38963938-0fe86966-4310-11e8-8e27-523b7f8b4190.png)

![image](https://user-images.githubusercontent.com/685363/38963985-4956799a-4310-11e8-8f9e-785ed764357f.png)

**Comment by BoykoAlex** [comment]
Works, I didn't see any errors in the console
