### ISSUE TITLE
Update Karma tests to include new browser versions

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#743]

**Comment by sabbyanandan** [comment]
Todo:
- [ ] mocks for modal dialog is not working - @ghillert 
- [ ] ~25 "flo" test failures (something related to `svg`) - @BoykoAlex

**Comment by ghillert** [comment]
Created issue: https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/874

**Comment by ghillert** [comment]
Created follow-up issues (low priority IMO):

https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/877
https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/878
