### ISSUE TITLE
Setting server context-path breaks dashboard

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#747]
_From @EHJ-52n on April 24, 2018 8:52_

### Problem

I am using the docker image `springcloud/spring-cloud-dataflow-server-local:1.4.0.RELEASE` and set the following environment configuration in my docker-compose.yml for this image:
```yaml
environment:
  - spring.cloud.dataflow.applicationProperties.stream.spring.rabbitmq.host=rabbitmq
  - server.contextPath=/dataflow
  - spring.cloud.config.enabled=false
```
The result is, that I can access the server via `http://localhost:9393/dataflow/`.

The response looks like:
```json
{
  _links: {
    dashboard: {
      href: "http://localhost:9393/dataflow/dashboard"
    },
    streams / definitions: {
      href: "http://localhost:9393/dataflow/streams/definitions"
    },
    streams / definitions / definition: {
      href: "http://localhost:9393/dataflow/streams/definitions/{name}",
      templated: true
    },
    streams / deployments: {
      href: "http://localhost:9393/dataflow/streams/deployments"
    },
    streams / deployments / deployment: {
      href: "http://localhost:9393/dataflow/streams/deployments/{name}",
      templated: true
    },
    runtime / apps: {
      href: "http://localhost:9393/dataflow/runtime/apps"
    },
    runtime / apps / app: {
      href: "http://localhost:9393/dataflow/runtime/apps/{appId}",
      templated: true
    },
    runtime / apps / instances: {
      href: "http://localhost:9393/dataflow/runtime/apps/{appId}/instances",
      templated: true
    },
    metrics / streams: {
      href: "http://localhost:9393/dataflow/metrics/streams"
    },
    tasks / definitions: {
      href: "http://localhost:9393/dataflow/tasks/definitions"
    },
    tasks / definitions / definition: {
      href: "http://localhost:9393/dataflow/tasks/definitions/{name}",
      templated: true
    },
    tasks / executions: {
      href: "http://localhost:9393/dataflow/tasks/executions"
    },
    tasks / executions / name: {
      href: "http://localhost:9393/dataflow/tasks/executions{?name}",
      templated: true
    },
    tasks / executions / execution: {
      href: "http://localhost:9393/dataflow/tasks/executions/{id}",
      templated: true
    },
    jobs / executions: {
      href: "http://localhost:9393/dataflow/jobs/executions"
    },
    jobs / executions / name: {
      href: "http://localhost:9393/dataflow/jobs/executions{?name}",
      templated: true
    },
    jobs / executions / execution: {
      href: "http://localhost:9393/dataflow/jobs/executions/{id}",
      templated: true
    },
    jobs / executions / execution / steps: {
      href: "http://localhost:9393/dataflow/jobs/executions/{jobExecutionId}/steps",
      templated: true
    },
    jobs / executions / execution / steps / step: {
      href: "http://localhost:9393/dataflow/jobs/executions/{jobExecutionId}/steps/{stepId}",
      templated: true
    },
    jobs / executions / execution / steps / step / progress: {
      href: "http://localhost:9393/dataflow/jobs/executions/{jobExecutionId}/steps/{stepId}/progress",
      templated: true
    },
    jobs / instances / name: {
      href: "http://localhost:9393/dataflow/jobs/instances{?name}",
      templated: true
    },
    jobs / instances / instance: {
      href: "http://localhost:9393/dataflow/jobs/instances/{id}",
      templated: true
    },
    tools / parseTaskTextToGraph: {
      href: "http://localhost:9393/dataflow/tools"
    },
    tools / convertTaskGraphToText: {
      href: "http://localhost:9393/dataflow/tools"
    },
    counters: {
      href: "http://localhost:9393/dataflow/metrics/counters"
    },
    counters / counter: {
      href: "http://localhost:9393/dataflow/metrics/counters/{name}",
      templated: true
    },
    field - value - counters: {
      href: "http://localhost:9393/dataflow/metrics/field-value-counters"
    },
    field - value - counters / counter: {
      href: "http://localhost:9393/dataflow/metrics/field-value-counters/{name}",
      templated: true
    },
    aggregate - counters: {
      href: "http://localhost:9393/dataflow/metrics/aggregate-counters"
    },
    aggregate - counters / counter: {
      href: "http://localhost:9393/dataflow/metrics/aggregate-counters/{name}",
      templated: true
    },
    apps: {
      href: "http://localhost:9393/dataflow/apps"
    },
    about: {
      href: "http://localhost:9393/dataflow/about"
    },
    completions / stream: {
      href: "http://localhost:9393/dataflow/completions/stream{?start,detailLevel}",
      templated: true
    },
    completions / task: {
      href: "http://localhost:9393/dataflow/completions/task{?start,detailLevel}",
      templated: true
    }
  },
  api.revision: 14
}
```

When accessing the dashboard via `http://localhost:9393/dataflow/dashboard`, I get an empty page with the following source:

```html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Spring Cloud Data Flow</title>
  <base href="/dashboard/">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link href="styles.05e4cbe82167119ec62a.bundle.css" rel="stylesheet" />
</head>

<body>
  <app-root>
    <div class="jumbotron vertical-center fade-index-spinner">
      <div class="container text-center">
        <div class="icon icon-middle" style="font-size: 96px">
          <svg class="icon-spinner-lg" width="200px" height="200px" 
              viewBox="0 0 101 101" xmlns="http://www.w3.org/2000/svg">
                <circle class="ring" fill="none" stroke-width="10%" 
                  stroke-linecap="butt" cx="50%" cy="50%" r="45%"></circle>
                <circle class="path" fill="none" stroke-width="10%"
                 stroke-linecap="butt" cx="50%" cy="50%" r="45%"></circle>
          </svg>
        </div>
      </div>
    </div>
  </app-root>
  <script type="text/javascript" src="inline.245caa4e45fc4a7126da.bundle.js"></script>
  <script type="text/javascript" src="polyfills.3d1c9d609a48f3c17cc7.bundle.js"></script>
  <script type="text/javascript" src="main.81410b088574907b4009.bundle.js"></script>
</body>

</html>
```

This code results in firefox and chromium trying to download the script files from `http://localhost:9393/dashboard/*.bundle.js` which should be `http://localhost:9393/dataflow/dashboard/*.bundle.js`.

### Potential Solution

To fix this, the `<html><head><base>` `href`attribute should be adjusted to `server.contextPath + /dashboard/` or `./dashboard/`.

### Miscellaneous

What do you think?

Is there any work-around for this possible?

_Copied from original issue: spring-cloud/spring-cloud-dataflow#2158_

**Comment by sabbyanandan** [comment]
Hi, @EHJ-52n. Thanks for reporting it. I'm just curious. Is there any particular reason for changing the context path? 

We could certainly revisit the approach to JS/CSS includes in the Dashboard. I will move it to the UI repo.

**Comment by EHJ-52n** [comment]
Hi @sabbyanandan,
we are hosting the SCDF server behind a proxy together with other services. Hence, we need to have a context path for each service behind the proxy. So, we can access all services via default ports 80 and 443.
Hope this helps!
Kind regards!

**Comment by mkandefer** [comment]
I had have this issue as well running the server behind a reverse proxy. I tried using the proxy to rerwrite the **base** tag href. While that worked on getting the page load its resources, possibly not all of them,  there were still errors reported in the console I couldn't track down.

**Comment by lancepowell** [comment]
same issue on 1.7.3.

**Comment by infogabry** [comment]
Issue is present in 2.3.0 BUILD RELEASE too.
If you setting the parameter --server.servlet.context-path in command line, the dashboard goes in error.
Home page always search resources in $REQUEST_URI/dashboard/ instead of $REQUEST_URI/$CONTEXT-PATH/dashboard/

I hope to make something wrong...

**Comment by callaertanthony** [comment]
Hi,
This is because of angular's build process. UI doesn't takes in account environment variables from dataflow API (context-path not loaded into the frontend).
The solution should be to build with run command like `ng build --base-href /$CONTEXT_PATH/dashboard/`.
So, if you want to have a base path working on frontend, you must build it from your side.
Otherwise, @ghillert, @sabbyanandan, maybe we can discuss on a default configuration that people can override ? We an available configuration, peoples will be able to use default docker image, etc. Rather than rebuild it from there sides. `envsubst` command can be use to replace the default value into the container.

**Comment by theodury** [comment]
Same issue

**Comment by uipathdevops** [comment]
team, any updates on this ?

**Comment by Manu10744** [comment]
hi :wave:
im another guy who'd be super happy if this was implemented :)

**Comment by zrav** [comment]
We run a bunch of applications in Kubernetes accessible through a single domain, routing traffic in the ingress controller to the apps based on the path, so being able to set the context root for all applications is essential. SCDF currently required special-casing with it's own subdomain due to this issue.

**Comment by jvalkeal** [comment]
Problem is that in angular there is no clean way to dynamically set context root, afaik. Things are mostly set during a compile time. `index.html` needs to know from where to download app files and then app itself would need to understand that for routing and server requests.

**Comment by Manu10744** [comment]
Has anyone tried out @callaertanthony approach? If so, did it work out for you?

**Comment by jvalkeal** [comment]
Trouble is that context root would need to be dynamic(follow what anyone could set as boot property) but angular at build time needs to know it.

If we could get an app to cleanly load, then I think remaining things what breaks would be relatively straightforward to fix.

**Comment by zrav** [comment]
Anything but / root context would already help a lot. So even a static /scdf would be very welcome.

**Comment by klopfdreh** [comment]
This is also a show stopper for us. We need to be able to set a context-path other than root.

**Comment by klopfdreh** [comment]
I am only a little bit familiar with AngularJS, but couldn't you just do something like:

index.html
```html
<script>
  window['base-href'] = window.location.pathname;
</script>
```

app.module.ts
```js
import {APP_BASE_HREF} from '@angular/common';
....
providers: [ {provide: APP_BASE_HREF, useValue: window['base-href'] } ],
....
```

See docs: https://angular.io/api/common/APP_BASE_HREF
And "Setting Base Href Dynamically in Angular 6": https://medium.com/@anandshende1994/setting-base-href-dynamically-in-angular-6-b7fe824848cf

I guess APP_BASE_HREF still exist in Angular10 isn't it?

**Comment by 651juan** [comment]
Is this fixed? When will it be released?

**Comment by Manu10744** [comment]
2.10 apparently

**Comment by klopfdreh** [comment]
2.10.0-M2 is released and you can try it out. 👍
