### ISSUE TITLE
Problem while creating new stream from UI in IE11

### ISSUE THREAD

**Issue by sachkk76** [spring-cloud/spring-cloud-dataflow-ui#75]
I was trying to patch spring-cloud-dataflow-ui-1.0.0.M2 version with spring-cloud-dataflow-server-cloudfoundry-1.0.0.M2,,as per instructions at  https://docs.pivotal.io/spring-cloud-data-flow/installing-scdf.html. but did not work.
Then I had patched spring-cloud-dataflow-ui-1.0.0.M3 with  spring-cloud-dataflow-server-cloudfoundry-1.0.0.M2.. and it worked.

So now flo UI up and running I see few problems -
1) Creating new stream from UI - when you drag drop time source and log sink to create tick tock stream...create stream  pop-up window stays there doing nothing.. no logs on dataflow-server
Same stream I can create from dataflow-shell.
Is there any issue patching flo with dataflow-server-cloudfoundry-1.0.0.M2?

2) New stream created (from shell) does not get reflected in runtime or stream definition unless browser cache is cleaned.

**Comment by BoykoAlex** [comment]
1) Is the create stream dialog staying up after you've clicked on Create button on the dialog?
2) Doesn't sound right. If you go to "Stream" tab and then open "Definitions" sub-tab you should streams created from the shell there. The list is refreshed every 2 secs - no need to wipe out the cache...

**Comment by sachkk76** [comment]
yeah "Confirm stream(s) Creation" dialog stays up when I clicked on create button forever..

**Comment by sabbyanandan** [comment]
@sachkk76: 

> yeah "Confirm stream(s) Creation" dialog stays up when I clicked on create button forever..

I'm assuming you hit "Create" button from dialog and the window just hung there - is that correct? Please note that you're deploying the stream to PCF. It is not instantaneous. In other words, all the stream apps needs deployed successfully to PCF - it takes 1-2 mins for individual apps to go through `cf push` lifecycle. With that said, yes, we would need to add a progress bar to indicate the progress in the UI.

> New stream created (from shell) does not get reflected in runtime or stream definition unless browser cache is cleaned.

Browser cache has nothing to do with stream deployments though. Could you elaborate on what you mean by this?

**Comment by sabbyanandan** [comment]
And, oh.. 

> I was trying to patch spring-cloud-dataflow-ui-1.0.0.M2 version with spring-cloud-dataflow-server-cloudfoundry-1.0.0.M2

Flo is now a OSS project [!] and "Flo for SCDF" comes pre-built in the UI going forward. You wouldn't have to patch the server anymore [😄]. The pivnet tile will be deleted with the upcoming 1.0.0.RC release.

**Comment by sachkk76** [comment]
I gave more than minutes. And dailog window still hanging there..
about 2nd point. after creating stream from shell, I refreshed the UI and steam did not appear. so I removed temp internet files from browser-history settings and refreshed it again.

**Comment by sachkk76** [comment]
Its not working in IE (v11).. It worked in Chrome.
One more question - How do I get my custom module properties visible? I could see time module (OOTB) properties in UI.

**Comment by sabbyanandan** [comment]
Since this is not an issue in Chrome, but in IE11, let's update the title/description and track it that way.

If the custom-app properties are wired the same way as the other applications and it returns in the REST response (_eg: http://localhost:9393/apps/source/file_), the UI will automatically load them. You'd have to review the application's configuration properties and whether they're returning in the response. For other issues, please open a separate issue in respective repos.
