### ISSUE TITLE
 Job executions view wouldn't load

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#77]
As a user, I'm trying to list all the batch-job (_as task_) executions; however, the list view wouldn't load and browser console includes the following error.

![image](https://cloud.githubusercontent.com/assets/1562654/15987631/96b6dd70-2fe3-11e6-9e23-b4aea60f1ce2.png)

**Comment by ilayaperumalg** [comment]
I could run a batch job successfully and see the list of executions in the UI as well as the shell. ![screen shot 2016-06-13 at 1 25 58 pm](https://cloud.githubusercontent.com/assets/151690/16000521/78cda81a-316a-11e6-8424-09010c5c009d.png)

@sabbyanandan Can you confirm if you can see the list via shell? If not, I suspect your batch job might be pointing to a different RDBMS schema. 

Irrespective of the above, there is a trivial fix needed here when there are *no* task/job executions but the UI developer console would get the above console message.

**Comment by sabbyanandan** [comment]
The actual issue was with `datasource` properties not properly configured at the Task application level. I'm able to load the task executions page now.
