### ISSUE TITLE
Incorrect placeholder in app "Name" field

### ISSUE THREAD

**Issue by benas** [spring-cloud/spring-cloud-dataflow-ui#770]
The placeholder in the "Name" field of the "Register Applications" form is `scdf-sample-app`. This is incorrect since it is not possible to specify a name with a "-" in it:

<img width="1413" alt="scdf" src="https://user-images.githubusercontent.com/1210553/39632657-fef68900-4fb5-11e8-9af0-7f36e0dbb172.png">

Here is the error when I use the same app name as the placeholder:

<img width="469" alt="scdf2" src="https://user-images.githubusercontent.com/1210553/39632808-68a4e7c0-4fb6-11e8-8e70-4611fe1ac37b.png">

**Comment by sabbyanandan** [comment]
According to the UI message, we are preventing `-` from submitting the form. We don't really have any validation on the name from the server-side perspective. We could mimic what Shell does in the UI for consistency.
