### ISSUE TITLE
Shortcut stream deployment should hide "deploy" option if >1 backend is available

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#783]
As a user, while deploying stream from Flo-dialog with multiple deployment backends, I'd like to have the option to select the backend. Today, if I deploy it from the Flo-dialog, the first in the list is used by default, but that won't be the intended platform always.

A possible solution would be to include deployment backends in the drop-down if >1 is available. _(For a single backend, we use the single-entry by default anyway)_

![image](https://user-images.githubusercontent.com/1562654/40204481-96055926-59dd-11e8-9e7c-cd6e0a34b5aa.png)
![image](https://user-images.githubusercontent.com/1562654/40205322-77019cee-59e0-11e8-9dbe-3edc96a1dcad.png)

**Comment by oodamien** [comment]
The following REST endpoint is used to create and deploy a stream:
https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#api-guide-resources-stream-definitions-create

The WS takes 3 params:
- Name (string)
- DSL (string)
- Deploy (boolean)

We have to add a new parameter to this service: deploymentProperties (map)

**Comment by ilayaperumalg** [comment]
I believe the requirement in this story is for the `Stream Deploy` workflow, not for the `Stream Create` workflow. It is the `Stream Deploy` page that leads to the list of properties page that has the platform list.

**Comment by sabbyanandan** [comment]
We would hide the "Deploy" checkbox if 1) SCDF is on Skipper mod 2) >1 platforms defined
