### ISSUE TITLE
Avoid resubmitting form values when nothing changed in the stream definition

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#786]
As a developer, I'd like to add support to prevent resubmitting the form-values when nothing changed in the stream definition.

This is the first-defense to add before it gets to the backend via spring-cloud/spring-cloud-dataflow#2224.

**Comment by ghillert** [comment]
Revisit due to https://github.com/spring-cloud/spring-cloud-skipper/issues/645
