### ISSUE TITLE
Don't update Stream when properties have not changed

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#789]
We could handle the use-case better where no property changed. In that case the update REST endpoint will send back an error: `Package to upgrade has no difference than existing deployed/deleted package. Not upgrading`. Therefore, we should:

* only activate the Deploy the Stream button when values have changed
* OR do better validation once the `deploy` button has been pressed
* provide better feedback in case the error is returned from the server

**Comment by sabbyanandan** [comment]
There has been a long discussion on this topic in the past. The result was that we could not realistically track the changes just on the front-end since it is possible for someone to change to influence the applications outside of SCDF. We ended up deciding not doing any tracking for now.
