### ISSUE TITLE
Arbitrary Boot properties cannot be supplied from Flo

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#790]

**Comment by BoykoAlex** [comment]
I recall that we talked about it in the past... Tried to look for commits related to this topic but couldn't find anything.
I vaguely remember something to turn on/off validation in the graph similar to tasks page. By the tasks page i mean the DSL editor that we had with content assist and validation. Validation could have been turned off with a toggle button.

If we'd like to do the minimum work i could comment out properties validation from Flo. Just want to ensure that is what we'd like to do here.
