### ISSUE TITLE
Investigate why sensitive values are submitted with asterisks

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#794]
As a user, I'm attempting to deploy a stream with sensitive property values such as passwords; however, the UI is submitting them as asterisks instead of the actual value.

See the [Gitter thread](https://gitter.im/spring-cloud/spring-cloud-dataflow?at=5b0a64c1c712f5612536d3df) re v.1.5 feedback.

Also, investigate why the fix via spring-cloud/spring-cloud-dataflow-ui#780 is not good enough.

**Comment by tzolov** [comment]
wasn't able to reproduce the problem using latest SCDF & UI build snapshot.  I've successfully submitted a sensitive property from UI to the controller.

**Comment by jvmlet** [comment]
Would you please whitelist the  `spring.cloud.stream.rabbit.bindings.input.consumer.binding-routing-key` in your custom processor app , register  the stream with `:inEx > my-custom-app --spring.cloud.stream.rabbit.bindings.input.consumer.binding-routing-key=someKey > :outEx` and click `deploy` in UI. Then open the rabbit MQ console and see the routing key.

**Comment by jvmlet** [comment]
I'm able to reproduce by running below command from shell
````
stream create --name testStream --definition ":inEx> my-custom-app --spring.cloud.stream.rabbit.bindings.input.consumer.binding-routing-key=someKey   > :outEx
````
Then open the UI and click `start->deploy`
My environment 1.5 GA for  `shell`, `CF SCFD`

**Comment by ilayaperumalg** [comment]
@jvmlet I checked the 1.5 GA local SCDF server with the above mentioned stream and the routing key is set correctly. 

![screenshot-rabbitmq](https://user-images.githubusercontent.com/151690/40642269-3540d136-633a-11e8-984b-eeeb92fa8bf0.png)

**Comment by jvmlet** [comment]
I've recked the behaviour , works as expected.
Propbably I overlooked the SCDF version I was checking  against (it was 1.5 SNAPSHOT)
Sorry for buthering

**Comment by ilayaperumalg** [comment]
@jvmlet Thanks for confirming. Closing this as invalid.
