### ISSUE TITLE
Move JSON deserialization for Job-related calls to domain model

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#796]
Since we do it already for several domain model classes, we should refactor the deserialization of Job/Task related REST calls to the respective domain model classes, instead of doing it in the services.

This allows for better isolation and easier testing. Therefore, as part of this issue we should also add unit tests.

**Comment by sabbyanandan** [comment]
Revisit this in the context of consistently applying for UI <-> Service calls.
