### ISSUE TITLE
Fix Task Definition status returns `unknown`

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#800]
`/tasks/definitions?page=0&size=30`, it returns `unknown` each time for all the entries

![image](https://user-images.githubusercontent.com/685363/40927388-52bd14d4-67ba-11e8-8258-021d36af954f.png)

**Comment by cppwfs** [comment]
Not sure why we even need this column.    Its not really meaningful.   The task definition either exists or it doesn't.

**Comment by ghillert** [comment]
Not a UI per se. The server always returns `unknown` right now. Created an issue for SCDF: https://github.com/spring-cloud/spring-cloud-dataflow/issues/2254

The outcome may affect this ticket though (refactoring).
