### ISSUE TITLE
Add Schedule Details

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#812]
As a developer, I'd like to add a details page for a particular Schedule, so we can navigate to, inspect, and monitor the scheduled parameters such as cron-expression.

 - [x] Schedule details
 - [x] Execution status per schedule
 - [x] Tabular model for consistent UX with rest of the Detail pages
 - [ ] Plaecholder for metrics/status per schedule
 - [x] Navigation mechanism between Task List and each Schedules and vice-versa
 - [ ] Test coverage

child of #809

**Comment by cppwfs** [comment]
What does execution status per schedule mean?

**Comment by sabbyanandan** [comment]
It's the multiple red/green dots we discussed in the inception. It should be captured in the design docs.

**Comment by cppwfs** [comment]
Gotcha.  Just verifying that there was nothing missing from the SPI.   This data is obtained from task-execution requests.
