### ISSUE TITLE
Docker artifact registration fails with validation error

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#814]
As a user, while attempting to register a Docker artifact from the UI, I'm blocked by a validation error. Docker artifacts don't have to begin with the `docker://` pattern. 

**Error:**

![image](https://user-images.githubusercontent.com/1562654/41068281-a4c8f592-699d-11e8-91f6-0491b5a8b4ea.png)

**Here are a few examples:**

![image](https://user-images.githubusercontent.com/1562654/41068303-b724d8fa-699d-11e8-80c8-705f3ebaeef2.png)

**Comment by ghillert** [comment]
Backported to 1.5.x
