### ISSUE TITLE
Invalid Stream state upon repetitive deployment in Skipper mode

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#816]
As a user, I've attempted to deploy a stream and I immediately deleted it while it was in progress. However, when recreating the same stream, I see a bogus status for the Stream in the UI. 

notes:
- The status should be `Undeployed`, but it shows as `failed`. 
- Though redeploying with the same name, it is still the first time recreating it. Given the version is coming from Skipper, I'm also seeing version info re-populated in the deployment screen. 

**1) create:**

![image](https://user-images.githubusercontent.com/1562654/41426798-a3464eb4-6fb9-11e8-8b29-761a3c8658ca.png)

**2) Deploy and destroy immediately**

![image](https://user-images.githubusercontent.com/1562654/41426831-bb93bd8a-6fb9-11e8-84e1-a7ba729402c4.png)
![image](https://user-images.githubusercontent.com/1562654/41426838-c256605a-6fb9-11e8-853e-8a5e117e3bd6.png)

**3) recreate** _(just created; not deployed yet, but the statis is `Deployed`!)_

![image](https://user-images.githubusercontent.com/1562654/41426884-f72ec204-6fb9-11e8-8ecf-25196baf28c3.png)

**4) bogus properties** _(notice the extra properties)_

![image](https://user-images.githubusercontent.com/1562654/41426929-1ce2f8f8-6fba-11e8-87a4-7ed1f4036d71.png)

**Comment by ghillert** [comment]
Backported to 1.5.x
