### ISSUE TITLE
Link to the last Task Execution from Task Definition Page

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#817]
With the fixing of https://github.com/spring-cloud/spring-cloud-dataflow/issues/2254 we not only have a status in regards to the last TaskExecution available as part of the Task Definition list, but we also receive the the entire TaskExecution metadata in the REST response.

Thus, we could:

1) Link to the respective Task Execution that is "responsible" for the show status
2) Provide some basic additional information surrounding the Task Definition status e.g. via a pop-over

**Comment by sabbyanandan** [comment]
We have this supported now.
