### ISSUE TITLE
Triggering App Default fails with an infinite redirect

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#832]
As a user, while attempting to set default App version from a secured SCDF-server, I see an infinite redirect and the action fails.

versions:
![image](https://user-images.githubusercontent.com/1562654/41942570-be40dffa-7954-11e8-9f75-8959697fea5e.png)

change: (why is it called `Validate`?)
![image](https://user-images.githubusercontent.com/1562654/41942583-c9a7c606-7954-11e8-88fa-240f5f9f03d2.png)

error:
![image](https://user-images.githubusercontent.com/1562654/41942608-dad213e6-7954-11e8-99bd-1f104110c537.png)

request/response:
![image](https://user-images.githubusercontent.com/1562654/41942636-fef045ae-7954-11e8-8b5a-bde8a50dc0cd.png)

**Comment by ghillert** [comment]
As part of a comprehensive fix we should prioritize https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/536

**Comment by ghillert** [comment]
Backported to 1.5.x
