### ISSUE TITLE
Task screen looks strange - shows error message on-load

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#833]
With enabled basic security, loading the task screen (with no tasks) results in a bogus error message. 

Also, the screen should probably not show the filter input box but rather display a message that no task definitions are available.

![image](https://user-images.githubusercontent.com/685363/41944829-a0deb36a-7945-11e8-854e-e814f96d62bc.png)

**Comment by ghillert** [comment]
Will be solved by https://github.com/spring-cloud/spring-cloud-dataflow/pull/2293

**Comment by sabbyanandan** [comment]
This has been addressed in SCDF core.
