### ISSUE TITLE
Deployer property "local.inheritLogging" doesn't work properly when set in UI

### ISSUE THREAD

**Issue by bustareason** [spring-cloud/spring-cloud-dataflow-ui#854]
Setting the deployer property "local.inheritLogging" to "true" in the UI (under the Deployment Platform section) doesn't work as expected.  Instead of showing evaluated expressions (e.g. in a transform), the logs will show literal expressions.  Steps to repro (tested on 1.6.0.BUILD-SNAPSHOT (spring-cloud-dataflow-server-local):

1.  Create a stream using the shell:
```stream create foo --definition "http --server.port=9000 | transform --expression='new String(payload).toUpperCase()' | log"```

2.  Go to the UI and deploy the app, setting the deployer property for `local.inheritLogging` to `true`.

3.  Post data to the stream using the shell:
```http post --target http://localhost:9000 --data foosss```

4.  Check the data flow server logs - you should see something similar to this:
```INFO 17493 --- [container-0-C-1] log-sink                                 : new String(payload).toUpperCase()```

Expected:
```INFO 17493 --- [container-0-C-1] log-sink                                 : FOOSSS```

**Comment by sabbyanandan** [comment]
@oodamien: See more discussion on this thread [here](https://gitter.im/spring-cloud/spring-cloud-dataflow?at=5b48b68526aa91065e90df93).

**Comment by oodamien** [comment]
Create stream definition: `"http --server.port=PORT | transform --expression='new String(payload).toUpperCase()' | log"` (x3)

Tests:
1 Deploy a stream FOO1 with the property `deployer.*.local.inheritLogging=true`
2 Deploy a stream FOO2 with the properties `deployer.*.local.inheritLogging=true`, `app.transform.transformer.expression='new String(payload).toUpperCase()'`
3 Deploy a stream FOO3 with the properties `deployer.*.local.inheritLogging=true`, `app.transform.transformer.expression=new String(payload).toUpperCase()`

Perform in the shell:
`http post --target http://localhost:PORT --data foosss` (x3)
Result:
1 FOO1: `FOOSSS`
2 FOO2: `new String(payload).toUpperCase()`
3 FOO3: `FOOSSS`

Stream Manifest:
1 FOO1: `"transformer.expression": "new String(payload).toUpperCase()"`
2 FOO2: `"transformer.expression": "'new String(payload).toUpperCase()'"`
3 FOO3: `"transformer.expression": "new String(payload).toUpperCase()"`
