### ISSUE TITLE
Add hint to indicate the requirement to register applications

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#87]
As a developer, I'd like to add a hint/warning message in ui, so when the Apps tab result is empty users will have the indication to register apps.

**Acceptance:**
- empty `app list` results with the [error message](https://github.com/spring-cloud/spring-cloud-dataflow/commit/682586426c5b8d29d602af7af001933d4841b26b#diff-eb78b13f6ad015cff293634630dd0346R195) returned by the backend server

**Comment by markfisher** [comment]
would be nice if the displayed message is consistent with what we just merged for the shell: https://github.com/spring-cloud/spring-cloud-dataflow/commit/682586426c5b8d29d602af7af001933d4841b26b

**Comment by sabbyanandan** [comment]
Agreed. I updated the description.
