### ISSUE TITLE
Add an extra step in the UI to confirm whether or not to show all Boot properties 

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#879]
As a user, if I don't register the App with companion artifact, I'd like to be warned about the available Boot properties as possibilities. 

Currently, in the Shell, if we don't provide the companion artifact for an App, we show the following message on autocomplete trigger. It'd be good to adopt a similar pattern in the UI, so users can confirm whether or not they'd like to see all properties. 

> dataflow:>stream create foo --definition "http | userprocessor -- (HIT-TAB-BUTTON)
> dataflow:>stream create foo --definition "http | userprocessor --Display all 1123 possibilities? (y or n)

**Comment by oodamien** [comment]
Dialog properties (stream creation / stream deploy): display a message + redirect to the app page.

**Comment by tzolov** [comment]
- The 'SHOW ALL PROPS' button should show only on apps that don't have metadata bundled in. For testing you can use the following app: `app register --name appender --type processor --uri https://github.com/sabbyanandan/partitions/raw/master/jars/appender-0.0.1-SNAPSHOT.jar`
- The same logic should apply in the create-stream table when you click on the app's settings button
- The same logic should apply on stream-deploy window when you press the edit button.
