### ISSUE TITLE
Include environment info in the About tab

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow-ui#91]
Helps ensure the right bits have been assembled in the final product.

**Comment by trisberg** [comment]
Should we also include the feature toggles?

**Comment by ghillert** [comment]
@trisberg Unless I miss or overlooked something, this is more tricky than thought. We don't seem to centrally specify the "core version" in the poms. In SCDF Kubernetes I have:

```xml
<properties>
	<spring-cloud-dataflow.version>1.2.0.BUILD-SNAPSHOT</spring-cloud-dataflow.version>
	...
</properties>
```

But that does not exist in SCDF Local. 

We then also need to expand the management endpoint on the server. Currently we only return:

```
info:
  app:
    name: "@project.artifactId@"
    description: "@project.name@"
    version: "@project.version@"
```

@sabbyanandan How should we name that property? 

Maybe **info.app.dataflow.core.version** ?

**Comment by trisberg** [comment]
I think we should rely on runtime info as much as possible, I'm adding this to the deployer spi:

```
	/**
	 * Return the environment info for this deployer. This info should include the
	 * following: 'deployer-class-name','deployer-version', 'deployer-spi-version', 'platform-type',
	 * 'platform-client-version', 'platform-host-version', 'java-version', 'spring-version', 'spring-boot-version'.
	 *
	 * @return the app deployment environment info
	 */
	Map<String, String>  environmentInfo();
```

Then the server could add it's own version and show this info via some endpoint, then the UI/Shell could use that endpoint and add their own version to the output which could be an aggregate of the following values from various sources:

Deployer:
'deployer-class-name'
'deployer-version'
'deployer-spi-version'
'platform-type',
'platform-client-version'
'platform-host-version'
'java-version'
'spring-version'
'spring-boot-version'

Server:
'data-flow-core-version'
'data-flow-server-class-name'
'data-flow-server-version'

Shell/UI:
'data-flow-shell-version'/'data-flow-ui-version'

**Comment by ghillert** [comment]
PR https://github.com/spring-cloud/spring-cloud-dataflow-ui/pull/172
