### ISSUE TITLE
Job restart button inside the execution page of a particular job

### ISSUE THREAD

**Issue by siddhantsorann** [spring-cloud/spring-cloud-dataflow-ui#919]
I think it would be a good idea to implement the restart job button/option when the user opens the execution of a particular job. Spring batch admin had the same. http://localhost:9393/dashboard/#/jobs/executions/3
Inside here. Thanks.

**Comment by sabbyanandan** [comment]
Hi, @siddhantsorann. We already have that option in the Job's list page - see [here](http://docs.spring.io/spring-cloud-dataflow/docs/1.7.0.RELEASE/reference/htmlsingle/#dashboard-jobs). Isn't that what you're looking for?

**Comment by siddhantsorann** [comment]
My point was that when a user goes to the task execution page from where he can select the job which takes him inside the job execution page. In there currently, there is no option. So the user will need to open the job executions and find the job for the respective task and restart from there.
