### ISSUE TITLE
Unable to create new Tasks

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#921]
As a user, while attempting to create Tasks, I notice that the "Create Task" button is hidden (see below), and it won't show up until Task Apps are registered. 

I don't get notified about it, though. I have had to assume and register Tasks to unhide the button. However, I do see a message when there isn't any Task definitions.

![image](https://user-images.githubusercontent.com/1562654/46085118-23677400-c15a-11e8-8e11-ce4c4a69c072.png)

**Comment by ghillert** [comment]
Created a follow-up issue: https://github.com/spring-cloud/spring-cloud-dataflow/issues/2463
