### ISSUE TITLE
Create Stream - Ensure that tool-tips stay inside window

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#93]
Ensure that the tool-tips for apps under the `Create Stream` dialog don't go beyond the browser window.

![image](https://cloud.githubusercontent.com/assets/685363/16509191/100f3aea-3ed6-11e6-88db-17e32c6ece8c.png)

**Comment by BoykoAlex** [comment]
Think we should really come up with something else for the tooltip. Tooltip is supposed to show a bit of information and we are showing a lot of info... perhaps it should become a pop-over (in the case of palette shapes)

**Comment by sabbyanandan** [comment]
This has been addressed in the rewrite.
