### ISSUE TITLE
Revisit label + text positioning in all the list pages

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#935]

**Comment by sabbyanandan** [comment]
see:

![image](https://user-images.githubusercontent.com/1562654/46634791-ed85a080-cb06-11e8-8aec-46281e5ae426.png)

**Comment by jvalkeal** [comment]
@oodamien Looks like this is just fixing `.label` to have same style as  is `.label-appty`. Thus it really doesn't cause any visible changes. I'm not sure if @sabbyanandan meant to center text vertically as label seem to be slightly above center. At least I didn't see any changes when tried this.
