### ISSUE TITLE
Scheduling - Pressing "Schedule the task" clears Schedule name input field

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#938]
I have the following schedule:

![image](https://user-images.githubusercontent.com/685363/46643602-8c66c880-cb18-11e8-86c4-d74a597994d4.png)

When I press the "Schedule the task" button the first time, `Schedule name` input field is cleared:

![image](https://user-images.githubusercontent.com/685363/46643681-d6e84500-cb18-11e8-933c-679402c21005.png)

I have to fill-in the schedule name a second time and then it works.

**Comment by oodamien** [comment]
Duplicate #938
