### ISSUE TITLE
Apps Property Details - Make columns flexible or use Ellipsis

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#94]
For long property names you can currently observe some overlapping between columns - see screenshot.

We should either make columns more flexible or use an ellipsis for long property names and provide a tool-tip with the full name.

![image](https://cloud.githubusercontent.com/assets/685363/16528440/b23bc2de-3f58-11e6-90b6-bd0526cc1c15.png)

**Comment by sabbyanandan** [comment]
This has been addressed in the UI rewrite; it is included in the 1.3 release.
