### ISSUE TITLE
None of the bulk stream operations works

### ISSUE THREAD

**Issue by tzolov** [spring-cloud/spring-cloud-dataflow-ui#942]
As visible from the screenshot, none of the Stream bulk operations seems to work with latest 1.7.0 BS

- No error are thrown in the JS console 
- No messages are generated/send in the `networking` tab

<img width="1235" alt="screen shot 2018-10-09 at 9 02 28 pm" src="https://user-images.githubusercontent.com/1351573/46692157-d7f7a000-cc06-11e8-8454-492631e004c5.png">

**Comment by oodamien** [comment]
Not reproduce on the same env.
Waiting debug/more infos from @tzolov

**Comment by jvalkeal** [comment]
Worked ok, btw you should get new dialog and after that you can expect something to happen.

**Comment by sabbyanandan** [comment]
+1; everything appears to be normal on my side also. @tzolov: Could you please double check on the 1.7 RC1 bits?

**Comment by tzolov** [comment]
I still can not make it work on my local Chrome browser, but obviously this is a local issue. It works with the Safari browser.
