### ISSUE TITLE
Spring Cloud Data Flow UI SideMenu Style Bug

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#972]
_From @LoopSun on October 30, 2018 14:51_

Description:

> runtime/apps
> streams
> tasks
> jobs
> analytics
These menu have a style 
```
element.style {
    display: none;
}
```

Release versions:

1.7.0.RELEASE

Custom apps:
None

Steps to reproduce:
None

Screenshots:
![image](https://user-images.githubusercontent.com/15653731/47726746-13314000-dc96-11e8-90e6-5709416f2295.png)

![image](https://user-images.githubusercontent.com/15653731/47726831-3a880d00-dc96-11e8-83b9-cd250a769d5e.png)

Additional context:
None

_Copied from original issue: spring-cloud/spring-cloud-dataflow#2524_

**Comment by oodamien** [comment]
The feature info should return false for the options:
```featureInfo: {
    analyticsEnabled: false,
    streamsEnabled: false,
    tasksEnabled: false,
    skipperEnabled: false,
    schedulerEnabled: false
}```

In that case, the items are not display.

**Comment by sabbyanandan** [comment]
Ah, good point. Thanks for checking.

Hi, @LoopSun. To see all the left-nav items, you need to have feature toggle enabled for them. Make sure to double check the feature flags - more details [here](http://docs.spring.io/spring-cloud-dataflow/docs/1.7.0.RELEASE/reference/htmlsingle/#enable-disable-specific-features).
