### ISSUE TITLE
Support OAuth2/OpenID Connect Authentication only

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#984]
- Remove all code related to username/password authentication
- Integration [angular-auth-oidc-client](https://github.com/damienbod/angular-auth-oidc-client
) library
  - Ensure integration works for development (Angular CLI) and production

OAuth2/OpenID Connect shall be the only supported security option

**Comment by sabbyanandan** [comment]
We will revisit this when we switch to Spring Security 5.2.x.
