### ISSUE TITLE
Paging is not working when filtered by task name

### ISSUE THREAD

**Issue by traceyyoshima** [spring-cloud/spring-cloud-dataflow-ui#991]
- View a Task Filtered by Name.
- Click on the next page or view more items per page and the page remains on 1.

Dataflow 1.7.0

**Comment by traceyyoshima** [comment]
Preliminary info:
- We have about 50k task executions.
- Through the web browser inspector, console output I see: ERROR TypeError: Cannot read property 'page' of undefined.

I'll delve deeper into the issue and get back to you with more info. Is there any information specifically that would help??

**Comment by oodamien** [comment]
![image](https://user-images.githubusercontent.com/487067/49233047-6a414680-f3f5-11e8-8de8-7a1d67a170f8.png)
