### ISSUE TITLE
Protractor Docker Plugin: Make SCDF/Skipper versions configurable

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#992]
First, add support for setting the Skipper environment variable (did not exist yet).

Using an environment variable, users should be able to make the:

* Spring Cloud Data Flow version
* Spring Cloud Skipper version

configurable (The Docker tag) using environment variables. If not specified they should default to the latest version.

**Comment by sabbyanandan** [comment]
Stale; closing.
