### ISSUE TITLE
Connectors bend and overlap for duplicate streams that start with named-destinations

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#996]
As a user, while copying the same stream with named-destinations a few times, I see the connectors bend, overlap with one another, and are basically messed up.

![image](https://user-images.githubusercontent.com/1562654/49239778-72c75c00-f3b8-11e8-9fd3-ca13a4d6a3e1.png)

**Should we instead error saying duplicate streams?**

When I change the destination to something else, they automatically get adjusted.

![image](https://user-images.githubusercontent.com/1562654/49239956-eec1a400-f3b8-11e8-8590-36b1a3518b82.png)

**Comment by BoykoAlex** [comment]
There is special routing for overlapping links... This routing doesn't work with "beizer curves" links it seems...

**Comment by sabbyanandan** [comment]
Also, look at the 2nd `hdfs` node, the way how it bubbled up to align with previous pipeline. That seems odd, too.

![image](https://user-images.githubusercontent.com/1562654/49240596-6e03a780-f3ba-11e8-8c5a-2205ff85e555.png)

**Comment by BoykoAlex** [comment]
Not sure we can do much about that node unless we find an alternative layout algorithm.

**Comment by BoykoAlex** [comment]
Overlapping connections issue fixed in Flo: https://github.com/spring-projects/spring-flo/commit/6dad59e37181b31ec8f572d3575e6e48a7d91ef2
Should be available in Flo 0.7.6

**Comment by sabbyanandan** [comment]
Thanks, @BoykoAlex. Feel free to PR it here, we can upgrade and backport to different branches.
